### ISSUE TITLE
Failure to run

### ISSUE THREAD

**Issue by andrewheiss** [lierdakil/pandoc-crossref#10]
With pandoc 1.13.2 on OS X 10.10.3, pandoc-crossref is unusable (at least on my system): 

    ~/.../filters/pandoc-crossref : pandoc -F pandoc-crossref.hs -i demo.md -o blah.html

    pandoc-crossref.hs:152:50:
        Couldn't match expected type ‘Pandoc’
                    with actual type ‘Either Text.Pandoc.Error.PandocError Pandoc’
        In the second argument of ‘($)’, namely ‘readMarkdown def s’
        In the second argument of ‘($)’, namely
          ‘getInlines $ readMarkdown def s’

    pandoc-crossref.hs:167:48:
        Couldn't match expected type ‘Pandoc’
                    with actual type ‘Either Text.Pandoc.Error.PandocError Pandoc’
        In the second argument of ‘($)’, namely ‘readMarkdown def s’
        In the second argument of ‘($)’, namely
          ‘getBlocks $ readMarkdown def s’

    pandoc-crossref.hs:179:9:
        Non type-variable argument
          in the constraint: MonadState References m
        (Use FlexibleContexts to permit this)
        When checking that ‘withTmplV’ has the inferred type
          withTmplV :: forall (m :: * -> *) b.
                       MonadState References m =>
                       (String -> Maybe MetaValue) -> m b -> m b
        In an equation for ‘applyTemplate’:
            applyTemplate i t tmpl
              = withTmplV internalVars $ replaceTemplate tmpl
              where
                  withTmplV f g
                    = do { modify $ ...;
                           .... }
                  internalVars "i" = Just $ MetaInlines i
                  internalVars "t" = Just $ MetaInlines t
                  internalVars _ = Nothing
    pandoc: Error running filter pandoc-crossref.hs

**Comment by lierdakil** [comment]
Pandoc 1.14 (a.k.a. repo version) has changed API interface. [pandoc-1.14 branch](https://github.com/lierdakil/pandoc-crossref/tree/pandoc-1.14) contains some work w.r.t. this change. You may want to try it and see if it works. I think it doesn't support external yaml settings as of yet though.

**Comment by lierdakil** [comment]
And please do check your pandoc version, since `PandocError` type is introduced in 1.14, and should not be present in 1.13.2. If it is, then we messed up badly somewhere...

**Comment by andrewheiss** [comment]
If I have 1.13.2 (in /usr/local/bin) and 1.14 (in ~/.cabal/bin) installed simultaneously, but I don't include 1.14 in the $PATH, shouldn't it not try to run 1.14 (and give me 1.14 errors)?

Even if I explicitly tell it to use 1.13.2, I get the same errors: 

    ~/.../filters/pandoc-crossref : /usr/local/bin/pandoc --version
    pandoc 1.13.2
    ...

    ~/.../filters/pandoc-crossref : /usr/local/bin/pandoc -F pandoc-crossref.hs -i demo.md -o blah.html

    pandoc-crossref.hs:152:50:
        Couldn't match expected type ‘Pandoc’
                    with actual type ‘Either Text.Pandoc.Error.PandocError Pandoc’
        In the second argument of ‘($)’, namely ‘readMarkdown def s’
        In the second argument of ‘($)’, namely
          ‘getInlines $ readMarkdown def s’
    (etc...)

**Comment by andrewheiss** [comment]
Ooh. Switching to the 1.14 branch *almost* fixes it. There's only one error left. Still strange that 1.13.2 is giving all those 1.14-related errors, though. 

    pandoc-crossref.hs:167:9:
        Non type-variable argument
          in the constraint: MonadState References m
        (Use FlexibleContexts to permit this)
        When checking that ‘setTmplV’ has the inferred type
          setTmplV :: forall (m :: * -> *).
                      MonadState References m =>
                      (String -> Maybe MetaValue) -> m ()
        In an equation for ‘applyTemplate’:
            applyTemplate i t tmpl
              = do { setTmplV $ \ n -> ...;
                     res <- replaceTemplate tmpl;
                     setTmplV $ const Nothing;
                     .... }
              where
                  setTmplV f = modify $ \ s -> ...
    pandoc: Error running filter pandoc-crossref.hs

**Comment by lierdakil** [comment]
It's likely 1.13.2 *binary* using 1.14 *library* from your `~/.ghc`, where cabal installed it. I'm not sure how to fix it, but I'd advise to simply use a sandbox for pandoc-1.14, which does not pollute ghc package set in any way.

As for other error, what ghc version do you run?

**Comment by andrewheiss** [comment]
I'm using GHC 7.10.1.

I'd never heard of cabal sandboxes before (I live with Python; never touched Haskell). Reinstalling 1.14 now.

**Comment by lierdakil** [comment]
Can't really test with ghc 7.10, but I can try to specify type, so maybe it helps. One moment.

**Comment by lierdakil** [comment]
Ok, tried specifying type conservatively. Also merged support for settings file into `pandoc-1.14` branch. See if this helps.

**Comment by andrewheiss** [comment]
Ack. Finally emerged from cabal hell with freshly sandboxed 1.14 install, and the binary seems to work fine. However, when using `pandoc-crossref.hs` as a filter, I get errors about Text.Pandoc and other libraries not existing. I'm absolutely sure this is because ghc isn't looking at the sandbox path (despite it being in my `$PATH`—when the filter is run, it doesn't know where to look for the `import Text.Pandoc`, etc. commands).

So this is totally off topic from this bug, but I have no idea how to connect the sandboxed version of 1.14 to the filter. Sorry! :)

**Comment by lierdakil** [comment]
You can build an executable from within cabal sandbox and use that:

```bash
cabal --sandbox-config-file=/full/path/to/pandocs/cabal.sandbox.config exec -- ghc --make pandoc-crossref.hs
```

This will create `pandoc-crossref` executable, which you can then use with pandoc-1.14 as usual (i.e. `pandoc -F pandoc-crossref ...`). I will be adding cabal build file later, but for now this should do.

**Comment by andrewheiss** [comment]
Getting closer! I can compile pandoc-crossref just fine, but then it complains about not finding a file:

    ~/.../filters/pandoc-crossref : cabal --sandbox-config-file=/Users/andrew/Research/Markdown\ magic/pandoc_dev/cabal.sandbox.config exec -- ghc --make pandoc-crossref.hs
    [1 of 1] Compiling Main             ( pandoc-crossref.hs, pandoc-crossref.o )
    Linking pandoc-crossref ...
    ld: warning: directory not found for option '-L/private/tmp/ghc20150402-41611-1b15z9c/ghc-7.10.1/gmp-static'
    ~/.../filters/pandoc-crossref : pandoc -F pandoc-crossref demo.md -o asdf.html
    pandoc: Error running filter pandoc-crossref
    pandoc-crossref: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

(I'm so sorry about this super long thread!)

**Comment by lierdakil** [comment]
Try `pandoc -F ./pandoc-crossref ...`, since it's not in PATH.

**Comment by andrewheiss** [comment]
THAT'S IT. I hadn't thought to include `./`, since I figured the command would see it in the current folder. Thanks so much!

In other news, it ran perfectly fine with no errors, so your conservative type specification worked.

**Comment by lierdakil** [comment]
Glad to hear it. Closing this as resolved then.
