### ISSUE TITLE
Latex outputs of subfigure block are not centered

### ISSUE THREAD

**Issue by dnguyen85** [lierdakil/pandoc-crossref#100]
I have noticed that `pandoc` seems to center all stand-alone figures, but `pandoc-crossref`'s latex outputs for subfigure environment is not centering them. From the example:

```
<div id="fig:subfigures">
![Subfigure a](img1.jpg){#fig:}

![Subfigure b](img1.jpg){#fig:subfigureB}

Subfigures caption
</div>
```
produces this latex output:
```
\begin{figure}

{\subfloat[Subfigure a]{\includegraphics{img1.jpg}\label{fig:}}}

{\subfloat[Subfigure b]{\includegraphics{img1.jpg}\label{fig:subfigureB}}}

	\caption{{Subfigures caption}}

	\label{fig:subfigures}

\end{figure}
```

Can we add an option to produce `\centering` in the Latex output?

**Comment by lierdakil** [comment]
I don't think we need an option even. It's honestly just an oversight on my part.

**Comment by dnguyen85** [comment]
Just tried this out. Works perfectly. Thanks for the fix.
