### ISSUE TITLE
Figure references appear as 1,2,3 instead of range 1-3

### ISSUE THREAD

**Issue by omrihar** [lierdakil/pandoc-crossref#101]
Hi,

first off, thanks for the great plugin!
I'm trying to get a range of figures represented as a hyphenated list (1-3) but all I get is 1,2,3.
The way I go about it is the following:
In the YAML header I defined 
```yaml
figPrefix:
   - Fig.
   - Figs.
rangeDelim: "&ndash;"
```
Then in the text I put the following `[@fig:embeddings1;@fig:embeddings2;@fig:embeddings3]` where
the `fig:embeddingsN` are the labels. I don't know if it's relevant, but I'm using the `americal-physical-society.csl` file for the style definition.
I know the `figPrefix` works because in the text I get `Figs. 1, 2, 3`.

Any help would be appreciated!

Thanks!
Omri

**Comment by lierdakil** [comment]
If you're targeting LaTeX output, typical LaTeX references don't support reference ranges. Try  `cref` output:

```yaml
cref: true
```

**Comment by omrihar** [comment]
Thanks! That was indeed the problem. I should have re-read the documentation more carefully.
I also had to add
```yaml
header-includes:
   - "\\newcommand{\\crefrangeconjunction}{--}"
```
to change the default "to" to an en-dash.

**Comment by lierdakil** [comment]
Glad to hear that you resolved the issue.

вт, 10 янв. 2017 г. в 15:12, Omri Har-Shemesh <notifications@github.com>:

**Comment by sjackman** [comment]
I use `rangeDelim: "&ndash;"` for HTML. Thanks for the suggestion to use `crefrangeconjunction`, @omrihar. That worked for me!

@lierdakil Would you be up for modifying pandoc-crossref so that it outputs the necessary `crefrangeconjunction` based on `rangeDelim`?
