### ISSUE TITLE
Error installing pandoc-crossref on macOS 10.12.2

### ISSUE THREAD

**Issue by tsamsonov** [lierdakil/pandoc-crossref#102]
When I try to install the package through cabal I get the following:
```
Butterfly:~ tsamsonov$ cabal install pandoc-crossref
Resolving dependencies...
internal error: could not construct a valid install plan.
The proposed (invalid) plan contained the following problems:
Package directory is required by several packages, but they require
inconsistent versions:
package zip-archive-0.3.0.5 requires directory-1.2.7.1
package yaml-0.8.21.1 requires directory-1.2.7.1
package x509-system-1.6.4 requires directory-1.2.7.1
package x509-store-1.6.2 requires directory-1.2.7.1
package temporary-1.2.0.4 requires directory-1.2.7.1
package streaming-commons-0.1.17 requires directory-1.2.7.1
package pandoc-1.18 requires directory-1.2.7.1
package pandoc-1.18 requires directory-1.2.7.1
package filemanip-0.3.6.3 requires directory-1.2.7.1
package process-1.4.3.0 requires directory-1.3.0.0

Proposed plan:
Configured aeson-1.0.2.1 (.fake.aeson-1.0.2.1)
Configured base-unicode-symbols-0.2.2.4 (.fake.base-unicode-symbols-0.2.2.4)
Configured connection-0.2.6 (.fake.connection-0.2.6)
Configured data-accessor-0.2.2.7 (.fake.data-accessor-0.2.2.7)
Configured data-accessor-template-0.2.1.13
(.fake.data-accessor-template-0.2.1.13)
Configured data-accessor-transformers-0.2.1.7
(.fake.data-accessor-transformers-0.2.1.7)
Configured directory-1.2.7.1 (.fake.directory-1.2.7.1)
Configured doctemplates-0.1.0.2 (.fake.doctemplates-0.1.0.2)
Configured filemanip-0.3.6.3 (.fake.filemanip-0.3.6.3)
Configured http-client-0.5.5 (.fake.http-client-0.5.5)
Configured http-client-tls-0.3.3.1 (.fake.http-client-tls-0.3.3.1)
Configured pandoc-1.18 (.fake.pandoc-1.18)
Configured pandoc-crossref-0.2.4.1 (.fake.pandoc-crossref-0.2.4.1)
Configured pandoc-types-1.17.0.5 (.fake.pandoc-types-1.17.0.5)
Configured process-1.4.3.0 (.fake.process-1.4.3.0)
Configured roman-numerals-0.5.1.5 (.fake.roman-numerals-0.5.1.5)
Configured streaming-commons-0.1.17 (.fake.streaming-commons-0.1.17)
Configured temporary-1.2.0.4 (.fake.temporary-1.2.0.4)
Configured texmath-0.8.6.7 (.fake.texmath-0.8.6.7)
Configured tls-1.3.9 (.fake.tls-1.3.9)
Configured utility-ht-0.0.12 (.fake.utility-ht-0.0.12)
Configured x509-store-1.6.2 (.fake.x509-store-1.6.2)
Configured x509-system-1.6.4 (.fake.x509-system-1.6.4)
Configured x509-validation-1.6.5 (.fake.x509-validation-1.6.5)
Configured yaml-0.8.21.1 (.fake.yaml-0.8.21.1)
Configured zip-archive-0.3.0.5 (.fake.zip-archive-0.3.0.5)
PreExisting Cabal-1.24.2.0 (Cabal-1.24.2.0)
PreExisting HTTP-4000.3.4 (HTTP-4000.3.4-KFReaUDBhDl5IdhBG0OByN)
PreExisting JuicyPixels-3.2.8 (JuicyPixels-3.2.8-EkKwWbFUdJU59x0d9nQWwV)
PreExisting QuickCheck-2.9.2 (QuickCheck-2.9.2-LUnRjwrWhwjHswl9yQmDJj)
PreExisting SHA-1.6.4.2 (SHA-1.6.4.2-F4Ws1RGgbCOHLdCsxX2sFW)
PreExisting array-0.5.1.1 (array-0.5.1.1)
PreExisting asn1-encoding-0.9.4 (asn1-encoding-0.9.4-HAfF2Vsn4uEGxMXXSWxYAi)
PreExisting asn1-parse-0.9.4 (asn1-parse-0.9.4-1HpcjA0wxIVK817RMCJTRm)
PreExisting asn1-types-0.3.2 (asn1-types-0.3.2-KdhtjSv7K2iIRkHjjTrRf0)
PreExisting async-2.1.1 (async-2.1.1-4n6HEMPJR2eJK0JpvCfuPK)
PreExisting attoparsec-0.13.1.0 (attoparsec-0.13.1.0-3ZzSdwcr60OAwHW88oHBGG)
PreExisting base-4.9.1.0 (base-4.9.1.0)
PreExisting base-compat-0.9.1 (base-compat-0.9.1-B9geVZFtCvE8ERS7UcvkRz)
PreExisting base64-bytestring-1.0.0.1
(base64-bytestring-1.0.0.1-4O9TExPPz6eI82Yj7L4SIj)
PreExisting binary-0.8.3.0 (binary-0.8.3.0)
PreExisting blaze-builder-0.4.0.2
(blaze-builder-0.4.0.2-CHCuxDJaC37LXaq0Zrx3Kf)
PreExisting blaze-html-0.8.1.3 (blaze-html-0.8.1.3-9cPqTe36LFJL9M3HGA0Tk7)
PreExisting blaze-markup-0.7.1.1 (blaze-markup-0.7.1.1-6MJYIi9D1MzAiyCkkp6TH3)
PreExisting byteable-0.1.1 (byteable-0.1.1-2lU1pexQSLj1KbNO17UifQ)
PreExisting bytestring-0.10.8.1 (bytestring-0.10.8.1)
PreExisting case-insensitive-1.2.0.7
(case-insensitive-1.2.0.7-4Oy3FIXmC4U6Y7ZlsLfFWn)
PreExisting cereal-0.5.4.0 (cereal-0.5.4.0-5GV8T0cZtQC43fdhZURRFq)
PreExisting cmark-0.5.4 (cmark-0.5.4-KGIi3HDrjP3LE8SBQT9WCL)
PreExisting conduit-1.2.8 (conduit-1.2.8-84o32VhrHTE6YWW8RK69Ug)
PreExisting containers-0.5.7.1 (containers-0.5.7.1)
PreExisting cookie-0.4.2.1 (cookie-0.4.2.1-5S4SsfaEOCYIRFYzTCzIva)
PreExisting cryptonite-0.21 (cryptonite-0.21-COjx4E6447L3RVxkcCqXxV)
PreExisting data-default-0.7.1.1 (data-default-0.7.1.1-7EGYJX2YWqWJRbPFUHNoCr)
PreExisting data-default-class-0.1.2.0
(data-default-class-0.1.2.0-GsXqKN6o1X9jr0fF5qCVD)
PreExisting data-default-instances-containers-0.0.1
(data-default-instances-containers-0.0.1-bob6IQGdJq92c061H46zK)
PreExisting data-default-instances-dlist-0.0.1
(data-default-instances-dlist-0.0.1-FKnZBeovJMk4M89wQxDhjl)
PreExisting data-default-instances-old-locale-0.0.1
(data-default-instances-old-locale-0.0.1-9zaGDEmgOixKkmLylWdN5l)
PreExisting deepseq-1.4.2.0 (deepseq-1.4.2.0)
PreExisting digest-0.0.1.2 (digest-0.0.1.2-ExF2dwgnnwj5rxxaZYWSiQ)
PreExisting directory-1.3.0.0 (directory-1.3.0.0)
PreExisting dlist-0.8.0.2 (dlist-0.8.0.2-6Wnps4GD7EFnRucVzXIFD)
PreExisting enclosed-exceptions-1.0.2
(enclosed-exceptions-1.0.2-1HTux13gCzv9vrun2El2JQ)
PreExisting exceptions-0.8.3 (exceptions-0.8.3-74UMKX8an841ULC0nHtYN7)
PreExisting extensible-exceptions-0.1.1.4
(extensible-exceptions-0.1.1.4-IyAM3ARTqH7BVZ5oHMMtXH)
PreExisting filepath-1.4.1.1 (filepath-1.4.1.1)
PreExisting ghc-boot-th-8.0.2 (ghc-boot-th-8.0.2)
PreExisting ghc-prim-0.5.0.0 (ghc-prim-0.5.0.0)
PreExisting haddock-library-1.4.2
(haddock-library-1.4.2-6hIQ29hRXkf8sTGLGCaMtg)
PreExisting hashable-1.2.5.0 (hashable-1.2.5.0-D2qhjboTBST6rFOSUg03ZP)
PreExisting highlighting-kate-0.6.3
(highlighting-kate-0.6.3-FZf23hM7z6F2Qwr3LM6EFQ)
PreExisting hourglass-0.2.10 (hourglass-0.2.10-pnbvWmzfcY1rOFETQEmcY)
PreExisting hslua-0.4.1 (hslua-0.4.1-7XWxxyyNaXZ6nHO8UCHhcK)
PreExisting http-types-0.9.1 (http-types-0.9.1-JKOY2gV9v78Xf1a6uuvm5)
PreExisting integer-gmp-1.0.0.1 (integer-gmp-1.0.0.1)
PreExisting integer-logarithms-1 (integer-logarithms-1-96xRAmHs4Fb6n66XL8dC1K)
PreExisting lifted-base-0.2.3.8 (lifted-base-0.2.3.8-KJ9qw1ISJCkDr3HqU6X6Av)
PreExisting memory-0.14.1 (memory-0.14.1-2sAH1UOAoJsAJUuxVd95o9)
PreExisting mime-types-0.1.0.7 (mime-types-0.1.0.7-BIxmkcVKAC6KirUtpdG87Z)
PreExisting mmorph-1.0.9 (mmorph-1.0.9-BlUMuETLS27BjTIGbug5LI)
PreExisting monad-control-1.0.1.0
(monad-control-1.0.1.0-49Hei1wJW1ACN6RZpF8agb)
PreExisting mtl-2.2.1 (mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6)
PreExisting network-2.6.3.1 (network-2.6.3.1-ABFtZSq90Z9BfMXNiqgBoe)
PreExisting network-uri-2.6.1.0 (network-uri-2.6.1.0-L3Uif3PZTvwGEgoez4onJa)
PreExisting old-locale-1.0.0.7 (old-locale-1.0.0.7-KGBP1BSKxH5GCm0LnZP04j)
PreExisting old-time-1.1.0.3 (old-time-1.1.0.3-KWRsMSdY26c2L27Y9n9cyq)
PreExisting parsec-3.1.11 (parsec-3.1.11-KfZohCLhCERHHaWU51ma7a)
PreExisting pem-0.2.2 (pem-0.2.2-CkEwei5500yF2642aAaOAi)
PreExisting pretty-1.1.3.3 (pretty-1.1.3.3)
PreExisting primitive-0.6.1.0 (primitive-0.6.1.0-6AbSTw9JXz141LE5p6LGH)
PreExisting process-1.4.3.0 (process-1.4.3.0)
PreExisting random-1.1 (random-1.1-9tceXaeYIMZ4JrKq20Egog)
PreExisting regex-base-0.93.2 (regex-base-0.93.2-3URDEr5Kbe07o8jW0I8mn7)
PreExisting regex-pcre-builtin-0.94.4.8.8.35
(regex-pcre-builtin-0.94.4.8.8.35-Jd8og6J4na1HxszezwiC5H)
PreExisting resourcet-1.1.9 (resourcet-1.1.9-JemCEM5qIiV9yBbNtQ5yAL)
PreExisting rts-1.0 (rts)
PreExisting scientific-0.3.4.10 (scientific-0.3.4.10-ICbf3tuDFCq7d8ztOzZX6R)
PreExisting semigroups-0.18.2 (semigroups-0.18.2-8LAVfZ0VxfI7bfD9sPWjsq)
PreExisting socks-0.5.5 (socks-0.5.5-I13ZuoRgHPX7Z2RyCXJRbk)
PreExisting stm-2.4.4.1 (stm-2.4.4.1-JQn4hNPyYjP5m9AcbI88Ve)
PreExisting syb-0.6 (syb-0.6-IcoSwlPi2Nx4zSqMmorFPS)
PreExisting tagged-0.8.5 (tagged-0.8.5-jDBtbBndklGIlXZjVMhpH)
PreExisting tagsoup-0.14 (tagsoup-0.14-KC4g0gvzaHkfONwf4wy0v)
PreExisting template-haskell-2.11.1.0 (template-haskell-2.11.1.0)
PreExisting text-1.2.2.1 (text-1.2.2.1-FeA6fTH3E2n883cNXIS2Li)
PreExisting tf-random-0.5 (tf-random-0.5-BGjMgO8m67W8CHiEl15kZ7)
PreExisting time-1.6.0.1 (time-1.6.0.1)
PreExisting time-locale-compat-0.1.1.3
(time-locale-compat-0.1.1.3-KZ1jqNx8uhlHjmuPPj6V1Y)
PreExisting transformers-0.5.2.0 (transformers-0.5.2.0)
PreExisting transformers-base-0.4.4
(transformers-base-0.4.4-DPTfYkTApgo2fdoO6WqXzc)
PreExisting transformers-compat-0.5.1.4
(transformers-compat-0.5.1.4-84sV5mkFftgD9qwogvuEDr)
PreExisting unix-2.7.2.1 (unix-2.7.2.1)
PreExisting unix-compat-0.4.3.1 (unix-compat-0.4.3.1-4UGk5Lzx1jh6odMZdBsQG0)
PreExisting unordered-containers-0.2.7.2
(unordered-containers-0.2.7.2-ICgWIYrGL9xLm3Sokc47MY)
PreExisting utf8-string-1.0.1.1 (utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5)
PreExisting vector-0.11.0.0 (vector-0.11.0.0-HhutbadagxHIONIkSRJEug)
PreExisting x509-1.6.5 (x509-1.6.5-DTsrTx8ZiZ5H5kcbHapRpy)
PreExisting xml-1.3.14 (xml-1.3.14-A87ph8qJG9NaSHycMiOEE)
PreExisting zlib-0.6.1.2 (zlib-0.6.1.2-BfeUVhBVvrx1Nvtzv6OD9c)

CallStack (from HasCallStack):
error, called at ./Distribution/Client/Dependency.hs:658:33 in
main:Distribution.Client.Dependency
Butterfly:~ tsamsonov$ 
```

**Comment by lierdakil** [comment]
It is possible that some dependencies have broken, but a more likely explanation is you have something *already* installed that is unfortunately depends on something that conflicts with pandoc-crossref.

You can try resolving this in one of the following ways:
1) Use stack. Clone this repo, then `stack install pandoc pandoc-crossref pandoc-citeproc` in the root. You can choose what ghc/pandoc version to build exactly by specifying `--stack-yaml stack-ghcver-pandocver.yaml` (see `stack*.yaml` files in root)
2) Use cabal sandboxes. (f.ex. http://coldwa.st/e/blog/2013-08-20-Cabal-sandbox.html for a quick-and-dirty introduction)
3) Try one of the precombiled binaries: https://github.com/lierdakil/pandoc-crossref/releases -- note that those are auto-built in CI environment, so are not guaranteed to work. But you will see if they don't immediately, so it doesn't hurt to try.

**Comment by tsamsonov** [comment]
@lierdakil Thank you for your suggestions. I've tried all of them during several days, but unfortunately none of them worked for me. I also tried installing on Windows 8 and Windows 10, including absolutely fresh installation of Windows 10 without any installations prior to haskell and pandoc. The result of `cabal install pandoc-crossref` is the same: **Could not construct a valid install plan**. Do you have any further thoughts on that?
<img width="946" alt="win 10 error" src="https://cloud.githubusercontent.com/assets/11613495/22647282/a2a39aa0-ec81-11e6-9b7e-9c2afa9c55f7.png">

**Comment by lierdakil** [comment]
Try `cabal install --max-backjumps -1 --reorder-goals pandoc-crossref`. Also, bear in mind you need at least ghc-7.10.
Also, what didn't work with precompiled binaries? Besides of having to install pandoc separately I mean.

**Comment by tsamsonov** [comment]
@lierdakil, using the `cabal install --max-backjumps -1 --reorder-goals pandoc-crossref` leads to the same error. I have ghc-8.0.2

If I try to use precompiled binary on macOS, I get the following:
```
Butterfly:Revised tsamsonov$ pandoc --filter pandoc-crossref -s HeterogeneousSimplification_IJGIS.tex -o HeterogeneousSimplification_IJGIS.docx
pandoc-crossref: Error in $: mempty
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:113:48 in pandoc-types-1.17.0.4-Exk146b33gSCuTXMt5VQK3:Text.Pandoc.JSON
pandoc: Error running filter pandoc-crossref
Filter returned error status 1
Butterfly:Revised tsamsonov$
```

**Comment by lierdakil** [comment]
Honestly, I don't get it. The error says that everything wants directory-1.2.7.1, but process wants directory-1.3.0.0. But if we [look on hackage](https://hackage.haskell.org/package/process-1.4.3.0), process should be fine with any directory version from 1.1 to 1.3 inclusive. This is confusing. I was able to reproduce on 8.0.2 though. Strangely enough, this doesn't happen on 8.0.1 (at least my CI tests do not have this problem).

So I was able to track this down to Pandoc 1.18 dependencies. Last release of pandoc-crossref should, in theory, work with Pandoc 1.19, so I might as well go and relax that particular boundary. Which I did just now. So you may try `cabal update` and `cabal install pandoc-crossref` again.

**Comment by lierdakil** [comment]
Or maybe not...

**Comment by lierdakil** [comment]
What the hell

**Comment by lierdakil** [comment]
Okay, everything should be fine now. Hackage was just being slow.

**Comment by tsamsonov** [comment]
@lierdakil Yep, the installation went successfully this time! However, when I try to use the filter, pandoc says that it does not know about it:

```
Butterfly:Revised tsamsonov$ pandoc --filter pandoc-crossref -s HeterogeneousSimplification_IJGIS.tex -o HeterogeneousSimplification_IJGIS.docx
pandoc: Filter pandoc-crossref not found
Butterfly:Revised tsamsonov$ 
```

I found that the installed executable is located at `/Users/tsamsonov/Library/Haskell/bin/`. However It seems that pandoc tries to look filters at `/usr/local/bin/`. If I copy pandoc-crossref to the latter folder, I get the following error:

```
Butterfly:Revised tsamsonov$ pandoc --filter pandoc-crossref -s HeterogeneousSimplification_IJGIS.tex -o HeterogeneousSimplification_IJGIS.docx
pandoc-crossref: Error in $: mempty
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:113:48 in pandoc-types-1.17.0.5-7E082rzFLm4JQj7ZZR9YEz:Text.Pandoc.JSON
pandoc: Error running filter pandoc-crossref
Filter returned error status 1
Butterfly:Revised tsamsonov$ 
```

What is a solution to the problem?

**Comment by lierdakil** [comment]
Just specifying full path to filter should be enough, no need to copy it anywhere.

That said, it seems your system pandoc installation is outdated. Since you've built pandoc-crossref from source, a recent enough version of Pandoc should've been installed alongside it in `/Users/tsamsonov/Library/Haskell/bin/` -- try using that one instead.

I should warn you, however, that it seems you're trying to convert TeX references to docx. This won't work. pandoc-crossref only understands Markdown input at the moment, no TeX reader included.

**Comment by tsamsonov** [comment]
@lierdakil Thanks for your support! Everything works as should be expected. It seems that I've been inattentive while reading pandoc-crossref documantation. You are right, I need an effective instrument to convert LaTeX articles to DOCX with all that cross-referenceing stuff. However, it seems that there are no such solutions at the moment. Probably we'll see yours in a foreseeable future.

**Comment by lierdakil** [comment]
Well, don't get your hopes up about that, I'm very short on time between my day job, my Ph.D., and other projects.

That said, a *very* minimalistic way of doing what you want would be to convert TeX to Markdown with `pandoc -R input.tex -t markdown` and then run a simple `sed` script that would replace TeX syntax with pandoc-crossref syntax. There is no 1:1 mapping, regrettably, but one could make it work reasonably well (provided you're familiar enough with sed and/or regular expressions).

A similar option using the same idea is to write a (relatively) simple Pandoc filter that would fulfill the role of the sed script, which may be easier or harder, depending on what you're familiar with.

Then again, all this would work well enough only for relatively simple TeX documents. Once you delve into the realm of arcane TeX (subfloats, algorithms, metaprogramming, exotic document classes, etc), there's no way back, not really. You might try `htlatex` or something similar to convert to html first, but from my personal experience, `htlatex` etc are *really* hard to make work right for a reasonably complicated TeX file.

If you're wondering, the primary inspiration for this project came from the fact that converting TeX to html/docx/whatever is *really* complicated. So I switched to Markdown for my writing. But it lacked cross-referencing capabilities, and so this project came about. So, my personal recommendation: switch to Markdown. If you have a backlog of documents, convert those to Pandoc Markdown with `pandoc -R -t markdown` and then `sed` remaining TeX macros into submission. If you need to collaborate on articles/whatever, convince your colleagues to use Markdown as well. Yes, a tall order, I know, but I managed to do that somehow (although it ultimately took several years, and there were relatively few people I really had to *convince* and not just *tell* to use Markdown)

**Comment by tsamsonov** [comment]
@lierdakil Thank you for your kind support and detailed answer. I think that switching to markdown is worth trying since it is much more versatile in terms of format exchange. However I am still limited  to using LaTeX when submitting articles to computer science journals. Possibly they will begin accepting manuscripts in markdown syntax in a foreseeable future.

**Comment by lierdakil** [comment]
Well, the point is converting Markdown to TeX is much easier than doing that the reverse (and pandoc-crossref uses LaTeX references with TeX output).

**Comment by dilawar** [comment]
It could be related to jgm/pandoc#3217
