### ISSUE TITLE
Autoref support

### ISSUE THREAD

**Issue by Alxandr** [lierdakil/pandoc-crossref#103]
I would like to be able to use `\autoref{seq:name}` instead of `\ref` which is used today. Would that be easy to add support for you think? Preferably enabling autoref should also disable prefixes alltogether (as autoref handles those automatically). It should probably simplify a good bit of the rendering as you wouldn't have to care about prefixes or anything similar to that, and just let autoref deal with it.

**Comment by lierdakil** [comment]
I don't have much time to discuss this at the moment, but did you try
cleveref output? In many cases it's just autoref on steroids. At the very
least it's not worse than autoref, unless you have very specific
requirements.

чт, 9 февр. 2017 г., 13:35 Aleksander Heintz <notifications@github.com>:

**Comment by Alxandr** [comment]
Ah, yes, sorry. I completely missed this :). `\cref` seems to do the job nicely :)

**Comment by rriemann** [comment]
@Alxandr, could you please just briefly describe how you have configured your project to get cleveref working? I just wanted to ask the same question.

**Comment by Alxandr** [comment]
These are my flags:

```
-M cref=true -f markdown -t latex --filter pandoc-mermaid --filter=pandoc-crossref --filter=pandoc-citeproc --bibliography references.bib --biblatex
```
