### ISSUE TITLE
EPUB Figure Link Missing

### ISSUE THREAD

**Issue by kva1966** [lierdakil/pandoc-crossref#106]
Hello,

Firstly, awesome tool, thank you.

I'm generating PDF/LaTeX output as well as EPUB. PDF works fine, proper crossref generated. EPUB however, has the correct numbering of figures, just no linking.

The following is my MD source sample:

```Markdown
![Maslow's Hierarchy of Needs](images/maslowhon.png "Maslow's Hierarchy of Needs"){ #fig:maslow }

The one management theory that has stuck with the author has been Maslow's 
Hierachy of Needs. See [@Fig:maslow].
```

And this the generated XHTML output:

```HTML
<div class="figure">
<img src="../Images/file0.png" title="Maslow's Hierarchy of Needs" alt="Figure 4.1: Maslow's Hierarchy of Needs" id="fig:maslow"/>
<p class="caption">Figure 4.1: Maslow's Hierarchy of Needs</p>
</div>
<p>The one management theory that has stuck with the author has been Maslow's Hierachy of Needs. See Fig.&#160;4.1.</p>
```

Any ideas what I might be doing wrong? 

Thanks again.

**Comment by lierdakil** [comment]
Not sure from your description, did you enable linkReferences option?

**Comment by kva1966** [comment]
You are correct, I did miss this. My apologies. 

Any reason it's not a default? Especially because the behaviour would be consistent by default in all the output formats?

**Comment by lierdakil** [comment]
Well, it wouldn't necessarily be consistent, f.ex. docx struggles with that atm (#105). But it's off by default mostly for two reasons:

1) It was implemented as additional functionality, not initially, so was disabled by default as to keep existing workflows consistent.
2) Personal preference. I don't usually *want* linked cross-references, due to most of my writing being intended for non-digital consumption (i.e. printed on paper). In this case, links can do more harm than good.

**Comment by kva1966** [comment]
Fair points. Thanks again for the quick responses. :-)

**Comment by lierdakil** [comment]
FWIW, you can enable this per-project via [settings file](https://github.com/lierdakil/pandoc-crossref#settings-file). Sadly, there's no support for a global settings file yet, but it's been in the back of my mind for a while, so I might implement it eventually.

**Comment by kva1966** [comment]
All good, have done this, and do have separate latex and epub metadata+commandline options anyway, don't need it to be global. :-)

My preference for having links enabled by default in epub and hypertext is because they generally are meant for online/ereader consumption only, so it seems to make sense. But I agree with your point on not wanting to disrupt existing workflows.
