### ISSUE TITLE
pandoc-crossref: Error in $: mempty 

### ISSUE THREAD

**Issue by hkarl** [lierdakil/pandoc-crossref#107]
Hi, 

banging my head, probably something stupid: 

* OSX 10.11.6
* fresh install of haskell 
* ghc: 8.0.2
* new cabal sandbox 
* cabal install pandoc-crossref, install pandoc-citeproc 
* trivial input file tmp.md (same behavior with, e.g., demo.md from here): 
```
# Title

hallo
```

* Command: 

```
(ept-md) ~/c.prog/django_propgen/templates> pandoc -F ../pandoc/.cabal-sandbox/bin/pandoc-crossref -i tmp.md
pandoc-crossref: Error in $: mempty
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:113:48 in pandoc-types-1.17.0.5-1nO0Pmm1T7o8ZbffPnaPI9:Text.Pandoc.JSON
pandoc: Error running filter ../pandoc/.cabal-sandbox/bin/pandoc-crossref
Filter returned error status 1
```

?? Any help much appreciated! 

Holger

**Comment by lierdakil** [comment]
Your system Pandoc version doesn't match with version used by pandoc-crossref. You can probably use pandoc that was built with pandoc-crossref (although I don't exactly remember if binaries are copied, but check `../pandoc/.cabal-sandbox/bin/pandoc`)

**Comment by lierdakil** [comment]
Alternatively, you could use prebuilt binary for Pandoc 1.17 (no warranty), or build pandoc-crossref with hard constraint on pandoc-1.17.0.5 (`--constraint="pandoc==1.17.0.5"`)

**Comment by lierdakil** [comment]
At least I'm guessing that your system Pandoc version is 1.17.0.5. I may be wrong.

**Comment by hkarl** [comment]
Hi, 

oh, so easy ... thanks. System pandoc was 1.17.1 , but still not compatible.... Using the one in the sandbox did the trick. 

Thanks a lot! 

Holger

**Comment by akdiem** [comment]
I have basically the same issue, but didn't quite get how I can fix it because I'm entirely new to using cabal. I removed pandoc and pandoc-crossref and then reinstalled pandoc-crossref, because I thought that would install the correct version of pandoc. But it's the same as before and I still get the error message

```
pandoc-crossref: Error in $: mempty
pandoc: Error running filter /home/alexandra/.cabal/bin/pandoc-crossref
Filter returned error status 1
Makefile:10: recipe for target 'rescience-template.tex' failed
make: *** [rescience-template.tex] Error 83
```

What exact steps do I need to do to ensure my versions of pandoc and pandoc-crossref are compatible? Current versions I have are pandoc 1.19.2.1 and pandoc-crossref 0.2.5.0

**Comment by lierdakil** [comment]
@akdiem, try using pandoc executable built by cabal. `/home/alexandra/.cabal/bin/pandoc` would be my guess. That said, you seem to have eschewed creating a sandbox. This is generally a bad idea.

**Comment by akdiem** [comment]
@lierdakil Could you elaborate on what you mean by

> That said, you seem to have eschewed creating a sandbox. This is generally a bad idea.

I don't understand what you mean

**Comment by lierdakil** [comment]
> I highly recommend you use a sandbox for installation, e.g.
>
> ```
> cabal update
> mkdir pandoc-crossref
> cd pandoc-crossref
> cabal sandbox init
> cabal install pandoc-crossref
>  ```
> This will get pandoc-crossref installed into .cabal-sandbox/bin. Pandoc will also be built, if it's not installed as a Haskell library system-wide. You might also want to install pandoc-citeproc in the same sandbox, if that's the case (`cabal install pandoc-citeproc`).
>
> (from https://github.com/lierdakil/pandoc-crossref#installation)

more info on sandboxes: http://coldwa.st/e/blog/2013-08-20-Cabal-sandbox.html (note the article is from 2013, when this feature was first introduced, so it's a little outdated)

**Comment by akdiem** [comment]
Thanks for the clarification! I'll try that
