### ISSUE TITLE
Parenthetical or bracketed references

### ISSUE THREAD

**Issue by davenquinn** [lierdakil/pandoc-crossref#108]
I apologize in advance for potentially being really dense. I can't seem to get figure references to print with brackets in Latex.

Given the following Pandoc,
```markdown
The Ca-in-olivine barometer yields a broad distribution
of model depths, largely coincident with
the spinel stability field [@fig:depth_constraints].
```
I get the following Latex output:
```latex
The Ca-in-olivine barometer yields a broad distribution
of model depths, largely coincident
with the spinel stability field fig. 25.
```

I can change the prefix to `Figure` by creating a `figPrefix` entry in `pandoc-crossref.yaml`. However, the brackets are not respected no matter what, either with or without a `pandoc-crossref.yaml` in the project. Maybe I am misunderstanding, but I thought the default behavior was supposed to mirror the styling for citations (which are printed with brackets). Is there a configuration setting I am missing?

**Comment by lierdakil** [comment]
Default behavior is supposed to mirror `\cref{ref1,...,refN}` from LaTeX actually. Which is an option for output. I don't understand how you managed to get `fig. 25` in LaTeX output though, since pandoc-crossref is supposed to use LaTeX primitives instead of hard numbers.

**Comment by lierdakil** [comment]
Anyway, with LaTeX output specifically, the answer is to use `cleveref` package and it's own customization commands, e.g.
```
pandoc test.md -Fpandoc-crossref -t latex -Mcref -Mheader-includes='\AtBeginDocument{\crefdefaultlabelformat{[#2#1#3]}}' -o test.pdf
```
will produce the following pdf:
![image](https://cloud.githubusercontent.com/assets/7275622/23886073/f1b03810-0888-11e7-8ebd-b3147b5ada56.png)

Notice you have to wrap customization commands into `\AtBeginDocument`, since `cleveref` is actually included *after* user-specified header-includes. Refer to [cleveref documentation](https://www.ctan.org/pkg/cleveref) for more details.

In other output formats, the answer is using [reference templates](https://github.com/lierdakil/pandoc-crossref#reference-templates)

All this said, it's a mystery to me why would you even want references to look the same as citations.

**Comment by lierdakil** [comment]
P.S. If you really don't want to use cleveref for some reason, you could redefine `\ref{...}` to be `[\ref{...}]`:

```markdown
---
header-includes:
  - |
    \AtBeginDocument{%
    \let\oldref\ref
    \renewcommand{\ref}[1]{{[}\oldref{#1}{]}}
    }
---
The Ca-in-olivine barometer yields a broad distribution
of model depths, largely coincident with
the spinel stability field [@fig:depth-constraints].

![Depth constraints](img.jpg){#fig:depth-constraints}
```
This is most definitely not the cleanest option, but it'll work at least for singular references.

Oh, and if you want whole reference in brackets, i.e. `[fig. 25]`, just escape those brackets, i.e. `\[@fig:somefigure\]` will work just fine.

**Comment by davenquinn** [comment]
I would like
```
The Ca-in-olivine barometer yields a broad distribution
of model depths, largely coincident
with the spinel stability field [Figure 25].
```
and am surprised that there seems to be no option in either this package or cleverref to support that easily. It seems like there could be some sort of tracking of whether the initial [@fig:...] was enclosed in brackets, so replicating this enclosure in the document could be conditionally enabled in an output template.

Cleverref alone seems to indirectly support this by not messing with outer brackets (I may be wrong), but pandoc-crossref drops the brackets before passing to cleverref, so there is no ability to control this behavior short of cumbersome escaping.

**Comment by lierdakil** [comment]
As I said, escape the brackets, like this: `\[@ref\]`.

`[@ref]` is a syntax for reference group. F.ex. `[@ref1; @ref2]` would render to `figs. 1,2` not `[fig. 1; fig. 2]`.

**Comment by davenquinn** [comment]
OK, I can do this, but given how much customization is available, and the fact that you suggest parallelism with the pandoc citation framework, the fact that similar behavior is impossible seems unfortunate.

Given that, for citations, the concepts of parenthetical and inline citations map 1:1 with the general (outside of Pandoc) usage, this kind of transformation seems at odds with the simplicity of the syntax in general.

**Comment by lierdakil** [comment]
Also, cleveref supports full-blown templating via `\crefformat{<type>}{<format>}`. F.ex. `\crefformat{figure}{{[}Figure~#2#1#3{]}}`.

As for the rest, how author-in-text citations are rendered depends entirely on csl you're using, not on syntax. Besides, there is no way to group citations, and by extension references, without brackets, and `[@ref1; @ref2; @ref3]` case for `figs. 1-3` is very common, unlike bracketing references.

**Comment by lierdakil** [comment]
More or less complete templating is supported with most output formats. But not LaTeX, mostly because it's hard to get right automatically, but relatively easy to hack-in almost anything by hand.

**Comment by davenquinn** [comment]
Yes, it's not too hard to hack this behavior: the code

```sh
cat text.md \
| sed -r "s/\[((@(fig|eq|sec|tab):\w+;? ?)*)\]/\\\[\1\\\]/g" \
| pandoc --filter pandoc-crossref [...]
```
gives me the behavior that I want by wrapping all of the citation groups in an escaped pair of brackets. I could change the brackets to, e.g. parentheses if desired. I would like to propose that a "delimiter" option be supplied in the config that can wrap bracketed groups if desired. This will increase parallelism with `pandoc-citeproc` I think. However, this works fine for the time being.

**Comment by lierdakil** [comment]
As I already tried to point out, there is close to zero meaning in drawing parallels to pandoc-citeproc, since *it relies on an external stylesheet for rendering*.

This is a wontfix, since it's easy enough to do using what's already there. 

- LaTeX with cleveref: use a custom LaTeX template and cleveref options
- Other formats: use [reference templates](https://github.com/lierdakil/pandoc-crossref#reference-templates)
