### ISSUE TITLE
Include label name in hyperlink

### ISSUE THREAD

**Issue by mtikekar** [lierdakil/pandoc-crossref#109]
If I have a reference, say "Fig. 1", only "1" is hyperlinked to the figure. I would like the full name "Fig. 1" to be the hyperlink. That is hyperref's default setting with autoref and can be emulated in cleveref by doing `\usepackage[nameinlink]{cleveref}`. I have limited Haskell knowledge, so I was able to modify the code for latex output, but couldn't figure out how to fix the general output.

**Comment by lierdakil** [comment]
This can become a problem for cases like this: `figs. 1-3`. So, what should be hyperlinked here?

**Comment by lierdakil** [comment]
Well anyway, see if b4c50af4f2a75fe644a87b1fd855f6ee35d3f493 works along the lines of what you'd expect. Long story short, `nameInLink` option makes reference prefix part of hyperlink *iff* there's only one link in the group. Feel free to suggest alterations to the behavior.

**Comment by lierdakil** [comment]
P.S. the *actual* changeset is 6e0fb77d329516001045eaab3126017d53ce649c, if you're interested.

**Comment by mtikekar** [comment]
Thanks, this works great! I don't know how to solve the problem case you mentioned. Cleveref takes issue with hyperref's default for the same reason.
