### ISSUE TITLE
non-breaking space between prefix and number

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#11]
Currently, a normal space is inserted between figPrefix, tblPrefix, eqnPrefix and its corresponding reference number. At line ends, this sometimes breaks the number to the next line wich should be avoided. Therefore, a non-breaking space should be inserted instead.

**Comment by lierdakil** [comment]
It's a little harder than it could be. Pandoc's document model lacks non-breakable spaces, so only option I have is raw unicode code-point. But frankly, I'm not sure if it's supported by all outputs.

**Comment by tolot27** [comment]
What about the Latex command `\ ` which is supported by pandoc and works at least for Latex and Docx? As long as there is no official spec, this would be the minimal consensus, IMHO.

**Comment by lierdakil** [comment]
It's converted to unicode code-point internally. Well, I might as well implement this, and roll-back/patch up if problems arise.
