### ISSUE TITLE
Equation label prefix

### ISSUE THREAD

**Issue by jpcirrus** [lierdakil/pandoc-crossref#111]
The equation label prefix of `eq` is the only one which isn't two letters long consequently I keep writing `eqn` by mistake only to have pandoc-citeproc catch it. It would be appreciated to also allow `eqn` in order to match the other labels' prefixes and every other singular reference to equations in the filter e.g. `eqnPrefix`.

**Comment by lierdakil** [comment]
I'll close this in favor of #84.
