### ISSUE TITLE
cabal: Could not resolve dependencies

### ISSUE THREAD

**Issue by smidm** [lierdakil/pandoc-crossref#112]
Fails to install on Fedora 25:

```
$ cabal update
...

$ cabal install pandoc-crossref
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pandoc-crossref-0.2.5.0 (user goal)
trying: template-haskell-2.11.1.0 (dependency of pandoc-crossref-0.2.5.0)
next goal: data-accessor-template (dependency of pandoc-crossref-0.2.5.0)
rejecting: data-accessor-template-0.2.1.13, 0.2.1.12 (conflict:
template-haskell==2.11.1.0, data-accessor-template => template-haskell>=2.4 &&
<2.11)
rejecting: data-accessor-template-0.2.1.11, 0.2.1.10, 0.2.1.9, 0.2.1.8,
0.2.1.7, 0.2.1.6, 0.2.1.5, 0.2.1.4, 0.2.1.3, 0.2.1.2, 0.2.1.1, 0.2.1, 0.2,
0.1.4, 0.1.3, 0.1.2, 0.1.1 (conflict: pandoc-crossref =>
data-accessor-template>=0.2.1.12 && <0.3.0.0)
Backjump limit reached (change with --max-backjumps).

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3

$ cabal --version
cabal-install version 1.22.9.0
using version 1.22.5.0 of the Cabal library 
```

Tried both standard install and sandbox.

**Comment by lierdakil** [comment]
```
$ cabal sandbox init
Writing a default package environment file to
/tmp/testcabal/cabal.sandbox.config
Creating a new sandbox at /tmp/testcabal/.cabal-sandbox
$ cabal update
Downloading the latest package list from hackage.haskell.org
$ cabal install pandoc-crossref
Resolving dependencies...
Notice: installing into a sandbox located at /tmp/testcabal/.cabal-sandbox
Downloading base-compat-0.9.3...
Configuring base64-bytestring-1.0.0.1...
Configuring base-unicode-symbols-0.2.2.4...
Configuring SHA-1.6.4.2...
Configuring byteable-0.1.1...
Configuring data-accessor-0.2.2.7...
Configuring data-default-class-0.1.2.0...
Configuring dlist-0.8.0.2...
Configuring digest-0.0.1.2...
Downloading foundation-0.0.7...
Building base-unicode-symbols-0.2.2.4...
Building SHA-1.6.4.2...
Building byteable-0.1.1...
Building base64-bytestring-1.0.0.1...
Building data-default-class-0.1.2.0...
Building data-accessor-0.2.2.7...
Building digest-0.0.1.2...
Building dlist-0.8.0.2...
Downloading haddock-library-1.4.3...
Downloading safe-0.3.14...
^C
$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ 
```

So I can't reproduce. Possibly it's a bug in cabal 1.22, or a problem with your global package database.

You might try with `--reorder-goals --max-backjumps=-1`, that might help.

**Comment by smidm** [comment]
The package database should be ok. I never used `cabal` before.

    $ cabal install pandoc-crossref --reorder-goals --max-backjumps=-1

    Resolving dependencies...
    Configuring array-0.5.1.1...
    Configuring base-unicode-symbols-0.2.2.4...
    Configuring data-default-class-0.1.2.0...
    Configuring extensible-exceptions-0.1.1.4...
    Configuring fail-4.9.0.0...
    Configuring filepath-1.4.1.2...
    Configuring haskell-lexer-1.0.1...
    Configuring foundation-0.0.7...
    Configuring hxt-charproperties-9.2.0.1...
    Configuring old-locale-1.0.0.7...
    Configuring safe-0.3.14...
    Configuring syb-0.6...
    Configuring transformers-0.5.4.0...
    Configuring utility-ht-0.0.13...
    Failed to install array-0.5.1.1
    Build log ( /home/matej/.cabal/logs/array-0.5.1.1.log ):
    Failed to install base-unicode-symbols-0.2.2.4
    Build log ( /home/matej/.cabal/logs/base-unicode-symbols-0.2.2.4.log ):
    Failed to install data-default-class-0.1.2.0
    Build log ( /home/matej/.cabal/logs/data-default-class-0.1.2.0.log ):
    Failed to install extensible-exceptions-0.1.1.4
    Build log ( /home/matej/.cabal/logs/extensible-exceptions-0.1.1.4.log ):
    Failed to install fail-4.9.0.0
    Build log ( /home/matej/.cabal/logs/fail-4.9.0.0.log ):
    Failed to install filepath-1.4.1.2
    Build log ( /home/matej/.cabal/logs/filepath-1.4.1.2.log ):
    Failed to install haskell-lexer-1.0.1
    Build log ( /home/matej/.cabal/logs/haskell-lexer-1.0.1.log ):
    Failed to install foundation-0.0.7
    Build log ( /home/matej/.cabal/logs/foundation-0.0.7.log ):
    Failed to install hxt-charproperties-9.2.0.1
    Build log ( /home/matej/.cabal/logs/hxt-charproperties-9.2.0.1.log ):
    Failed to install old-locale-1.0.0.7
    Build log ( /home/matej/.cabal/logs/old-locale-1.0.0.7.log ):
    Failed to install safe-0.3.14
    Build log ( /home/matej/.cabal/logs/safe-0.3.14.log ):
    Failed to install syb-0.6
    Build log ( /home/matej/.cabal/logs/syb-0.6.log ):
    Failed to install transformers-0.5.4.0
    Build log ( /home/matej/.cabal/logs/transformers-0.5.4.0.log ):
    Failed to install utility-ht-0.0.13
    Build log ( /home/matej/.cabal/logs/utility-ht-0.0.13.log ):
    cabal: Error: some packages failed to install:
    HTTP-4000.3.6 depends on transformers-0.5.4.0 which failed to install.
    JuicyPixels-3.2.8.1 depends on transformers-0.5.4.0 which failed to install.
    QuickCheck-2.9.2 depends on transformers-0.5.4.0 which failed to install.
    SHA-1.6.4.2 depends on filepath-1.4.1.2 which failed to install.
    aeson-1.2.0.0 depends on transformers-0.5.4.0 which failed to install.
    array-0.5.1.1 failed during the configure step. The exception was:
    user error (The package 'array' requires Cabal library version -any && >=1.10
    but no suitable version is installed.)
    asn1-encoding-0.9.5 depends on foundation-0.0.7 which failed to install.
    asn1-parse-0.9.4 depends on foundation-0.0.7 which failed to install.
    asn1-types-0.3.2 depends on foundation-0.0.7 which failed to install.
    async-2.1.1.1 depends on array-0.5.1.1 which failed to install.
    attoparsec-0.13.1.0 depends on transformers-0.5.4.0 which failed to install.
    base-compat-0.9.3 depends on array-0.5.1.1 which failed to install.
    base-unicode-symbols-0.2.2.4 failed during the configure step. The exception
    was:
    user error (The package 'base-unicode-symbols' requires Cabal library version
    -any && >=1.6 but no suitable version is installed.)
    base64-bytestring-1.0.0.1 depends on array-0.5.1.1 which failed to install.
    binary-0.8.5.1 depends on array-0.5.1.1 which failed to install.
    blaze-builder-0.4.0.2 depends on array-0.5.1.1 which failed to install.
    blaze-html-0.9.0.1 depends on array-0.5.1.1 which failed to install.
    blaze-markup-0.8.0.0 depends on array-0.5.1.1 which failed to install.
    byteable-0.1.1 depends on array-0.5.1.1 which failed to install.
    bytestring-0.10.8.1 depends on array-0.5.1.1 which failed to install.
    case-insensitive-1.2.0.9 depends on transformers-0.5.4.0 which failed to
    install.
    cereal-0.5.4.0 depends on fail-4.9.0.0 which failed to install.
    cmark-0.5.5.1 depends on array-0.5.1.1 which failed to install.
    conduit-1.2.10 depends on transformers-0.5.4.0 which failed to install.
    connection-0.2.8 depends on transformers-0.5.4.0 which failed to install.
    containers-0.5.10.2 depends on array-0.5.1.1 which failed to install.
    cookie-0.4.2.1 depends on old-locale-1.0.0.7 which failed to install.
    cryptonite-0.22 depends on foundation-0.0.7 which failed to install.
    data-accessor-0.2.2.7 depends on transformers-0.5.4.0 which failed to install.
    data-accessor-template-0.2.1.13 depends on utility-ht-0.0.13 which failed to
    install.
    data-accessor-transformers-0.2.1.7 depends on transformers-0.5.4.0 which
    failed to install.
    data-default-0.7.1.1 depends on old-locale-1.0.0.7 which failed to install.
    data-default-class-0.1.2.0 failed during the configure step. The exception
    was:
    user error (The package 'data-default-class' requires Cabal library version
    -any && >=1.6 but no suitable version is installed.)
    data-default-instances-containers-0.0.1 depends on data-default-class-0.1.2.0
    which failed to install.
    data-default-instances-dlist-0.0.1 depends on data-default-class-0.1.2.0 which
    failed to install.
    data-default-instances-old-locale-0.0.1 depends on old-locale-1.0.0.7 which
    failed to install.
    deepseq-1.4.2.0 depends on array-0.5.1.1 which failed to install.
    digest-0.0.1.2 depends on array-0.5.1.1 which failed to install.
    directory-1.3.1.1 depends on filepath-1.4.1.2 which failed to install.
    dlist-0.8.0.2 depends on array-0.5.1.1 which failed to install.
    doctemplates-0.1.0.2 depends on transformers-0.5.4.0 which failed to install.
    exceptions-0.8.3 depends on transformers-0.5.4.0 which failed to install.
    extensible-exceptions-0.1.1.4 failed during the configure step. The exception
    was:
    user error (The package 'extensible-exceptions' requires Cabal library version
    -any && >=1.2.3 but no suitable version is installed.)
    fail-4.9.0.0 failed during the configure step. The exception was:
    user error (The package 'fail' requires Cabal library version -any && >=1.10
    but no suitable version is installed.)
    filemanip-0.3.6.3 depends on transformers-0.5.4.0 which failed to install.
    filepath-1.4.1.2 failed during the configure step. The exception was:
    user error (The package 'filepath' requires Cabal library version -any &&
    >=1.18 but no suitable version is installed.)
    foundation-0.0.7 failed during the configure step. The exception was:
    user error (The package 'foundation' requires Cabal library version -any &&
    >=1.10 but no suitable version is installed.)
    haddock-library-1.4.3 depends on transformers-0.5.4.0 which failed to install.
    hashable-1.2.6.0 depends on array-0.5.1.1 which failed to install.
    haskell-lexer-1.0.1 failed during the configure step. The exception was:
    user error (The package 'haskell-lexer' requires Cabal library version -any &&
    >=0 but no suitable version is installed.)
    hourglass-0.2.10 depends on array-0.5.1.1 which failed to install.
    hslua-0.4.1 depends on array-0.5.1.1 which failed to install.
    http-client-0.5.6.1 depends on transformers-0.5.4.0 which failed to install.
    http-client-tls-0.3.4.1 depends on transformers-0.5.4.0 which failed to
    install.
    http-types-0.9.1 depends on transformers-0.5.4.0 which failed to install.
    hxt-9.3.1.16 depends on transformers-0.5.4.0 which failed to install.
    hxt-charproperties-9.2.0.1 failed during the configure step. The exception
    was:
    user error (The package 'hxt-charproperties' requires Cabal library version
    -any && >=1.6 but no suitable version is installed.)
    hxt-regex-xmlschema-9.2.0.3 depends on transformers-0.5.4.0 which failed to
    install.
    hxt-unicode-9.0.2.4 depends on hxt-charproperties-9.2.0.1 which failed to
    install.
    integer-logarithms-1.0.1 depends on array-0.5.1.1 which failed to install.
    lifted-base-0.2.3.10 depends on transformers-0.5.4.0 which failed to install.
    memory-0.14.3 depends on foundation-0.0.7 which failed to install.
    mime-types-0.1.0.7 depends on array-0.5.1.1 which failed to install.
    mmorph-1.0.9 depends on transformers-0.5.4.0 which failed to install.
    monad-control-1.0.1.0 depends on transformers-0.5.4.0 which failed to install.
    mtl-2.2.1 depends on transformers-0.5.4.0 which failed to install.
    network-2.6.3.1 depends on array-0.5.1.1 which failed to install.
    network-uri-2.6.1.0 depends on transformers-0.5.4.0 which failed to install.
    old-locale-1.0.0.7 failed during the configure step. The exception was:
    user error (The package 'old-locale' requires Cabal library version -any &&
    >=1.10 but no suitable version is installed.)
    old-time-1.1.0.3 depends on old-locale-1.0.0.7 which failed to install.
    pandoc-1.19.2.1 depends on transformers-0.5.4.0 which failed to install.
    pandoc-crossref-0.2.5.0 depends on utility-ht-0.0.13 which failed to install.
    pandoc-types-1.17.0.5 depends on transformers-0.5.4.0 which failed to install.
    parsec-3.1.11 depends on transformers-0.5.4.0 which failed to install.
    pem-0.2.2 depends on transformers-0.5.4.0 which failed to install.
    pretty-1.1.3.5 depends on array-0.5.1.1 which failed to install.
    pretty-show-1.6.12 depends on haskell-lexer-1.0.1 which failed to install.
    primitive-0.6.2.0 depends on transformers-0.5.4.0 which failed to install.
    process-1.4.3.0 depends on filepath-1.4.1.2 which failed to install.
    random-1.1 depends on array-0.5.1.1 which failed to install.
    regex-base-0.93.2 depends on transformers-0.5.4.0 which failed to install.
    regex-pcre-builtin-0.94.4.8.8.35 depends on transformers-0.5.4.0 which failed
    to install.
    resourcet-1.1.9 depends on transformers-0.5.4.0 which failed to install.
    roman-numerals-0.5.1.5 depends on base-unicode-symbols-0.2.2.4 which failed to
    install.
    safe-0.3.14 failed during the configure step. The exception was:
    user error (The package 'safe' requires Cabal library version -any && >=1.18
    but no suitable version is installed.)
    scientific-0.3.4.12 depends on transformers-0.5.4.0 which failed to install.
    semigroups-0.18.3 depends on transformers-0.5.4.0 which failed to install.
    skylighting-0.1.1.5 depends on transformers-0.5.4.0 which failed to install.
    socks-0.5.5 depends on fail-4.9.0.0 which failed to install.
    stm-2.4.4.1 depends on array-0.5.1.1 which failed to install.
    streaming-commons-0.1.17 depends on transformers-0.5.4.0 which failed to
    install.
    syb-0.6 failed during the configure step. The exception was:
    user error (The package 'syb' requires Cabal library version -any && >=1.8 but
    no suitable version is installed.)
    tagged-0.8.5 depends on transformers-0.5.4.0 which failed to install.
    tagsoup-0.14.1 depends on array-0.5.1.1 which failed to install.
    template-haskell-2.10.0.0 depends on array-0.5.1.1 which failed to install.
    temporary-1.2.0.4 depends on transformers-0.5.4.0 which failed to install.
    texmath-0.9.4 depends on transformers-0.5.4.0 which failed to install.
    text-1.2.2.1 depends on array-0.5.1.1 which failed to install.
    tf-random-0.5 depends on transformers-0.5.4.0 which failed to install.
    time-1.6.0.1 depends on array-0.5.1.1 which failed to install.
    time-locale-compat-0.1.1.3 depends on array-0.5.1.1 which failed to install.
    tls-1.3.10 depends on transformers-0.5.4.0 which failed to install.
    transformers-0.5.4.0 failed during the configure step. The exception was:
    user error (The package 'transformers' requires Cabal library version -any &&
    >=1.6 but no suitable version is installed.)
    transformers-base-0.4.4 depends on transformers-0.5.4.0 which failed to
    install.
    transformers-compat-0.5.1.4 depends on transformers-0.5.4.0 which failed to
    install.
    unix-2.7.2.1 depends on array-0.5.1.1 which failed to install.
    unix-compat-0.4.3.1 depends on array-0.5.1.1 which failed to install.
    unordered-containers-0.2.8.0 depends on array-0.5.1.1 which failed to install.
    utf8-string-1.0.1.1 depends on array-0.5.1.1 which failed to install.
    utility-ht-0.0.13 failed during the configure step. The exception was:
    user error (The package 'utility-ht' requires Cabal library version -any &&
    >=1.10 but no suitable version is installed.)
    uuid-types-1.0.3 depends on array-0.5.1.1 which failed to install.
    vector-0.12.0.1 depends on transformers-0.5.4.0 which failed to install.
    x509-1.6.5 depends on transformers-0.5.4.0 which failed to install.
    x509-store-1.6.2 depends on transformers-0.5.4.0 which failed to install.
    x509-system-1.6.4 depends on transformers-0.5.4.0 which failed to install.
    x509-validation-1.6.5 depends on transformers-0.5.4.0 which failed to install.
    xml-1.3.14 depends on array-0.5.1.1 which failed to install.
    yaml-0.8.22 depends on transformers-0.5.4.0 which failed to install.
    zip-archive-0.3.0.5 depends on transformers-0.5.4.0 which failed to install.
    zlib-0.6.1.2 depends on array-0.5.1.1 which failed to install.

**Comment by lierdakil** [comment]
Well, dependencies are resolved now, but configuration fails.

Seems like these are the complaints: `user error (The package 'syb' requires Cabal library version -any && >=1.8 but no suitable version is installed.)`.

I'm not sure how you installed GHC, but it really seems environment is kinda broken =\ Cabal-the-library is pretty inseparable from GHC, at least until GHC 8, so the fact that cabal-the-executable (also known as cabal-install) can't find it is *plenty* worrying.
I believe on Fedora to get GHC you should install `haskell-platform` package. I have no idea if you did or not, but if not, that might be it?

**Comment by smidm** [comment]
I solved the problem with:

`sudo dnf install haskell-platform ghc-Cabal-devel`

The haskell environment was not completely installed. Installing `cabal-install` only was not enough.
