### ISSUE TITLE
feature request: listing without code block

### ISSUE THREAD

**Issue by smidm** [lierdakil/pandoc-crossref#113]
When typesetting an algorithm with math included I had to resort to http://pandoc.org/MANUAL.html#line-blocks syntax:

```
| in: image sequences
| out: synchronization events
|
| foreach: camera
| 	  foreach: frame
| 		  $m_f$ := line median intensity (frame)
| 		  $m_f \in \mathbb{N}^n$, where $n$ is frame height
```

It would be handy to allow the wrapping div syntax of code block label to work with arbitrary content. First paragraph will be a caption and rest the listing / algorithm content.

**Comment by lierdakil** [comment]
I'll close this in favor of #84.
