### ISSUE TITLE
Feature request: height of subfigures

### ISSUE THREAD

**Issue by nim65s** [lierdakil/pandoc-crossref#117]
Hi,

On the [subfigure grid](https://github.com/lierdakil/pandoc-crossref#subfigure-grid), one can specify the width of the images, and the height is deducted from the image ratio.

It would be really great to be able to specify the height instead, so that we could align several images with different ratio.

Thanks :)

**Comment by lierdakil** [comment]
That would be hard, to say the least. Pandoc-crossref, being a Pandoc filter, has no idea what those images are and what ratios they have (unless you specify that manually). And most output formats need column widths, not row heights. So... yeah. I would say it's way out of scope for this project.

**Comment by nim65s** [comment]
Ok, thanks for your answer, I'll find another way for my document :)
