### ISSUE TITLE
Are there any way to avoid displaying the prefix?

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [lierdakil/pandoc-crossref#119]
When displaying equations, I want to display the equation number but to hide the equation prefix.

For example, for the below markdown

```markdown
In @eq:MyEq,...
```
I want the generated latex to be

```latex
In \ref{eq:MyEq}
```

Is it possible to do this by changing the `eqnPrefix` or `eqnPrefixTemplate`? Or do I have to use raw latex to write `in \ref{eq:MyEq}` in the markdown file?

**Comment by lierdakil** [comment]
https://github.com/lierdakil/pandoc-crossref#prefix-suppression
