### ISSUE TITLE
Warnings on undefined refereces or duplicated labels?

### ISSUE THREAD

**Issue by borir** [lierdakil/pandoc-crossref#120]
Is it possible to issue warnings if there are references to undefined labels or duplicated labels? For HTML outputs, it seems that pandoc-crossref issues errors on the duplicated labels but not on the undefined references. For PDF outputs, neither causes errors or warnings. If the current implementation has no such features, would you add these as options?

**Comment by lierdakil** [comment]
PDF output uses LaTeX for both rendering *and* cross-referencing, so... yeah, that's not really possible.

For other output formats, missing references are rendered as "**¿reference_label?**". You're probably right in that it should also complain on stderr.

**Comment by lierdakil** [comment]
One could, in principle, grep stderr output for "Undefined reference" and fail. If you'd prefer there to be an option to make the filter error out, please open a new issue so I can keep track of it, thanks.
