### ISSUE TITLE
html table support?

### ISSUE THREAD

**Issue by eborgnine** [lierdakil/pandoc-crossref#122]
I'd like to respectfully request support for html tables, though I know this was said to be challenging in issue 104.  Would be quite helpful to be able to do something like this

```
[@tbl:mytable] is a simple table

<table id='tbl:mytable'>
<caption>This is my table</caption>
<thead><tr>
<th COLSPAN='1'>Header 1</th><th COLSPAN='2'>Header 2</th>
</tr></thead>
<tbody><tr>
<td>A1</td><td>B1</td><td>C1</td>
</tr></tbody></table>
```

A hack is to create an empty markdown table before the html table

```
[@tbl:anothertable] is another table

<div>
|   |   | 
|---|---| 
<span style="display:inline-block; width: 20em"> <span>|        

: This is also my table {#tbl:anothertable}

<table><tr><td>html table here</td></tr></table>
</div>
```

which renders nicely most of the time

<p>tbl. 3 is another table</p>
<div>
<div id="tbl:anothertable">
<table>
<caption>Table 3: This is also my table</caption>
<tbody>
<tr class="odd">
<td><span style="display:inline-block; width: 20em"> <span></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<table>
<tr>
<td>
html table here
</td>
</tr>
</table>
</div>

but is clumsy

**Comment by lierdakil** [comment]
Sorry, not really possible. Pandoc parses raw HTML as a horrifying mess of `RawBlock`s and `Plain`s, so it isn't practical to try and extract table caption from that. Doing the reverse, i.e. inserting a `caption` tag into that mess, sounds like an even worse idea.
