### ISSUE TITLE
vertical alignment of equation numbers with tableEqns=true

### ISSUE THREAD

**Issue by kugelblitz** [lierdakil/pandoc-crossref#125]
Hello,

To my opinion, tableEqns are better than the default \qquad indentation because it makes the equation numbers stick to the right margin, which is often the expected behavior.

However, that option works nice only with simple equations that are vertically short enough to fit in one line. With larger equations, it turns out that the reference number is vertically aligned to the top of the equation, while the convention is that it should be vertically aligned to the center.

Word (since 2010, anyway) has an option in the UI for individual table cell alignment, with nine values, from "left-top" to "right-bottom". So this option must be present in the docx format. I believe that the present behavior is "right-top", or "default", while it should rather be "right-center".

Thanks

**Comment by lierdakil** [comment]
We have to work within the constraints of Pandoc's AST, and it doesn't have vertical alignment in tables. Save for reimplementing better parts of Pandoc writers, this is pretty much impossible, as far as I can tell.

**Comment by kugelblitz** [comment]
OK, got it. I assumed that tables generated by pandoc-crossref are inherently different from ordinary Pandoc's tables, but apparently I was wrong.

I figure that my only choice is to fix the alignment in the generated docx using Word macros or some hardcore direct editing of the docx XML contents. If you have any pointers on that, I will be happy to know.

**Comment by lierdakil** [comment]
As for direct XML manipulation, if you could write a script that would insert 
```xml
<w:tcPr><w:vAlign w:val="center" /></w:tcPr>
```
inside relevant `<w:tc>`, which is part of `w:tbl > w:tr > w:tc` hierarchy, that would do it. For reference, `tbl` is table element, `tr` is row, and `tc` is cell. So math-related tables would be one-row tables with two cells.

I think it's possible to write an XSLT transformation that would do it, but I'm not very familiar with XSLT myself, so I can't give any pointers.

Writing up a Word macro that would iterate over all tables, find single-row two-cell ones and set vertical alignment in second cell sounds easier to me. VBA code would probably look something like this:

```vba
Dim atable As Table
For Each atable In ActiveDocument.Tables
 If atable.Rows.Count = 1 And atable.Columns.Count = 2 Then
  atable.Cell(1,2).VerticalAlignment = wdAlignVerticalCenter
 End If
Next
```

Bear in mind this is untested and likely contains syntax errors. Also bear in mind this works on any 1-row 2-column table. It should be possible to check if both cells contain math, but I can't concoct the code for that from the top of my head.

**Comment by kugelblitz** [comment]
Thank you for the pointers.
Below is what I have come up with.
It can really be multiple-row 2-column table, because consecutive numbered equations are merged in one table (I an not sure whether it is Pandoc's, pandoc-crossref's, or Word's behavior).
Also, I had to convert numbers-as-equations to numbers-as-text, because the alignment "to the right" does not work for equations. (I wonder what is the reason of them being equations in the first place).

```
Sub FixEquationNumbering()
  Dim atable As Table
  Dim rightcell As Cell
  For Each atable In ActiveDocument.Tables
    ' Find all 2-column tables. Our tables are not necessarily 1-row
    ' because the consecutive equations can be grouped in a single table.
    If atable.Columns.Count = 2 Then
      For Each aRow In atable.Rows
        Set leftcell = aRow.Cells(1)
        Set rightcell = aRow.Cells(2)
        If rightcell.Range.OMaths.Count = 1 And leftcell.Range.OMaths.Count = 1 Then
          ' Removing an OMath object magically replaces it with plain text,
          ' which is exactly what we need
          rightcell.Range.OMaths(1).Remove
          ' ... because the alignment does not work very well with equations
          rightcell.VerticalAlignment = wdAlignVerticalCenter
        End If
      Next
    End If
  Next
End Sub
```

**Comment by lierdakil** [comment]
> Below is what I have come up with.

Thank you for sharing.

> I an not sure whether it is Pandoc's, pandoc-crossref's, or Word's behavior

Latter. Pandoc definitely outputs one distinct table per equation.

> I wonder what is the reason of them being equations in the first place

This is mostly relevant in HTML output, since matching fonts between math and non-math parts can be challenging to say the least, esp. with MathJax or similar. Glad to see it didn't turn out to be a huge problem.
