### ISSUE TITLE
Refering to figures in tables

### ISSUE THREAD

**Issue by dilawar** [lierdakil/pandoc-crossref#128]
Here is my pandoc entry

```
 --------------------------------------------------    ----------------------------------
 ![](./figure_camkii8_voxel1.pdf){#fig:f81 width=8cm}  ![](./figure_camkii12_voxel1.pdf){#fig:f121 width=8cm}
 CaMKII=8, Voxels=1                                    CaMKII=12, Voxels=1
  ---------------------------------------------------   -----------------------------------
``` 

Using `@fig:f81` or `@fig:f121` does not work in pdf. 

```
LaTeX Warning: Reference `fig:f81' on page 1 undefined on input line ...
LaTeX Warning: Reference `fig:f121' on page 1 undefined on input line ...
```

I suspect, the `tex` document does not have `label` generated in `includegraphics` macro. 
Was it intentional not to support reference in `Tables`?

**Comment by lierdakil** [comment]
Problem is, those are not treated as figures by Pandoc. Figure in Pandoc is an image sitting by itself inside a paragraph (well, I'm oversimplifying a bit, see https://pandoc.org/MANUAL.html#extension-implicit_figures)

There are several options. For one, you could try using [subfigure grid](https://github.com/lierdakil/pandoc-crossref#subfigure-grid).

Another option would be using [grid tables](https://pandoc.org/MANUAL.html#extension-grid_tables), which can contain paragraphs in cells.
