### ISSUE TITLE
table-style captions for code with codeBlockCaptions and labels

### ISSUE THREAD

**Issue by nim65s** [lierdakil/pandoc-crossref#129]
Hello :)

As documented in README.md, this works:
```
a   b   c
--- --- ---
1   2   3
4   5   6

: Caption {#tbl:label}
```

But when I enable `codeBlockCaptions`, the "table-style" doesn't allow to put the label at the same place, as in:

    ```haskell
    main :: IO ()
    main = putStrLn "Hello World!"
    ```

    : Listing caption {#lst:code}

Wouldn't it be nice ? :)

**Comment by lierdakil** [comment]
Well, that proved to be easy, so there's an implementation in `master`. I will hold off on release though, there's still some things I'd like to do before that. You can build from `master` if you want.

**Comment by nim65s** [comment]
Wow, perfect, thanks a a lot ! :D
