### ISSUE TITLE
Change from Pandoc Error to Warning for Undefined References

### ISSUE THREAD

**Issue by stakaz** [lierdakil/pandoc-crossref#136]
it would be nice to have an option to only see a warning when a cross-reference is not defined in the document but let the document compile anyway.

The reason is any use of multiple files for one output file.

In my example I work with Atom editor and with multiple files like `chapter1.md` `chapter2.md` ... But I want/can preview just one file separately at a time with markdown-preview-plus (or to be general let just assume that I want to preview only one part of the whole document while writing so save compilation time). Now, if I reference from `chapter1.md` to ,e.g., a section via `@sec:section2_2` which is defined in `chapter2.md` I get an error

```
Pandoc Error:
Undefined cross-reference: sec:section2_2
```

But instead I would like to have a compiled file with something like `???` if the reference is not defined. Actually this is the case, when you only write `@sec:`.

Would this be possible or is it even already with some options of pandoc?

**Comment by lierdakil** [comment]
I'm pretty sure it's already a warning, unlike duplicate labels. I believe
it's just Mpp acting up.

ср, 18 окт. 2017 г., 9:48 Stanislav <notifications@github.com>:

**Comment by stakaz** [comment]
Thank you for the quick reply. I've created an issue for markdown-preview-plus. Hope this can be done soon. Here is the link: https://github.com/atom-community/markdown-preview-plus/issues/312.

**Comment by lierdakil** [comment]
The irony of the situation is somewhere down the line I wound up maintaining MPP as well. I'll try to take a look today.

**Comment by stakaz** [comment]
Well ;) I didn't noticed. Thank you for your help.
