### ISSUE TITLE
feature request: man page

### ISSUE THREAD

**Issue by Konfekt** [lierdakil/pandoc-crossref#137]
It would be convenient to have an offline documentation, such as a man page. A good start is the output of 
```sh
pandoc -f markdown -t man -o pandoc-crossref.1 README.md
```

**Comment by lierdakil** [comment]
Well, since there is no mechanism (that I'm aware of) for actually installing a manpage via Cabal or any other applicable universal method, save for a dedicated install script, I would suggest asking the package maintainer for your distribution to do that (if you have pandoc-crossref packaged, that is)

**Comment by Konfekt** [comment]
Well, here is the manpage obtained by adapting `Readme.MD` as found on

https://gist.github.com/Konfekt/d950f03c33eb31a7422e3f23d160ba6f

and invoking
```sh
pandoc -s -f markdown -t man -o pandoc-crossref.1 README.md
```
to obtain

https://gist.github.com/Konfekt/06f5ab7252ec1685a85d1b75de59d249

**Comment by Konfekt** [comment]
If this serves you somehow? My distribution does not have pandoc-crossref packaged. I rely on downloading the binary releases.

**Comment by lierdakil** [comment]
What I'm trying to say is, I can of course generate that on CI and include in the archive, I just don't understand what the point of that would be exactly.

It is, after all, rather trivial to get yourself offline copy for any version with simple 
```bash
wget https://raw.githubusercontent.com/lierdakil/pandoc-crossref/v0.2.6.0/README.md
```
(substitute any version you need to), or even convert on the fly with
```bash
pandoc -s -f markdown -t man https://raw.githubusercontent.com/lierdakil/pandoc-crossref/v0.2.6.0/README.md > pandoc-crossref.1
```

So... what is the point of including readme/docs with the binaries (in whatever format)?

**Comment by Konfekt** [comment]
It is not trivial for everyone. Also, the manpage does not necessarily have to coincide with the readme. For example, the Travis and image links do not belong there.

**Comment by lierdakil** [comment]
Well, not sure if that's what you wanted, but `v0.3.0.0-beta2` has manual embedded in text and html format. Running `pandoc-crossref --man` will print text, while `pandoc-crossref --man-html` will attempt to open html manual (local) in the default browser. I don't know whether latter will work consistently though.

(note: v0.3 is only compatible with Pandoc 2.0)

Manpage proper is available at <https://github.com/lierdakil/pandoc-crossref/blob/v0.3.0.0-beta2/docs/pandoc-crossref.1>

I didn't modify CI scripts to include it in the packed release though, but I'll try to not forget about this when it's time for a proper release.

**Comment by Konfekt** [comment]
Yeah, that's already the best ersatz for a man page possible, thanks!
