### ISSUE TITLE
Language dependent labels

### ISSUE THREAD

**Issue by Ondiz** [lierdakil/pandoc-crossref#138]
I love pandoc-citeproc and I'm wondering if it could be possible to use the internationalisation capability of LaTeX packages `babel` or `polyglossia` when writing the figure and table captions. Now even if I pass the language option to pandoc it doesn't have any effect because these prefixes are hardcoded in English:

```latex
\AtBeginDocument{%
\renewcommand*\figurename{Figure}
\renewcommand*\tablename{Table}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{List of Figures}
\renewcommand*\listtablename{List of Tables}
}
``` 

Maybe these two can be only activated when the user provides an alternative `figureTitle` and if she doesn't let the language package do its work? 

Thanks for the great job! 😄

**Comment by lierdakil** [comment]
Reason for why those are hard-coded is output formats besides LaTeX (after all, if you're targeting LaTeX exclusively, might just use LaTeX in the first place). Other output formats (docx, html) don't have `babel` or anything close. Hence, at least some consistency is enforced.

See also [readme section touching on i18n](https://github.com/lierdakil/pandoc-crossref#settings-file)

**Comment by Ondiz** [comment]
I understand. 

I'm targeting pdf and I'm used to LaTeX managing languages, that's why I was a bit surprised when it didn't happen from Markdown. I read along the readme but I missed the relation between the settings file and i18n... it took a while to understand what was happening.

Anyway, thanks for your time and your patience!
