### ISSUE TITLE
Overlapping subfigure captions

### ISSUE THREAD

**Issue by ahoereth** [lierdakil/pandoc-crossref#141]
For grid style subfigures with multiline captions, the captions overlap with one another. This can also not be solved by shrinking the images. I wasn't able to find a simple way to add some hspace between the images without using latex directly.

Pandoc 1.9.2.4 with latest pandoc-crossref.

![screen shot 2017-10-31 at 17 53 24](https://user-images.githubusercontent.com/3015996/32237138-7072cd5c-be64-11e7-92cb-607244f4accf.png)

## Code to reproduce:

```Shell
pandoc demo.md --filter pandoc-crossref -o demo.pdf
```

```Markdown
<div id="fig:afigure">
![Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.](dali.jpg){#fig:afigureA width=45%}
![Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.](dali.jpg){#fig:afigureB width=45%}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
```

**Comment by ahoereth** [comment]
Okay found a workaround, but I think this would actually be a sensible default:

```Markdown
---
header-includes:
  - \usepackage{caption}
  - \captionsetup[subfloat]{margin=10pt}
...
<div id="fig:afigure">
![Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.](dali.jpg){#fig:afigureA width=50%}
![Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.](dali.jpg){#fig:afigureB width=50%}

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</div>
```

![screen shot 2017-11-01 at 15 04 09](https://user-images.githubusercontent.com/3015996/32278440-0f38b60c-bf16-11e7-9cec-0a9cda33e668.png)

**Comment by lierdakil** [comment]
I've added `\captionsetup[subfloat]{margin=0.5em}` to generated latex header in 77da68b. I doubt I will make a new release anytime soon though.
