### ISSUE TITLE
pandoc-crossref incompatible with pandoc 2.0.1.1

### ISSUE THREAD

**Issue by salim-b** [lierdakil/pandoc-crossref#142]
I've just upgraded Pandoc from 1.9.2.1 to 2.0.1.1 and it doesn't work in combination with pandoc-crossref 0.2.6.0.

It always produces the following error:
```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.54 \textbackslash
```

The problem seems that instead of
```
\usepackage{subfig}
\AtBeginDocument{%
\renewcommand*\figurename{Figure}
\renewcommand*\tablename{Table}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{List of Figures}
\renewcommand*\listtablename{List of Tables}
}
\usepackage{float}
\floatstyle{ruled}
\makeatletter
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\makeatother
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
```

the following gets inserted into the (intermediate) Latex code:
```
\textbackslash{}usepackage\{subfig\}
\textbackslash{}AtBeginDocument\{\%
\textbackslash{}renewcommand*\textbackslash{}figurename\{Figure\}
\textbackslash{}renewcommand*\textbackslash{}tablename\{Table\}
\}
\textbackslash{}AtBeginDocument\{\%
\textbackslash{}renewcommand*\textbackslash{}listfigurename\{List of
Figures\}
\textbackslash{}renewcommand*\textbackslash{}listtablename\{List of
Tables\}
\}
\textbackslash{}usepackage\{float\}
\textbackslash{}floatstyle\{ruled\}
\textbackslash{}makeatletter
\textbackslash{}@ifundefined\{c@chapter\}\{\textbackslash{}newfloat\{codelisting\}\{h\}\{lop\}\}\{\textbackslash{}newfloat\{codelisting\}\{h\}\{lop\}{[}chapter{]}\}
\textbackslash{}makeatother
\textbackslash{}floatname\{codelisting\}\{Listing\}
\textbackslash{}newcommand*\textbackslash{}listoflistings\{\textbackslash{}listof\{codelisting\}\{List
of Listings\}\}
```

I'm pretty much a Latex novice and have no clue why this is happening but I guess the backslash character shouldn't be replaced by the Latex command to write a backslash (`\textbackslash`).

**Comment by lierdakil** [comment]
I've added a few commits into pandoc-2.0 branch that should help with that. Bear in mind, the branch is highly experimental (i.e. I just kept changing code until it started typechecking basically, and not much else) -- that's why it's not merged into `master`.

**Comment by salim-b** [comment]
> I've added a few commits into pandoc-2.0 branch that should help with that. Bear in mind, the branch is highly experimental

Glad to hear you've already tackling this! I've reverted to Pandoc 1.9 for now (and unfortunately don't have the capacities to test an experimental version right now...).

**Comment by lierdakil** [comment]
I've published https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.0.0-beta, if you're on Linux or Windows, you could grab a pre-built binary, and it'll (probably) work. If you're on Mac though, I'm having trouble with Mac CI lately, so probably no build yet.

**Comment by talazem** [comment]
Hi, I'm in the same predicament, but on a Mac. I previously pandoc-crossref, alongside pandoc, using brew. Any advice on what I can do in the meantime to get v0.3.0.0 installed? Many thanks for your work.

**Comment by salim-b** [comment]
> I've published https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.0.0-beta, if you're on Linux or Windows, you could grab a pre-built binary

Thanks! I'm on Linux and just gave it a try: Seems to work fine so far with Pandoc 2.0.1.1 👍 

(Although now I'm facing other issues most probably related to [some of the endless changes made from Pandoc 1.19 to 2.0](https://github.com/jgm/pandoc/releases/tag/2.0) 🙈 Guess I gotta stay with 1.19 for the time being.)

**Comment by lierdakil** [comment]
@talazem, if you have GHC toolchain, you can try building via cabal. You can feed it the source archive, e.g.

```bash
cabal install https://github.com/lierdakil/pandoc-crossref/archive/v0.3.0.0-beta.tar.gz
```

[Usual caveats about sandboxes apply](https://github.com/lierdakil/pandoc-crossref#installation)

Alternatively, [get stack](https://docs.haskellstack.org/en/stable/README/), get the [source tarball](https://github.com/lierdakil/pandoc-crossref/archive/v0.3.0.0-beta.tar.gz), unpack it, then in the source directory (the one containing `pandoc-crossref.cabal`) run:
```bash
stack setup
stack install pandoc pandoc-citeproc pandoc-crossref
```

**Comment by ilovezfs** [comment]
Hi, I'm one of the Homebrew maintainers. This is the first I'm hearing about the issues with pandoc-crossref and pandoc 2.0.x. The current version of pandoc in Homebrew is 2.0.1.1.

@lierdakil how would you feel about it if I were to ship pandoc-crossref v0.3.0.0-beta as the current "stable" version in Homebrew? I'm reluctant to introduce a new pandoc@1.9 formula just for pandoc-crossref given our analytics data, but obviously don't want to be shipping broken software.

```
Josephs-MacBook-Pro:~ joe$ brew formula-analytics pandoc
install events in the last 30 days for pandoc
============================================================================
1 | pandoc                                                | 26,552 |  99.92%
2 | pandoc --HEAD                                         |     22 |   0.08%
============================================================================
Total                                                     | 26,574 |    100%
============================================================================
Josephs-MacBook-Pro:~ joe$ brew formula-analytics pandoc-crossref
install events in the last 30 days for pandoc-crossref
============================================================================
1 | pandoc-crossref                                          | 134 | 100.00%
============================================================================
Total                                                        | 134 |    100%
============================================================================
Josephs-MacBook-Pro:~ joe$
```

**Comment by geniusupgrader** [comment]
metadata seems not working. From the demo.md in docs/demo:
`pandoc demo.md -f markdown --to=html --standalone --filter=pandoc-crossref --metadata=figureTitle:OtherName -o demo.html`
has no effect.

And in another document of mine, with the same command, there is even this error:
~~~
CallStack (from HasCallStack):
  error, called at lib/Text/Pandoc/CrossRef/Util/Meta.hs:29:33 in pandoc-crossref-0.2.6.0-3uxdGmCrwBf33v3qLZ5TUf:Text.Pandoc.CrossRef.Util.Meta
Error running filter pandoc-crossref:
Filter returned error status 1
~~~

Maybe I do something wrong?

**Comment by lierdakil** [comment]
@ilovezfs , pandoc-crossref-0.2.x is basically only compatible with pandoc-1.x -- there's nothing I can do about that, Pandoc 2.0 changed a whole lot of stuff internally. It still *runs* with pandoc-2.0, but results are... questionable at best.

As you can plainly see, 0.3 is a bit wonky, hence no release. To top it off, I will be away till December, starting this weekend, so it's unlikely I'll find time to get it to release-able state anytime soon.

@geniusupgrader, okay, so here's the problem: 0.2.x tried to parse strings passed on commandline as Markdown, which wasn't always consistent. Pandoc-2.0 changed some stuff, so it became even less consistent, and I removed that. Apparently, not the brightest idea I had, so fix is incoming. Still, full Markdown support from commandline is unlikely.

**Comment by geniusupgrader** [comment]
> Still, full Markdown support from commandline is unlikely.

@lierdakil: Does this mean, that pandoc-crossref must be rewritten completely to support Pandoc-2.0? Or that you do not have plans to incorporate more functionality in the near future?

**Comment by lierdakil** [comment]
Not completely, no. I'm kinda busy right now, so I can't dedicate too much time to this. I will do what I can today and maybe a bit tomorrow, and then it'll have to go on ice 'till December. Anyway, https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.0.0-beta2a should pick up text from command line at least.

**Comment by felixonmars** [comment]
I am getting the following error when trying to build pandoc-crossref 0.3.0.0-beta3 with pandoc 2.0.1:

```
[2 of 2] Compiling Main             ( src/pandoc-crossref.hs, dist/build/pandoc-crossref/pandoc-crossref-tmp/Main.dyn_o )

src/pandoc-crossref.hs:30:21: error:
    • Ambiguous type variable ‘a0’ arising from a use of ‘strArgument’
      prevents the constraint ‘(Data.String.IsString
                                  a0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘a0’ should be.
      These potential instances exist:
        instance Data.String.IsString Inlines
          -- Defined in ‘Text.Pandoc.Builder’
        instance Data.String.IsString Format
          -- Defined in ‘Text.Pandoc.Definition’
        instance a ~ Char => Data.String.IsString [a]
          -- Defined in ‘Data.String’
        ...plus 11 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the second argument of ‘($)’, namely
        ‘strArgument (metavar "FORMAT")’
      In a stmt of a 'do' block:
        fmt <- optional $ strArgument (metavar "FORMAT")
      In the expression:
        do vers <- flag
                     Nothing
                     (Just Version)
                     (long "version" <> short 'v' <> help "Print version")
           man' <- flag Nothing (Just Man) (long "man" <> help "Show manpage")
           hman <- flag
                     Nothing
                     (Just HtmlMan)
                     (long "man-html" <> help "Show html manpage")
           fmt <- optional $ strArgument (metavar "FORMAT")
           return go (vers <|> man' <|> hman) fmt
   |
30 |   fmt <- optional $ strArgument (metavar "FORMAT")
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by lierdakil** [comment]
@felixonmars, well, okay, package bounds on optparse-applicative are too relaxed, plus insufficient testing.  I've pushed fix to `master`.

**Comment by lierdakil** [comment]
For anyone interested, finally got Travis to give me an OSX build in https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.0.0-beta3a

**Comment by felixonmars** [comment]
@lierdakil Thanks, 0.3.0.0-beta3a works fine here :)

**Comment by prouast** [comment]
@lierdakil 0.3.0.0-beta3a works for me too, thanks!

**Comment by svenevs** [comment]
I'm on Mac with pandoc 2.0.2, just wanted to report that at least for my purposes `0.2.7.0` is functional for generating XeLaTeX code (I'm not using pandoc to generate the actual PDF, just generate the code, and specifically **not** standalone).  So maybe that will help identify some potential issues (maybe a template problem or something)?

**Comment by lierdakil** [comment]
v0.3.0.0 released on Hackage. Please file new issues if something goes wrong.
