### ISSUE TITLE
understanding the rules of linking

### ISSUE THREAD

**Issue by svenevs** [lierdakil/pandoc-crossref#143]
Hello!

`pandoc-crossref` is freaking sweet, thank you very much!  I would like to submit a PR with a brief explanation of the reference names allowed, and what they turn into, ~~as it seems to be explicit and unalterable~~ (I read 84, but not the original 83...sorry!).

1. Figures: label with `{#fig:your_label}` (always start with `#fig:`).  Links generated will always be `fig. X` where `X` is the number (e.g., 1, 2, ...).
2. Tables: `#tbl:` -> `tbl. X`
3. (Code) Listings: `#lst:` -> `lsts. X`
4. Where all links are concerned, a custom link name can be generated with `[Prefix @anchor:label]`.  For example, instead of writing `@fig:your_label` resulting in a link of `fig. X`, if you wrote `[Figure @fig:your_label]` the link `Figure X` will be generated instead.

Where actual linkage is concerned, is it true that latex is the only one that will actually generate hyperlinks?  Even the demo website for html does not have links (even though there are labelled divs), reStructuredText does not generate any links either.  They just do the replacement without any link.

I would add the would-be PR underneath the Installation section of the README with slightly less terse verbiage.  If this is not desired, or incorrect, please close.  ~~Though if it is incorrect, please kindly point me in a direction for how to let `#tbl:` -> `Table X`.  #84 seems related, but I think that is only for one side of the coin (`{#custom:`), not for custom output link names?~~  IT IS RELATED!  Updated to add number 4, I think having this on the README would be very helpful.

**Comment by lierdakil** [comment]
pandoc-crossref has a bunch of options for configuring how references etc get formatted in the output. I try hard to document everything, but since readme was becoming more than a bit bloated, it's been moved to separate page, http://lierdakil.github.io/pandoc-crossref/

In particular, http://lierdakil.github.io/pandoc-crossref/#reference-format describes document metadata variables responsible for reference formatting. Also notice `linkReferences` option.

**Comment by svenevs** [comment]
Indeed, it is much more involved than I thought.  Sorry!

> Where actual linkage is concerned, is it true that latex is the only one that will actually generate hyperlinks?

Is this statement true, or just operator error?

**Comment by lierdakil** [comment]
> actually generate hyperlinks

> Also notice linkReferences option.

It's disabled by default. Latex is handled differently (because it has hyperref, other output formats don't)

**Comment by svenevs** [comment]
Shame on me.  I was setting `link_references` in the meta options.  Thank you for being so gentle...
