### ISSUE TITLE
Show code/table caption UNDER the code block / table?

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#148]
Is it possible to have the caption for code block or table display underneath instead of above?

**Comment by GandalfSaxe** [comment]
It may have something to do with tableTemplate?

Speaking of which, in the YAML header of `demo.md` it's formatted like  `*$$tableTitle$$ $$i$$*$$titleDelim$$ $$t$$`, while on the [man page](https://github.com/lierdakil/pandoc-crossref/blob/master/docs/man.md#item-title-templates) it's formatted like `\\[tableTitle\\] \\[i\\]\\[titleDelim\\] \\[t\\]` - why is this?

**Comment by GandalfSaxe** [comment]
I have since realized that table captions are conventionally placed above the tables, so this is not really an issue. But just for the sake of it, I'd still like to know if it's possible in principle since the issue is here anyway now ¯\_(ツ)_/¯

**Comment by lierdakil** [comment]
> Speaking of which, in the YAML header of demo.md it's formatted like *$$tableTitle$$ $$i$$*$$titleDelim$$ $$t$$, while on the man page it's formatted like \\[tableTitle\\] \\[i\\]\\[titleDelim\\] \\[t\\] - why is this?

Oversight on my part, mostly. Template variables steal display math syntax, and at some point both `$$...$$` and `\[...\]` were more or less equivalent. Not the case with later versions of Pandoc. Thanks for noticing that.

As for caption placement, that's up to Pandoc. See https://github.com/jgm/pandoc/issues/2868. Pretty sure I played with the idea of making a writer flag that would determine caption placement, but it was abandoned for one reason or another.

**Comment by GandalfSaxe** [comment]
Yeah it's no biggie for me since it's conventional to put table captions above. You may close this issue if you wish.
