### ISSUE TITLE
Use of -i option in makefile

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#149]
Hi,

This is just a small detail, but you seem to use -i in all of pandoc commands in your makefiles, e.g.:

`pandoc --number-sections -t latex --filter pandoc-crossref -o output.pdf -i demo.md`

It seems like you think it means input, however no option/flag is actually possible for specifying the input file as far as I can see. The `-i` actually means [incremental](http://pandoc.org/MANUAL.html#incremental-lists), which makes lists show up incrementally in documents that is converted into slide shows by pandoc.

Just thought I'd point this out, and would suggest that you remove all superfluous `-i` from all the makefiles in the repo :)

**Comment by GandalfSaxe** [comment]
On another nitpick note, since you use `autoSectionLabels: True` in `demo.md`, instead of writing the first section header as:

`# Chapter 1. Figures {#sec:sec1}`

You could've written

`# Chapter 1. Figures {#sec1}`

right? And I guess that crossref is intelligent enough to not make the label `{#sec:sec:sec1}`?

**Comment by lierdakil** [comment]
Huh. I could've sworn that at least *some* version of Pandoc used `-i` for input, but I guess I'm confusing that with `-o` for output. Thanks for letting me know.

As for the second point, yes. But autoSectionLabels is primarily intended to be used with automatic Pandoc section labels (i.e. when label isn't specified explicitly) -- there's no way to differentiate between Pandoc-generated labels and user-defined ones, hence it works this way. As a rule of thumb, when specifying section label manually (and intending to use it with crossref), it's better to use prefix.
