### ISSUE TITLE
installation is cumbersome

### ISSUE THREAD

**Issue by arve0** [lierdakil/pandoc-crossref#15]
Hi and thanks for the package!
I've installed pandoc via [brew](http://brew.sh/) and to use this filter I have to get haskell (1.6Gb installed) plus 83 packages. In the meantime, I've managed to drink a cup of coffee and create this issue, and the compiling is still not done! 

Not sure there is an easy fix of this, I guess the dependencies are mainly due to pandoc? Anyhow, seems cumbersome just for some text parsing.

Here are the packages:
```
base64-bytestring-1.0.0.1 (new package)
blaze-builder-0.4.0.1 (new package)
blaze-markup-0.7.0.2 (new package)
blaze-html-0.8.0.2 (new package)
byteable-0.1.1 (new package)
cereal-0.4.1.1 (new package)
cryptohash-0.11.6 (new package)
data-default-class-0.0.1 (new package)
cookie-0.4.1.5 (new package)
data-default-instances-base-0.0.1 (new package)
data-default-instances-containers-0.0.1 (new package)
data-default-instances-old-locale-0.0.1 (new package)
deepseq-generics-0.1.1.2 (new package)
digest-0.0.1.2 (new package)
dlist-0.7.1.1 (new package)
data-default-instances-dlist-0.0.1 (new package)
data-default-0.5.3 (new package)
extensible-exceptions-0.1.1.4 (new package)
hourglass-0.2.9 (new package)
asn1-types-0.3.0 (new package)
http-types-0.8.6 (new package)
mime-types-0.1.0.6 (new package)
nats-1 (new package)
network-2.6.1.0 (new version)
scientific-0.3.3.8 (new package)
attoparsec-0.11.3.4 (latest: 0.13.0.0) (new version)
securemem-0.1.7 (new package)
crypto-cipher-types-0.0.9 (new package)
cipher-aes-0.2.10 (new package)
cipher-des-0.0.6 (new package)
cipher-rc4-0.1.4 (new package)
crypto-random-0.0.9 (new package)
crypto-numbers-0.2.7 (new package)
semigroups-0.16.2.2 (new package)
socks-0.5.4 (new package)
tagsoup-0.13.3 (new package)
transformers-0.4.3.0 (new version)
haddock-library-1.2.0 (new package)
mmorph-1.0.4 (new package)
mtl-2.2.1 (new version)
JuicyPixels-3.2.4 (new package)
aeson-0.7.0.6 (latest: 0.8.1.0) +new-bytestring-builder (new package)
asn1-encoding-0.9.0 (new package)
asn1-parse-0.9.1 (new package)
crypto-pubkey-types-0.4.3 (new package)
crypto-pubkey-0.2.8 (new package)
hslua-0.3.13 (new package)
pandoc-types-1.12.4.2 (new package)
parsec-3.1.9 (new version)
network-uri-2.6.0.3 (new package)
HTTP-4000.2.19 (new version)
pem-0.2.2 (new package)
regex-base-0.93.2 (reinstall) changes: mtl-2.1.3.1 -> 2.2.1
regex-pcre-builtin-0.94.4.8.8.35 (new package)
streaming-commons-0.1.12 (new package)
transformers-compat-0.4.0.4 (new package)
exceptions-0.8.0.2 (new package)
http-client-0.4.11.2 (new package)
temporary-1.2.0.3 (new package)
transformers-base-0.4.4 (new package)
monad-control-1.0.0.4 (new package)
lifted-base-0.2.3.6 (new package)
enclosed-exceptions-1.0.1.1 (new package)
resourcet-1.1.4.1 (new package)
utf8-string-1 (new package)
highlighting-kate-0.5.15 (new package)
void-0.7 (new package)
conduit-1.2.4.2 (new package)
x509-1.5.0.1 (new package)
x509-store-1.5.0 (new package)
x509-system-1.5.0 (new package)
x509-validation-1.5.2 (new package)
tls-1.2.17 (new package)
connection-0.2.4 (new package)
http-client-tls-0.2.2 (new package)
xml-1.3.14 (new package)
texmath-0.8.2 (new package)
yaml-0.8.11 (new package)
zip-archive-0.2.3.7 (new package)
pandoc-1.13.2.1 (new package)
pandoc-crossref-0.1.0.2 (new package)
```

Might note also that the install needs `--force-reinstall` on a clean system:
```
cabal: The following packages are likely to be broken by the reinstalls:
regex-posix-0.95.2
regex-compat-0.95.1
Use --force-reinstalls if you want to install anyway.
```

**Comment by lierdakil** [comment]
Well, I sort of have to depend on pandoc here, and you're right, bulk of these packages are pandoc's dependencies (and pandoc's build takes a while, btw). In fact, only "real" dependency for pandoc-crossref is pandoc itself -- all other dependencies are required by pandoc anyway.

It may be possible to point cabal to your existing pandoc install with some path juggling, but I have literally no idea on how `brew`, of for that matter OSX, works.

Sadly, providing binary packages for OSX is not something I can readily do, since I don't have neither access to OSX, nor time and resources to build for every possible pandoc/ghc combination out there. Sorry.

P.S. Reinstalls are most likely due to mtl updating. Neither pandoc, nor this package, force newest version of mtl, so it seems like cabal's idea of being fancy. `--avoid-reinstalls` helps in such cases, or so I'm told.

**Comment by suknat** [comment]
I get the same problem as @arve0 using macports (which I used to install haskell):

```
Resolving dependencies...
In order, the following would be installed:
SHA-1.6.4.2 (new package)
base64-bytestring-1.0.0.1 (new package)
blaze-builder-0.4.0.1 (new package)
blaze-markup-0.7.0.3 (new package)
blaze-html-0.8.1.1 (new package)
byteable-0.1.1 (new package)
cereal-0.5.1.0 (new package)
cmark-0.5.0 (new package)
data-default-class-0.0.1 (new package)
cookie-0.4.1.6 (new package)
data-default-instances-base-0.0.1 (new package)
data-default-instances-containers-0.0.1 (new package)
data-default-instances-old-locale-0.0.1 (new package)
deepseq-generics-0.1.1.2 (latest: 0.2.0.0) (new package)
digest-0.0.1.2 (new package)
dlist-0.7.1.2 (new package)
data-default-instances-dlist-0.0.1 (new package)
data-default-0.5.3 (new package)
extensible-exceptions-0.1.1.4 (new package)
hourglass-0.2.9 (new package)
hslua-0.4.1 (new package)
http-types-0.9 (new package)
memory-0.10 (new package)
asn1-types-0.3.2 (new package)
asn1-encoding-0.9.3 (new package)
asn1-parse-0.9.4 (new package)
cryptonite-0.10 (new package)
mime-types-0.1.0.6 (new package)
nats-1.1 (new package)
network-2.6.2.1 (new version)
scientific-0.3.4.4 (new package)
attoparsec-0.11.3.4 (latest: 0.13.0.1) (new version)
socks-0.5.4 (new package)
tagged-0.8.2 (new package)
semigroups-0.18.0.1 (new package)
tagsoup-0.13.6 (new package)
transformers-0.4.3.0 (latest: 0.5.0.0) (new version)
haddock-library-1.2.1 (new package)
mmorph-1.0.4 (new package)
mtl-2.2.1 (new version)
JuicyPixels-3.2.6.3 (latest: 3.2.6.4) (new package)
aeson-0.7.0.6 (latest: 0.10.0.0) +new-bytestring-builder (new package)
pandoc-types-1.16 (new package)
parsec-3.1.9 (new version)
network-uri-2.6.0.3 (new package)
HTTP-4000.3.1 (new version)
pem-0.2.2 (new package)
regex-base-0.93.2 (reinstall) changes: mtl-2.1.3.1 -> 2.2.1
regex-pcre-builtin-0.94.4.8.8.35 (new package)
streaming-commons-0.1.15 (new package)
transformers-compat-0.4.0.4 (new package)
exceptions-0.8.0.2 (new package)
http-client-0.4.26.2 (new package)
temporary-1.2.0.3 (new package)
transformers-base-0.4.4 (new package)
monad-control-1.0.0.4 (new package)
lifted-base-0.2.3.6 (new package)
enclosed-exceptions-1.0.1.1 (new package)
resourcet-1.1.7 (new package)
unix-compat-0.4.1.4 (new package)
filemanip-0.3.6.3 (new package)
utf8-string-1.0.1.1 (new package)
highlighting-kate-0.6.1 (new package)
void-0.7.1 (new package)
conduit-1.2.6.1 (new package)
x509-1.6.3 (new package)
x509-store-1.6.1 (new package)
x509-system-1.6.3 (new package)
x509-validation-1.6.3 (new package)
tls-1.3.4 (new package)
connection-0.2.5 (new package)
http-client-tls-0.2.2 (new package)
xml-1.3.14 (new package)
texmath-0.8.4.1 (new package)
yaml-0.8.15.2 (new package)
zip-archive-0.2.3.7 (new package)
pandoc-1.16 +old-locale (new package)
pandoc-crossref-0.1.6.2 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
regex-posix-0.95.2
regex-compat-0.95.1
Use --force-reinstalls if you want to install anyway.
```

Which of the following would you suggest:
- install haskell independently of macports
- use `--force-reinstalls`?

**Comment by lierdakil** [comment]
I would suggest using a sandbox.

Something along the lines of

mkdir pandoc-crossref
cd pandoc-crossref
cabal sandbox init --sandbox=.
cabal install pandoc-crossref
4 янв. 2016 г. 14:45 пользователь "suknat" <notifications@github.com>
написал:

**Comment by suknat** [comment]
Thanks - that worked as far as the install goes, but pandoc cannot find pandoc-crossref when I use `--filter panic-crossref`. How might I point pandoc to the correct location?

**Comment by lierdakil** [comment]
Use full path to executable, e.g. `--filter /path/to/sandbox/bin/pandoc-crossref` or add `/path/to/sandbox/bin` to PATH. Note, that pandoc is probably installed into sandbox along with pandoc-crossref, so it might be a good idea to use that version.

**Comment by suknat** [comment]
Ah! Just realised what a stupid question that was. That worked - thanks! I'll try a compile tomorrow.
Cheers and thanks for all your help.

**Comment by lierdakil** [comment]
Since pandoc-crossref is now in homebrew, I think we can close this.

**Comment by gandalfsaxe** [comment]
I have some collaborators in windows, and installing pandoc-crossref on windows is a huge pain in the butt - especially when you don't have admin rights.

Have you thought about easing the installation process in a true cross-platform fashion such as putting it on PyPI to allow installation via `pip` or on conda source forge? I'd be happy to help, but I think long term the easiest thing to do is to setup it up to automatically deploy with new builds.

**Comment by lierdakil** [comment]
You're aware that there are automatic builds available on each tagged release, right? It's mentioned [in the readme](https://github.com/lierdakil/pandoc-crossref#installation):

> There are a few pre-built executables available at [releases page](https://github.com/lierdakil/pandoc-crossref/releases) for Windows, OSX and Linux. Bear in mind that those are a product of an automated build script, and as such, provided as-is, with zero guarantees.

Those are not at all guaranteed to work, but are very likely to work on Windows specifically (at least as long as Pandoc itself is installed). The only caveat is getting the versions right.

PyPI for Python is what Hackage is for Haskell. Why it came up here I have no idea.

**Comment by gandalfsaxe** [comment]
I did see, I guess I somehow thought more setup was needed than just the executable in the path. Conda would still be the easiest option I think, both for ease of installing (no need to add to path manually) and for the ease of updating (`conda update pandoc-crossref` or simply `conda update --all`). But if it's not something you use / want to spend time on, I understand. If all we need is the executable in the path, I can deal with that :)

You're right, mentioning PyPI in this context was meaningless, never mind.

I only just realized that `pandoc-citeproc` is included in the x86 zip [release of pandoc](https://github.com/jgm/pandoc/releases/tag/2.2.1). I thought that was going to be my installation pain point bottleneck, but I think installation on windows is manageable after all then 👍

**Comment by gandalfsaxe** [comment]
(Actually I still have to build for now since the latest release is older than the latest changes [you made ](https://github.com/lierdakil/pandoc-crossref/issues/183)to the equation labels 😄 )

**Comment by lierdakil** [comment]
You can grab the latest Windows build from CI directly. https://ci.appveyor.com/project/lierdakil/pandoc-crossref/build/artifacts -- or for any commit made in last 6 months for that matter.

**Comment by gandalfsaxe** [comment]
Great tip! Thanks.
