### ISSUE TITLE
Auto figure labels?

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#150]
Is there something similar to `autoSectionLabels` for figures? I.e. so you don't have to type:

`[Caption](image.png) {fig:something}`
but can just type
`[Caption](image.png) {something}`

and can then refer to it by `@fig:something`.

**Comment by lierdakil** [comment]
You're misunderstanding the purpose of `autoSectionLabels`. It's not to save a few keystrokes, but to provide some (thin) compatibility between crossref and Pandoc's automatically-assigned section labels.
