### ISSUE TITLE
\listoftables isn't produced in docx

### ISSUE THREAD

**Issue by atanasj** [lierdakil/pandoc-crossref#151]
Hi,
I'm not sure if I'm doing something wrong, but I don't seem to be getting any list of tables using the \listoftables command. I am entering the following information into the YAML metadata block:

```
---
header-includes: \listoftables
linkReferences: True
nameInLink: True
figPrefix:
  - “Table”
  - “Tables”
figPrefix:
  - “Figure”
  - “Figures”
listing: True
codeBlockCaptions: True
---
```

OSX 10.12.6
pandoc 2.0.2
pandoc-crossref v0.2.7.0

Am I doing something wrong? Any help greatly appreciated. Thanks.

Atanas.

**Comment by lierdakil** [comment]
Uh... `header-includes: \listoftables` won't do what you expect it to do. It will insert raw TeX command into document header (e.g. LaTeX preamble or HTML `<head>`, and I don't think it's a thing in docx even).

What you want to do is to use `\listoftables` in the document where you would like to put said list of tables. Bear in mind, it's, quite literally, a list of table captions. I personally find it useful when preparing articles for publication.

**Comment by atanasj** [comment]
Thanks for your response, and thanks in advance for your patience. Yes, this feature would be very useful and a welcome addition to my workflow, for similar reasons to what you use if for.

I tried the \listoftables and \listoffigure in the document where I wanted them inserted, but I still don't get either list appear. 

I built the package into a sandbox as instructed. Am I missing something on the filter by chance? I am using '-F pandoc-crossref'.

**Comment by lierdakil** [comment]
What Pandoc and pandoc-crossref versions are you using?

**Comment by lierdakil** [comment]
bump

**Comment by atanasj** [comment]
Sorry, I thought I responded... I'm now on 2.0.4, but was on 2.0.2 when I raised the issue.

**Comment by atanasj** [comment]
Oh, crossref is the latest stable... Sorry, not on my computer to give you the exact version number. But it's the most recent 2.x.x version. I'll try and be Mohr specific when next on my computer.

**Comment by lierdakil** [comment]
pandoc-crossref 0.2.x is only compatible with Pandoc 1.x, Pandoc 2.0 changed a bunch of internals. While it doesn't outright crash, some things might not work or not work as expected. See https://github.com/lierdakil/pandoc-crossref/issues/142 for more details.

There's a beta version available. If you're comfortable with binaries, check [the releases page](https://github.com/lierdakil/pandoc-crossref/releases). If not, try building from `master`.

**Comment by atanasj** [comment]
Thanks for that. The beta seems to work, so I'll use that for now. Thank you again for your help, and a great package!
