### ISSUE TITLE
Figure captions italic?

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#152]
First, thank you for making pandoc-crossref, it's very useful 😃

How do I make figure captions italic on default?
I tried many things with `figureTemplate` but I couldn't get any change.

Also, if I set `figureTitle: "**Figure**"` then it will show `**Figure** 1: bla bla`, but how do I get the number bold also?

**Comment by lierdakil** [comment]
This should work more or less as you would expect:

```md
---
figureTemplate: '*$$figureTitle$$ $$i$$*$$titleDelim$$ $$t$$'
---

![Some figure](figure.img){#fig:figure1}
```

Note the single quotes around value of `figureTemplate` (could've been double quotes). Reason for needing that is YAML parser, unescaped `*` isn't allowed in YAML, so whole value will end up being discarded (at which point, default takes precedence)

**Comment by GandalfSaxe** [comment]
Hmm doesn't immediately work for me. "Figure 1:" is not bold, and the figure caption itself is not italic. Do I need additional stuff in my YAML metadata?

**Comment by lierdakil** [comment]
This was intended to be self-contained example (although the example only italicizes 'Figure n' part, not what you describe). What pandoc/pandoc-crossref versions are you using?

**Comment by GandalfSaxe** [comment]
**pandoc 1.19.2.1** (via conda, although I can see tha homebrew have a pandoc 2.0.3 installed, and conda won't update it further).

**pandoc-crossref 0.2.7.0**

**Comment by lierdakil** [comment]
Pandoc 1.19.2.4 with pandoc-crossref 0.2.7.0 seems to work as expected:

```
[:] $ cat /tmp/test.md
---
figureTemplate: '*$$figureTitle$$ $$i$$*$$titleDelim$$ $$t$$'
---

![Some figure](figure.img){#fig:figure1}
```
```
[:] $ pandoc -F pandoc-crossref -t html /tmp/test.md
<div class="figure">
<embed src="figure.img" id="fig:figure1" />
<p class="caption"><em>Figure 1</em>: Some figure</p>
</div>
```
Notice `<em>` around `Figure 1`.

**Comment by GandalfSaxe** [comment]
1. Is there any way to achieve bold "Figure 1:" and italic "Caption here"? [Example](https://i.stack.imgur.com/fFmwA.png)

I tried figureTemplate: `'**$$figureTitle$$ $$i$$***$$titleDelim$$ $$t$$*'` but that gives me:
`<figcaption><strong>Figure 1</strong><em>: Some figure</em></figcaption>`, so \<strong> ends too early and \<em> starts to soon.

2. If I try to to convert to PDF via latex instead by running `pandoc -F pandoc-crossref Test.md -o Test.pdf` I get error:
```
Error producing PDF.
! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.63 \textbackslash
```
Do you know why?

3. How did you know that `-F` works the same as `--filter`? Pretty neat. It's seems [undocumented](http://pandoc.org/MANUAL.html).

**Comment by GandalfSaxe** [comment]
I figured out question 2 above. I get the `! LaTeX Error: Missing \begin{document}.` error if I compile with pandoc 2.0.3, but not pandoc 1.19.2.1. I presume this is because pandoc-crossref is not compatible with pandoc 2.0.3 yet unless you're running the crossref beta branch `pandoc-2.0`?

**Comment by lierdakil** [comment]
I think I should mention that crossref's templates are not supported in LaTeX output. This is mentioned in readme. I can recommend using a custom LaTeX output template (with `pandoc --template path-to-template.tex`, you can start from `pandoc -D latex`) with cleveref and use cleveref's customization commands to format everything however you like.

So,
1. `$$titleDelim$$` is rendered as `:`. So... why are you surprised by the output exactly?
2. See https://github.com/lierdakil/pandoc-crossref/issues/142
3. 
```
$ pandoc --help | grep filter
  -F PROGRAM            --filter=PROGRAM                                
                        --lua-filter=SCRIPTPATH    
```

**Comment by GandalfSaxe** [comment]
Thanks.

Any chance of crossref's templates being supporting in LaTeX output or is that unlikely?

**Comment by lierdakil** [comment]
Unlikely because custom Pandoc templates are a thing. Making crossref templates work in TeX is a lot of effort, and it'll be broken with non-default templates anyway, so I don't really see the point. I could accept a PR though, if anyone's interested (it's not hard conceptually, just need to add a bunch of LaTeX commands to preamble that would set up formatting to match templates)

Primary reason for why that is an issue in the first place is LaTeX is treated differently from all other output formats. While in other output formats rendering everything has to be handled by crossref itself, with LaTeX output the task is offloaded to LaTeX engine (because I need LaTeX export with references still being references, and I would imagine I'm not alone). And those are two rather different systems. (arguably, docx and odt could also be "special" like LaTeX, but I just don't have neither time nor patience to fight with either OOXML or ODF, both are nightmare fuel IMO)

**Comment by GandalfSaxe** [comment]
Ok. So if I wanted to get this working for LaTeX, I would need to make a custom pandoc template?

**Comment by lierdakil** [comment]
Yes. Or, alternatively, use `header-includes` to include arbitrary LaTeX commands into default template header.
