### ISSUE TITLE
Label AND scale image? (HTML?)

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#153]
Since Markdown does not support resizing of images natively, the only reliable way (that I know) to achieve image scaling is instead of using `![Caption](image.png){fig:somefig}` then using `<img src="image.png" style="zoom:50%">{#fig:somefig}`. However this does not seem to work, and breaks the image completely when rendering it with pandoc.

Is there any way to both scale and label a figure?

**Comment by lierdakil** [comment]
Pandoc supports image size attributes, refer to [Pandoc's manual](http://pandoc.org/MANUAL.html#images)
