### ISSUE TITLE
Skip figure number?

### ISSUE THREAD

**Issue by GandalfSaxe** [lierdakil/pandoc-crossref#157]
Is it possible to have automatic figure numbering on, but then skip it for one figure, having no figure caption at all?

**Comment by lierdakil** [comment]
I *think* you have to specify figure identifier starting with `fig:` to get a figure numbered. So... no?

**Comment by GandalfSaxe** [comment]
In my testing, I get a figure just by !()[file.jpg]. Then it shows the caption "Figure 1" after converting it from Markdown to LaTeX.

But actually it's all `pandoc`, and happens irregardless of using filter `pandoc-crossref`, so I should have asked this `pandoc-discuss` mailing list. So you can close this. But if you or anyone else happen to know this, I'd be interested.

**Comment by lierdakil** [comment]
It's LaTeX actually. Well, that and Pandoc's `implicitfigures` Markdown extension. At least with Pandoc 2.0, it seems like images with empty alt text are never interpreted as figures:
```
[:~] $ pandoc --version
pandoc 2.0.1.1
[:~] $ pandoc -t latex <<< '![asd](fig.png)'
\begin{figure}
\centering
\includegraphics{fig.png}
\caption{asd}
\end{figure}
[:~] $ pandoc -t latex <<< '![](fig.png)'
\includegraphics{fig.png}
```
(bear in mind pandoc-crossref 0.2.7 is not compatible, 0.3 beta available, check releases page)

**Comment by GandalfSaxe** [comment]
Ah I see. That seems like a reasonable default.
Thanks.
