### ISSUE TITLE
Beamer and undefined references

### ISSUE THREAD

**Issue by klpn** [lierdakil/pandoc-crossref#159]
I use pandoc-crossref 0.3.0.0 with Pandoc 2.0.3. When I try to compile a Beamer presentation with the commandline: `pandoc -F pandoc-crossref -t beamer -o pres.pdf pres.md --pdf-engine=lualatex --template=default.beamer --bibliography=../kp.bib`, I get `Undefined cross-reference: fig:myfig`.

The figure label in question is actually defined in an external file read with `\input`, but the references are replaced with `¿fig:myfig?`, and they are not correctly rendered in the PDF output. They are correctly rendered if I compile with: `pandoc -t json pres.md | pandoc-crossref latex | pandoc -f json -t beamer -o pres.pdf --pdf-engine=lualatex --template=default.beamer --bibliography=../kp.bib`.

From what I understand, this replacement of missing references is disabled if `latex` is used as output format. Should `beamer` output be treated the same way, because both `beamer` and `latex` are transformed into LaTeX source code by Pandoc's LaTeX writer (and then into PDF if the `pdf` extension is specified)?

**Comment by lierdakil** [comment]
Sounds reasonable. Current `master` now treats `beamer` as if it is `latex`. If you could test the current `master` that would be nice.

**Comment by klpn** [comment]
I built `master`, and the references are correctly rendered also with the shorter commandline, so my problem is solved.

**Comment by lierdakil** [comment]
Thanks for testing! Let's keep it open, otherwise I might forget to update changelog on next release.
