### ISSUE TITLE
Build fails at Travis

### ISSUE THREAD

**Issue by hanjoosten** [lierdakil/pandoc-crossref#161]
While [upgrading ampersand](https://github.com/AmpersandTarski/Ampersand/compare/feature/Upgrades) to GHC 8.2.2., [travis-ci fails to build](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/326074163) pandoc-crossref. Building locally on my windows machine and [also at appveyor](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/326074163) works great. I have never seen something like this, that the linker fails 😞 .
Any idea what is going on?

**Comment by lierdakil** [comment]
Well, the errors about `pthread_create` etc would suggest that linker isn't linking-in `pthread`. Perhaps adding `-lpthread` flag manually would work?

Also, the build log you linked tries to build with GHC 8.0.2 I think? At least [config seems to say so](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/326074163/config)? Pretty sure that [does build on Travis](https://travis-ci.org/lierdakil/pandoc-crossref/builds/315828367) -- but I use `stack setup` to get a compiler.

**Comment by hanjoosten** [comment]
Ah, sorry for the inconvenience. I fortot to set the GHC version . This makes cabal compile and link fine, stack is still failing. I have to dig into this some deeper as soon as I have time. Thanks for the answer!

**Comment by hanjoosten** [comment]
Still struggling with stack build on travis-ci. However this issue is related to [this issue of pandoc](https://github.com/jgm/pandoc/issues/4130).

**Comment by hanjoosten** [comment]
@lierdakil I think my issue is because the library lacks the -threaded option. Could that please be added? Thanks!

**Comment by lierdakil** [comment]
Apparently, I was wrong, an hackage won't allow editing build flags. Well, published as v0.3.0.1, along with some other stuff (see changelog). Let me know if it helps (or doesn't)

**Comment by hanjoosten** [comment]
Thanks so much! This change fixed the build problem I had. logs: [before](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/328723392) and [after](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/329494312) the [change](https://github.com/AmpersandTarski/Ampersand/compare/12ac2dafa16c...fb7cdc582aaa).
