### ISSUE TITLE
Markdown to Jupyter export with crossreferences

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#164]
There is an easy way to export Markdown text with code block insertions to Jupyter notebooks with various kernels. Via Stitch + Notedown + patch = [Knitty](https://github.com/kiwi0fruit/knitty) - interface wrapper around them. Such documents can be edited with [Atom/Hydrogen](https://nteract.gitbooks.io/hydrogen/docs/Usage/GettingStarted.html) and MPP.

It would be nice to have cross-references in exported Jupyter notebooks. At the moment cross-references via  *pandoc-crossref* is not possible because the algorithm of convertion to Jupyter includes markdown to markdown export with Pandoc (all Pandoc filters are applied in this part). Then the new markdown document is straight-forwardly converted to ipynb: Markdown + common code blocks are converded to markdown Jupyter cells, marked code blocks are converted to Jupyter input code cells.

Is it possible to add to the *pandoc-crossref* filter the option of converting markdown with pandoc-crossref insertions to static markdown with already numbered figs, equations, tables (may be with html insertions because Jupyter markdown cells have different flavor than Pandoc)?

// Markdown flavor mismatch actually needs investigation and would affect the hypothetical algorithm. But putting this aside as I understand how it can be done in outline.

**Comment by lierdakil** [comment]
Hi. Um. Not entirely sure what you're asking for here. `pandoc-crossref` will do its job regardless of output format -- it'll work with Markdown exactly as it would work with HTML (LaTeX is the only special one):
```
$ echo -e '![A figure](image.png){#fig:asd}\n\n@Fig:asd' | pandoc -F pandoc-crossref -t markdown -f markdown
![Figure 1: A figure](image.png){#fig:asd}

Fig. 1
```

Note: you can output to other Markdown flavours, like `gfm` or `commonmark`. Although not all features are guaranteed to work correctly with less rich Markdown flavours.

**Comment by kiwi0fruit** [comment]
Thanks! That looks exactly like what I need.

Strange... I thought that I tested pandoc-crossref and it didn't change
labels in some cases. I'm glad that I mixed things up. I'll test all use
cases after all.

22 янв. 2018 г. 6:32 PM пользователь "Nikolay Yakimov" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
I've tested pandoc markdown output (after pandoc-crossref) with Jupyter markdown cells: nothing works as expected when `-t markdown`. Jupyter's markdown renderer does not support markdown attributes.

**Comment by kiwi0fruit** [comment]
But raw HTML works: `<img src="http://localhost:8888/static/base/images/logo.png" alt="Figure 1: A figure" id=fig:asd>`

**Comment by kiwi0fruit** [comment]
Same is for equations: `[$$f(x)\qquad(1)$$]{#eq:qwe}` does not work. But `<div id="eq:qwe">$$f(x)\qquad(1)$$</div>` and `<a name="eq:qw"></a>$$f(x)\qquad(1)$$` work.

**Comment by kiwi0fruit** [comment]
Same is for tables: neither work:
```
::: {#tbl:zxc}
  a   b
  --- ---
  1   2

  : Table 1: Table
:::

Tbl. 1


<div id="tbl:zxc">

| a | b |
| - | - |
| 1 | 2 |

Table 1: Table

</div>
```

The only solution seems to be with caption that is simply near the table:
```
Table 1: Table<a name="tbl:zxc"></a>

| a | b |
| - | - |
| 1 | 2 |
```

**Comment by kiwi0fruit** [comment]
I guess this is a work for simple pandoc filter separate from pandoc-crossfer that iterates over images, display math and tables with attributes and moves `#id` to the `<a name="id"></a>` in case of Tables, and moves id, css classes together with attributes to `<img>` or `<div>` in case of Fig and Eq. And then pandoc export with `-t gfm`. I guess it should be merged with `--to-ipynb` option from [here](https://github.com/kiwi0fruit/knitty/blob/master/knitty.md#11-new-command-line-interfaces) and moved to separate filter that is applied after knitty and after pandoc-crossref (so code blocks are prepared in the same loop).

**Comment by kiwi0fruit** [comment]
Something tells me that you would be not interested in implementing this in pandoc-crossref so I'm closing the issue. In case I'm wrong you can always reopen it.

**Comment by lierdakil** [comment]
> you can output to other Markdown flavours, like gfm or commonmark

Pretty sure everyone and their coffee grinder support commonmark nowadays. Try that.

Also be aware that you can tweak Pandoc Markdown output format extensions at will, see <http://pandoc.org/MANUAL.html#extensions>

**Comment by kiwi0fruit** [comment]
There is a small chance that there is a working combination of
extensions... But I doubt it :-) But `commonmark` worth a try (and see what
output would look like when disabling attributes extensions).

23 янв. 2018 г. 19:09 пользователь "Nikolay Yakimov" <
notifications@github.com> написал:

**Comment by lierdakil** [comment]
> But I doubt it 

Most likely there is one. After all, with all extensions disabled, Pandoc Markdown isn't that different from commonmark.

**Comment by kiwi0fruit** [comment]
Here is two possibilities: pandoc will strip attributes (that are needed
for working local hyperlinks) or it will convert to raw html. A guess it
will strip them in most cases (or convert to non-working in Jupyter form:
like gfm tables with attributes are wrapped it div. But Jupyter doesn't
understand this form).

23 янв. 2018 г. 7:17 PM пользователь "Nikolay Yakimov" <
notifications@github.com> написал:

**Comment by kiwi0fruit** [comment]
But I hope for commonmark writer to be what I need. At least it seem
reasonable for Pandoc when exporting to commonmark use raw html heavily:
html is a valid Markdown after all.

23 янв. 2018 г. 7:22 PM пользователь "Peter Zagubisalo" <
peter.zagubisalo@gmail.com> написал:

**Comment by kiwi0fruit** [comment]
@lierdakil You were right. These settings produce Jupyter compatible crossreferences:
```bat
set jupymd=markdown-bracketed_spans-fenced_divs-link_attributes-simple_tables-multiline_tables-grid_tables-pipe_tables-fenced_code_attributes-markdown_in_html_blocks-table_captions

pandoc -t %jupymd% -F pandoc-crossref test.md -o test.md.md
```
where `test.md` is:
```md
![A figure](http://localhost:8888/static/base/images/logo.png){#fig:asd}

@Fig:asd

$$f(x)$${#eq:qwe}

@Eq:qwe

| a | b |
|---|---|
| 1 | 2 |

: Table {#tbl:zxc}

@Tbl:zxc
```
And the output is:
```md
<img src="http://localhost:8888/static/base/images/logo.png" alt="Figure 1: A figure" id="fig:asd" />

Fig. 1

<span id="eq:qwe">$$f(x)\qquad(1)$$</span>

Eq. 1

<div id="tbl:zxc">

<table>
<caption>Table 1: Table</caption>
<thead>
<tr class="header">
<th>a</th>
<th>b</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>

Tbl. 1
```

**Comment by kiwi0fruit** [comment]
I guess only Figs with subfigures are left for testing...
