### ISSUE TITLE
error during install with cabal: No instance for (Monad Parser) arising from a do statement

### ISSUE THREAD

**Issue by mokawi** [lierdakil/pandoc-crossref#165]
Hi,

I'm trying to install crossref with cabal, and it's giving me an error statement: 

> Resolving dependencies...
> Configuring pandoc-crossref-0.3.0.1...
> Building pandoc-crossref-0.3.0.1...
> Failed to install pandoc-crossref-0.3.0.1
> Build log ( /home/mok/.cabal/logs/pandoc-crossref-0.3.0.1.log ):
> cabal: Entering directory '/tmp/cabal-tmp-2551/pandoc-crossref-0.3.0.1'
> Configuring pandoc-crossref-0.3.0.1...
> Building pandoc-crossref-0.3.0.1...
> Preprocessing library pandoc-crossref-0.3.0.1...
> [ 1 of 18] Compiling Paths_pandoc_crossref ( dist/build/autogen/Paths_pandoc_crossref.hs, dist/build/Paths_pandoc_crossref.o )
> [ 2 of 18] Compiling Text.Pandoc.CrossRef.Util.PandocOrphans ( lib/Text/Pandoc/CrossRef/Util/PandocOrphans.hs, dist/build/Text/Pandoc/CrossRef/Util/PandocOrphans.o )
> [ 3 of 18] Compiling Text.Pandoc.CrossRef.References.Types ( lib/Text/Pandoc/CrossRef/References/Types.hs, dist/build/Text/Pandoc/CrossRef/References/Types.o )
> [ 4 of 18] Compiling Text.Pandoc.CrossRef.Util.Util ( lib/Text/Pandoc/CrossRef/Util/Util.hs, dist/build/Text/Pandoc/CrossRef/Util/Util.o )
> 
> lib/Text/Pandoc/CrossRef/Util/Util.hs:83:1: warning: [-Wredundant-constraints]
>     • Redundant constraint: Monad m
>     • In the type signature for:
>            extRR :: (Monad m, Typeable a, Typeable b) =>
>                     (a -> m (ReplacedResult a))
>                     -> (b -> m (ReplacedResult b)) -> a -> m (ReplacedResult a)
> [ 5 of 18] Compiling Text.Pandoc.CrossRef.Util.Meta ( lib/Text/Pandoc/CrossRef/Util/Meta.hs, dist/build/Text/Pandoc/CrossRef/Util/Meta.o )
> 
> lib/Text/Pandoc/CrossRef/Util/Meta.hs:108:1: warning: [-Wredundant-constraints]
>     • Redundant constraint: Functor m
>     • In the type signature for:
>            tryCapitalizeM :: (Functor m, Monad m, Walkable Inline a,
>                               Default a, Eq a) =>
>                              (String -> m a) -> String -> Bool -> m a
> [ 6 of 18] Compiling Text.Pandoc.CrossRef.Util.Template ( lib/Text/Pandoc/CrossRef/Util/Template.hs, dist/build/Text/Pandoc/CrossRef/Util/Template.o )
> [ 7 of 18] Compiling Text.Pandoc.CrossRef.Util.CustomLabels ( lib/Text/Pandoc/CrossRef/Util/CustomLabels.hs, dist/build/Text/Pandoc/CrossRef/Util/CustomLabels.o )
> [ 8 of 18] Compiling Text.Pandoc.CrossRef.Util.Settings.Template ( lib/Text/Pandoc/CrossRef/Util/Settings/Template.hs, dist/build/Text/Pandoc/CrossRef/Util/Settings/Template.o )
> [ 9 of 18] Compiling Text.Pandoc.CrossRef.Util.Options ( lib/Text/Pandoc/CrossRef/Util/Options.hs, dist/build/Text/Pandoc/CrossRef/Util/Options.o )
> [10 of 18] Compiling Text.Pandoc.CrossRef.Util.CodeBlockCaptions ( lib/Text/Pandoc/CrossRef/Util/CodeBlockCaptions.hs, dist/build/Text/Pandoc/CrossRef/Util/CodeBlockCaptions.o )
> [11 of 18] Compiling Text.Pandoc.CrossRef.Util.ModifyMeta ( lib/Text/Pandoc/CrossRef/Util/ModifyMeta.hs, dist/build/Text/Pandoc/CrossRef/Util/ModifyMeta.o )
> [12 of 18] Compiling Text.Pandoc.CrossRef.Util.Settings.Gen ( lib/Text/Pandoc/CrossRef/Util/Settings/Gen.hs, dist/build/Text/Pandoc/CrossRef/Util/Settings/Gen.o )
> [13 of 18] Compiling Text.Pandoc.CrossRef.References.Blocks ( lib/Text/Pandoc/CrossRef/References/Blocks.hs, dist/build/Text/Pandoc/CrossRef/References/Blocks.o )
> [14 of 18] Compiling Text.Pandoc.CrossRef.References.Refs ( lib/Text/Pandoc/CrossRef/References/Refs.hs, dist/build/Text/Pandoc/CrossRef/References/Refs.o )
> [15 of 18] Compiling Text.Pandoc.CrossRef.References.List ( lib/Text/Pandoc/CrossRef/References/List.hs, dist/build/Text/Pandoc/CrossRef/References/List.o )
> [16 of 18] Compiling Text.Pandoc.CrossRef.Util.Settings ( lib/Text/Pandoc/CrossRef/Util/Settings.hs, dist/build/Text/Pandoc/CrossRef/Util/Settings.o )
> [17 of 18] Compiling Text.Pandoc.CrossRef.References ( lib/Text/Pandoc/CrossRef/References.hs, dist/build/Text/Pandoc/CrossRef/References.o )
> [18 of 18] Compiling Text.Pandoc.CrossRef ( lib/Text/Pandoc/CrossRef.hs, dist/build/Text/Pandoc/CrossRef.o )
> Preprocessing executable 'pandoc-crossref' for pandoc-crossref-0.3.0.1...
> [1 of 2] Compiling ManData          ( src/ManData.hs, dist/build/pandoc-crossref/pandoc-crossref-tmp/ManData.o )
> [2 of 2] Compiling Main             ( src/pandoc-crossref.hs, dist/build/pandoc-crossref/pandoc-crossref-tmp/Main.o )
> 
> src/pandoc-crossref.hs:43:7: error:
>     • No instance for (Monad Parser) arising from a do statement
>     • In the expression:
>         do { numVers <- flag
>                           Nothing
>                           (Just NumericVersion)
>                           (long "numeric-version" <> help "Print version");
>              vers <- flag
>                        Nothing
>                        (Just Version)
>                        (long "version" <> short 'v' <> help "Print version");
>              man' <- flag
>                        Nothing (Just Man) (long "man" <> help "Show manpage");
>              hman <- flag
>                        Nothing
>                        (Just HtmlMan)
>                        (long "man-html" <> help "Show html manpage");
>              fmt <- optional $ strArgument (metavar "FORMAT");
>              return $ go (numVers <|> vers <|> man' <|> hman) fmt }
>       In an equation for ‘run’:
>           run
>             = do { numVers <- flag
>                                 Nothing
>                                 (Just NumericVersion)
>                                 (long "numeric-version" <> help "Print version");
>                    vers <- flag
>                              Nothing
>                              (Just Version)
>                              (long "version" <> short 'v' <> help "Print version");
>                    man' <- flag
>                              Nothing (Just Man) (long "man" <> help "Show manpage");
>                    hman <- flag
>                              Nothing
>                              (Just HtmlMan)
>                              (long "man-html" <> help "Show html manpage");
>                    fmt <- optional $ strArgument (metavar "FORMAT");
>                    return $ go (numVers <|> vers <|> man' <|> hman) fmt }
>             where
>                 go :: Maybe Flag -> Maybe String -> IO ()
>                 go (Just Version) _
>                   = putStrLn
>                     $ "pandoc-crossref v"
>                       <>
>                         "0.3.0.1"
>                         <>
>                           " built with Pandoc v"
>                           <>
>                             "2.0.6"
>                             <> "," <> " pandoc-types v" <> "1.17.3.1" <> " and GHC " <> "8.0.1"
>                 go (Just NumericVersion) _ = putStrLn "0.3.0.1"
>                 go (Just Man) _ = putStrLn man
>                 go (Just HtmlMan) _
>                   = withSystemTempFile "pandoc-crossref-manual.html" $ \ fp h -> ...
>                 go Nothing _ = toJSONFilter f
>                 f fmt p@(Pandoc meta _)
>                   = runCrossRefIO meta fmt defaultCrossRefAction p
> cabal: Leaving directory '/tmp/cabal-tmp-2551/pandoc-crossref-0.3.0.1'
> cabal: Error: some packages failed to install:
> pandoc-crossref-0.3.0.1 failed during the building phase. The exception was:
> ExitFailure 1

In my first try, I did it after install pandoc with cabal. Then I tried installing haskell-platform using apt, then ghc-pandoc-dev (along with pandoc), but it never seems to work. My ghc version is 8.0.1.

**Comment by lierdakil** [comment]
This is a bug in GHC 8.0.1. Which is fixed in GHC 8.0.2. I don't see the point in adapting to compiler bugs that are already fixed upstream, so my advice is: update your compiler.

**Comment by mokawi** [comment]
It worked. Thanks!
