### ISSUE TITLE
pandoc 2.1.2 support

### ISSUE THREAD

**Issue by garethstockwell** [lierdakil/pandoc-crossref#168]
When do you plan to release a cabal package which can be installed with pandoc 2.1.2?

The latest is pandoc-crossref 0.3.0.1, which requires pandoc 2.0.*:
https://hackage.haskell.org/package/pandoc-crossref-0.3.0.1

**Comment by lierdakil** [comment]
Package candidate uploaded: https://hackage.haskell.org/package/pandoc-crossref-0.3.0.2/candidate

If you could test it, that would be nice.

**Comment by lierdakil** [comment]
Published to Hackage
