### ISSUE TITLE
Upper case ref prefix when starting a sentence.

### ISSUE THREAD

**Issue by arve0** [lierdakil/pandoc-crossref#17]
`[@fig:lab]` always gives lower case.

`bla bla. Figure \ref{fig:lab}` is a workaround.

**Comment by lierdakil** [comment]
I kind of know about it. I couldn't invent a heuristic to automatically capitalize first character, but I guess it's possible to let users capitalize reference, f.ex. `[@Fig:lab]` could mean `Figure ...`, while `[@fig:lab]` would resolve to `figure ...`. I'll try to implement this in a day or two.

**Comment by lierdakil** [comment]
Package candidate v0.1.2.0 is avalable, which implements this feature request.

You can install it via `cabal install http://hackage.haskell.org/package/pandoc-crossref-0.1.2.0/candidate/pandoc-crossref-0.1.2.0.tar.gz`

I will be grateful for any bugreports.

You can see what changed [here](https://github.com/lierdakil/pandoc-crossref/compare/v0.1.1.0...v0.1.2.0)

**Comment by arve0** [comment]
Thanks! I'll try it tomorrow.

**Comment by arve0** [comment]
It works lovely!
