### ISSUE TITLE
Delimiter after section numbers

### ISSUE THREAD

**Issue by bramvermeer** [lierdakil/pandoc-crossref#172]
I am using crossref section numbering, which prefixes each section title with a number, like this:

> 3.1 New Section Title

Is there a way to add a point after the number, or to style the number differently from the title (e.g. italicize), like:

> 3.1. New Section Title
> *3.1* New Section Title

I didn´t see this in the docs/forum, but maybe I overlooked something. Many thanks for any help!

**Comment by lierdakil** [comment]
Huh. It's a reasonable feature to expect, given the amount of customization already offered. But it's not there for some reason (most likely oversight).

So anyway, it's now implemented in 0.3.1.0, which is currently available as a package candidate at https://hackage.haskell.org/package/pandoc-crossref-0.3.1.0/candidate

Provided nothing breaks on CI, I'll promote the candidate to the full release at some point.
