### ISSUE TITLE
flextable and knitr/markdown/docx

### ISSUE THREAD

**Issue by HJAllen** [lierdakil/pandoc-crossref#175]
flextable is a library for creating docx tables which adds word xml directly to the knitted document. I have been using pandoc-crossref in a Rstudio/rmarkdown/knitr/docx workflow with pandoc.table with great success. With flextable, there isn't the option to add a tag to the caption in a way similar to pandoc.table.
Questions:
1. Has anyone developed a solution for use with pandoc-crossref?
2. If not, might one be able to place the table in a <div  id="tbl:Label"> tag similar to multi-figures or code blocks?

Below is a reproducible .Rmd snippet.

    ---
    title: "flextableSnippet"
    output: word_document
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    library(flextable)
    ```
    
    ## flextable table
    
    ```{r}
    iris.t <-
      iris[1:5,] %>%
      regulartable() %>% 
      style(pr_c = officer::fp_cell(vertical.align = "bottom",
                                    border.bottom = officer::fp_border(width = 2)), part = "header") %>% 
      rotate(j = names(iris)[-c(1:2)],
             rotation = "tbrl", part = "header", align = "bottom") %>% 
      height(height = max(dim_pretty(., part = "header")$widths), part = "header") %>% 
      width(width = dim_pretty(.,part = "body")$widths)%>% 
      add_footer(top = TRUE, Sepal.Length = "Sample Dates.")
    iris.t
    ```

**Comment by HJAllen** [comment]
Upon further investigation, I see that when knitted, the flextable is written to the intermediate .md file as an openxml code chunk. When the code chunk is wrapped in <div id="fig:Label"> as described in the help for subfigures, a proper caption is produced and references are valid. This seems like a reasonable solution to me. So, the question is, can the <div> approach be expanded to include the tbl tag?

**Comment by lierdakil** [comment]
Well... FWIW, there's https://github.com/lierdakil/pandoc-crossref/pull/174, which doesn't really care what prefix you're using, so it *should* work for subfigures with `id="tbl:label"` (and it will produce the correct formatting in caption and references, of course). But it's work-in-progress and the behaviour is subject to change without advance warnings.

Apart from that... yes, definitely possible. Whether I'll find time to implement that is up in the air though -- #174 seems like a more promising direction, so it'll likely end up higher on the priority list.

**Comment by HJAllen** [comment]
Thanks for the pointer.  I am using pandoc 2.1.3 and pandoc-crossref windows binary v0.3.1.0. The snippet in #84 as below. docx output does not create a reference for neither `[@cl:addgp]` nor `[@dfn:ring]` but does for the section reference `[@sec:top]`. I understand this is a work in progress. Is there any further documentation on this feature, or, do you see an obvious mistake in my code?

command
`C:/Users/JALLEN/R/RStudio-1.1.423/bin/pandoc/pandoc test.md --to docx --from markdown --output test.docx --filter pandoc-crossref`

document
```
---
title: Test Document
author: HJA
output:
  word_document:
    pandoc_args: [
      "--filter", "pandoc-crossref"
      ]
    keep_md: TRUE
prefixes:
  dfn:
    ref: ["dfn.", "dfns."]
    name: "Definition"
  cl:
    ref: ["cl.", "cls."]
    scope: ["dfn"]
---

# Section{#sec:top}

See test reference [@cl:addgp] or [@dfn:ring]

<div id="dfn:ring">
A _ring_ is a triple $(R,+,*)$ satisfying:

#. [$+$ is an abelian group]{#cl:addgp}
#. [$*$ is a monoid]{#cl:multmon}
#. [$*$ distributes over $+$]{#cl:distrib}
</div>


Make sure pandoc-crossref works by referencing [@sec:top]
```

**Comment by HJAllen** [comment]
That's Great! v0.4.0.0-alpha0 works as advertised. For completeness, I have included the .Rmd file which demonstrates. One note, the `\n' linefeeds used in catting of the caption appear to be necessary as flextable does not append a linefeed to the end of its output nor does the </div> get picked up.

    ---
    title: "flextableSnippet"
    output:
      word_document:
        pandoc_args: [
          "--filter", "pandoc-crossref"
          ]
        keep_md: TRUE
    editor_options: 
      chunk_output_type: console
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    library(flextable)
    ```
    
    # flextable table
    
    Reference to iris table [@tbl:iris]
    
    ```{r, results='asis'}
    #output div
    cat("<div id=\"tbl:iris\">")
    
    iris.t <-
      iris[1:5,] %>%
      regulartable() %>% 
      style(pr_c = officer::fp_cell(vertical.align = "bottom",
                                    border.bottom = officer::fp_border(width = 2)), part = "header") %>% 
      rotate(j = names(iris)[-c(1:2)],
             rotation = "tbrl", part = "header", align = "bottom") %>% 
      height(height = max(dim_pretty(.,  part = "header")$widths), part = "header") %>% 
      width(width = c(dim_pretty(. ,part = "all")$widths[c(1:2)],
                      dim_pretty(. ,part = "body")$widths[-c(1:2)]))
    iris.t
    
    #Output Caption
    cat("\nIris table caption.\n")
    # Output </div>
    cat("</div>")

**Comment by lierdakil** [comment]
I'm not familiar with RMD myself, but if it's Pandoc Markdown on the top level, I would expect you could simplify the table part to
``````markdown
::: {#tbl:iris}
```{r, results='asis'}
iris.t <-
  iris[1:5,] %>%
  regulartable() %>% 
  style(pr_c = officer::fp_cell(vertical.align = "bottom",
                                border.bottom = officer::fp_border(width = 2)), part = "header") %>% 
  rotate(j = names(iris)[-c(1:2)],
         rotation = "tbrl", part = "header", align = "bottom") %>% 
  height(height = max(dim_pretty(.,  part = "header")$widths), part = "header") %>% 
  width(width = c(dim_pretty(. ,part = "all")$widths[c(1:2)],
                  dim_pretty(. ,part = "body")$widths[-c(1:2)]))
iris.t
```

Iris table caption.
:::
``````

**Comment by HJAllen** [comment]
Your last suggestion was not successful. Didn't really dig into it as the above solution is good enough for me.

**Comment by HJAllen** [comment]
It has been a while but trying to reuse the code snippet above to reference a div wrapped table but it is currently broken. Any idea why this may be?
Thanks.

**Comment by lierdakil** [comment]
No idea, since you didn't specify what is "broken" exactly. Remember, I don't use R.

In case you've updated pandoc recently, the last v0.4.0.0 prerelease (alpha6d) is not compatible with pandoc v2.10.x. In that case, you might try a more recent build https://bintray.com/lierdakil/pandoc-crossref/any-prefix/40a8b12efce01cf46ff385875cf2d49e3cae6a91#files

**Comment by lierdakil** [comment]
Right. So, looking at the previous discussion here, I believe we established that pandoc-crossref 0.3.x doesn't really handle this, it really wants to see a table being referenced as `tbl:*` and doesn't recognize raw ooxml block as a table. Not a surprise that pandoc-crossref 0.3.8.1 doesn't handle this case.

Try getting the latest prerelease build of v0.4.0.0 (find it [here](https://bintray.com/lierdakil/pandoc-crossref/any-prefix/40a8b12efce01cf46ff385875cf2d49e3cae6a91#files)), that should (hopefully) work. Or checkout the top of any-prefix branch on this repo if you want to build from source.

If you're not keen on using prerelease software, we can return to the idea of referencing arbitrary `div`s with current mainline release, but I can't promise I will implement anything in v0.3.x in a timely fashion.

**Comment by HJAllen** [comment]
Aha, yes it had been so long I forgot about your comment re v0.4 and missed it this time. I will try again. Thanks!
