### ISSUE TITLE
v0.3.2.0 Windows build

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#176]
Maybe now after 21 days passed appveyor would work?

**Comment by lierdakil** [comment]
Doubt it, doesn't seem like any progress has been made on related issues https://github.com/commercialhaskell/stackage/issues/3385 https://github.com/commercialhaskell/stack/issues/3944

**Comment by lierdakil** [comment]
Nope, no change at all: https://ci.appveyor.com/project/lierdakil/pandoc-crossref/build/1.0.288
