### ISSUE TITLE
Using pandoc-crossref without Haskell platform

### ISSUE THREAD

**Issue by asaf050** [lierdakil/pandoc-crossref#177]
Hello,
Is it possible to use pandoc-crossref without installing Haskell platform?
I don't want to install 700MB software just to install pandoc-crossref.

Thanks
Asaf

**Comment by lierdakil** [comment]
Precompiled binaries are available at the [GitHub releases page](https://github.com/lierdakil/pandoc-crossref/releases). Those should "just work" in most cases, provided Pandoc is installed and pandoc-crossref is invoked as a filter. The only caveat is those are tied to Pandoc's version, so using pandoc-crossref built for one Pandoc version with another may fail.

**Comment by asaf050** [comment]
Thanks!
