### ISSUE TITLE
code listings does not use titleDelimiter

### ISSUE THREAD

**Issue by arve0** [lierdakil/pandoc-crossref#18]
Seems like `titleDelimiter` is not added to the code listings.

**Comment by lierdakil** [comment]
It should work in all formats except LaTeX. Translating pandoc-crossref templates to LaTeX proved to be a very daunting task, so I opted to leave it out for now. Right now, only `*Title` and `*Prefix` affect LaTeX output.
You can, however, use `-M header-includes=...` and `-M include-before=...` to customize LaTeX output with, well, LaTeX commands.

**Comment by arve0** [comment]
Ok, thanks. Than this is a no-fix.
