### ISSUE TITLE
Page numbers for printable PDFs?

### ISSUE THREAD

**Issue by rauschma** [lierdakil/pandoc-crossref#186]
Use case: Given the following input.

```
For more information, consult [the chapter on Unicode](#cha:unicode).
```

I’d like to create two PDFs:

* First, a printable one, with page numbers.

  > For more information, consult the chapter on Unicode (page 123).

* Second, a PDF for reading on electronic devices – with links (same: HTML, EPUB, MOBI).

  > For more information, consult **the chapter on Unicode**.

  Legend: bold = clickable link

Any ideas or comments on this idea?

**Comment by lierdakil** [comment]
Page numbers can only realistically be a thing with LaTeX. So the best I can recommend is using LaTeX really. Cleveref package is rather nice to use.

If you don't want/can't use LaTeX, this particular idea can be reduced to a relatively simple filter, more or less like this (top of my head, untested):
```haskell
myfilter (Link _ text (url, _) : xs)
  | '#':ref <- url = text <> RawInline (Format "latex") ("\pageref{" <> ref <> "}") <> xs
myfilter xs = xs
```

**Comment by lierdakil** [comment]
Actually, here's a gist with working code: https://gist.github.com/lierdakil/c1bd46e057e886a6c39ef58d5b47e4e9

**Comment by lierdakil** [comment]
Right... Pandoc 2.0 comes with a built-in Lua interpreter. Note to self: might be a good idea to look into building a Haskell interpreter into Pandoc too.

Anyway, here's a Lua version:
```lua
function Link(el)
    if string.sub(el.target, 1, 1) == "#" then
        local ref = string.sub(el.target, 2)
        return (
           el.content .. {
           pandoc.Space(),
           pandoc.Str("(page"),
           pandoc.Space(),
           pandoc.RawInline("latex", "\\pageref{" .. ref .. "}"),
           pandoc.Str(")")
           }
        )
    else
        return el
    end
end
```
(remember that Lua filters should be run with `--lua-filter` commandline option)

**Comment by rauschma** [comment]
Cool, thanks! It’s amazing how versatile Pandoc is. With my current setup I now get: PDF (screen), PDF (print), EPUB, MOBI, website (I post-process and split Pandoc’s HTML output – this is possibly Pandoc’s only real weak spot).
