### ISSUE TITLE
changing prefixes does not work with 0.4

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#190]
Changing prefixes of references (i. e. by `figPrefix: Abb.`) does not work with latest version 0.4.0.0-alpha2; v0.3.2.1 works out of the box.
If cleveref is used, crefnames are set to the english defaults. It looks like the prefix variables are not in use anymore.

I also noticed empty renewcommands:

```latex
\AtBeginDocument{%
\renewcommand*\figurename{Abbildung}
\renewcommand*\tablename{}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{}
\renewcommand*\listtablename{}
}
```

instead of:
```latex
\AtBeginDocument{%
\renewcommand*\figurename{Abbildung}
\renewcommand*\tablename{Table}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{List of Figures}
\renewcommand*\listtablename{List of Tables}
}
```

**Comment by lierdakil** [comment]
The format changed. See https://github.com/lierdakil/pandoc-crossref/pull/174 for details. Sorry, not much in terms of documentation yet.

**Comment by lierdakil** [comment]
I'll investigate the empty renew commands, that's likely a bug.
