### ISSUE TITLE
Fails to install on Windows 10 - Black screen

### ISSUE THREAD

**Issue by LeonStaufer** [lierdakil/pandoc-crossref#194]
Apologies if this is a silly question because I am missing something, but when I run the windows executable it remains at an empty black cmd window. 

I've tried this with both v0.3.1.0, and v0.3.2.1. I've also tried running the executable with administrator privileges, but this has not helped.

Any help is appreciated.

**Comment by tolot27** [comment]
Pandoc-crossref is a filter for pandoc (parameter `-F`) which accepts input (AST) from stdin. If you run it standalone you will not see anything, except if you use the parameter `--version`. Please read the manual.

**Comment by LeonStaufer** [comment]
Thank-you very much.

**Comment by LeonStaufer** [comment]
For future users it might also be helpful to know that the `pandoc-crossref.exe` needs to be in the same folder as pandoc (usually `C:\Users\USERNAME\AppData\Local\Pandoc\` on Windows) or specified when running pandoc with the filter, as shown below:

`pandoc --filter /path/to/filter`

More information can be found in the [Pandoc manual under the filters section](https://pandoc.org/MANUAL.html)
