### ISSUE TITLE
pandoc-crossref does not work with pandoc --listings 

### ISSUE THREAD

**Issue by sjackman** [lierdakil/pandoc-crossref#197]
```sh
❯❯❯ echo '`Hello, world!`' >hello.md
❯❯❯ pandoc --listings -Fpandoc-crossref -o hello.pdf hello.md
Error producing PDF.
! Undefined control sequence.
l.77 \passthrough
```

**Comment by sjackman** [comment]
Adding `codeBlockCaptions: True` to the YAML front-matter and removing `--listings` from the command line resolved my issue.

**Comment by lierdakil** [comment]
You need `-Mlistings` (or `listings: True` in metadata block) to let pandoc-crossref know you're using listings. This is mentioned in the manual.

**Comment by sjackman** [comment]
Found it here http://lierdakil.github.io/pandoc-crossref/#table-style-captions

> listings: if True, generate code blocks for listings package. Only relevant for LaTeX output. \usepackage{listings} will be automatically added to header-includes. You need to specify --listings option as well.

`You need to specify --listings option as well.`
This doesn't seem to be true. It works without `--listings`.

**Comment by sjackman** [comment]
You may wan to consider changing the linked URL of the GitHub page
from https://hackage.haskell.org/package/pandoc-crossref
to http://lierdakil.github.io/pandoc-crossref/
which is more useful.

**Comment by lierdakil** [comment]
> This doesn't seem to be true. It works without --listings.

Probably depends on Pandoc version, but having `-Mlistings` without `--listings` can lead to subtle breakage (since the latter actually affects how Pandoc's LaTeX renderer does stuff)

> You may wan to consider changing the linked URL

Sounds reasonable.

**Comment by sjackman** [comment]
Thanks for `pandoc-crossref`! It makes writing academic papers enjoyable. =)

**Comment by sjackman** [comment]
With `--listings -Mlistings -McodeBlockCaptions` the code is syntax highlighted but without colour, and the spacing between letters and punctuation is weird and not right.
Without `--listings -Mlistings` and with `codeBlockCaptions` everything works as expected.

**Comment by lierdakil** [comment]
> the code is syntax highlighted but without colour, and the spacing between letters and punctuation is weird and not right.

Well, I don't know what you mean by "weird and not right" exactly, but the "without colour" part is precisely what one would expect with LaTeX `listings` package. In fact, if you look at raw LaTeX, Pandoc doesn't even attempt highlighting the code with `--listings` enabled, offloading the task to LaTeX instead:
``````
$ cat test.md
```cpp
#include <stdio.h>
int main() {
    printf("Hello, world!\n");
    return 0;
}
```

$ pandoc -t latex test.md
\begin{Shaded}
\begin{Highlighting}[]
\PreprocessorTok{#include }\ImportTok{<stdio.h>}
\DataTypeTok{int}\NormalTok{ main() \{}
\NormalTok{    printf(}\StringTok{"Hello, world!}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{);}
    \ControlFlowTok{return} \DecValTok{0}\NormalTok{;}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

$ pandoc -t latex --listings test.md
\begin{lstlisting}[language={C++}]
#include <stdio.h>
int main() {
    printf("Hello, world!\n");
    return 0;
}
\end{lstlisting}
``````

Hope that makes sense.

**Comment by sdbbs** [comment]
Just noting my experience: I have a pandoc.yaml with these contents:

```yaml
# ...
listings: true
filters:
- ${.}/../scripts/pandoc/my_script.lua
- pandoc-crossref
- citeproc
# ...
metadata:
  link-citations: true
# ...
  header-includes: |
# ...
    \lstset{% for listings
      basicstyle=\ttfamily,
      breaklines=true,
    }
# ...
```

.... and in my test.md file something like:

```html
<!-- ... -->
See figure [@fig:my_figure].

![This is my figure](my_figure.png){ #fig:my_figure }
<!-- ... -->
```

With this, it turns out I *have* to use `-Mlistings` on the command line, else for some reason, if I enable `pandoc-crossref` under `filters`, then `\lstset` becomes undefined (?!):

```none
$ pandoc --defaults=pandoc.yaml --pdf-engine-opt=-shell-escape --toc test.md -o test.pdf
Error producing PDF.
! Undefined control sequence.
l.96 \lstset

$ pandoc --defaults=pandoc.yaml --pdf-engine-opt=-shell-escape --listings --toc test.md -o test.pdf
Error producing PDF.
! Undefined control sequence.
l.96 \lstset

$ pandoc --defaults=pandoc.yaml --pdf-engine-opt=-shell-escape -Mlistings --listings --toc test.md -o test.pdf

$ pandoc --defaults=pandoc.yaml --pdf-engine-opt=-shell-escape -Mlistings --toc test.md -o test.pdf

```

Is there any option I can set in the .yaml file, so I get the same effect as `-Mlistings` on the command line, without having to use `-Mlistings` on the command line?
