### ISSUE TITLE
Links in Listings Caption in LaTeX

### ISSUE THREAD

**Issue by thomasWeise** [lierdakil/pandoc-crossref#198]
First of all, thank you for your great package!
It makes my life much much easier.

Today, I think I came across some problem with links in listings captions.
Most likely, I am doing something wrong, however, so it might be that the error is on my side entirely.

What I want to do is to link the included listings to source codes online.
What I do is something like

    ```{#lst.ref .java caption="blabla blabla. [src](http://www.github.com/thomasWeise/blabla/blob/master/file.java)"}
    class xyz {
    ...
    }
    ```

An what I would like to get was that the caption is something like `Listing 1.1: blabla blabla. src`, where `src` is a hyperlink written as `src` and pointing to url http://www.github.com/thomasWeise/blabla/blob/master/file.java.

But what I seemingly get when producing the pdf via pdflatex is something like 

`Listing 1.1: (http://www.github.com/thomasWeise/blabla/blob/master/file.java)]blabla blabla.
[src](http://www.github.com/thomasWeise/blabla/blob/master/file.java)`

where the whole caption is a hyperlink.

I am using pandoc-crossref together with the LaTeX listings package option set both in the metadata and the command line of pandoc.
I am using chapter-numbered listings.

Am I doing something wrong? Do I maybe need some special escaping or something?
Or are links in captions not supported?

Anyway, thank you very much for your great work.

**Comment by lierdakil** [comment]
Long story short, `caption` attribute on code block is a LaTeX string, not Markdown. You can use LaTeX commands directly. Something to the tune of `\href{https://github.com/...}{src}` should work.

You can, however, get Markdown support in captions if you *don't* use listings package. See https://lierdakil.github.io/pandoc-crossref/#table-style-captions

**Comment by thomasWeise** [comment]
Hi.
I see.
But what will happen with the LaTeX strings if I export to epub?
Will they be converted?
Otherwise I will simply switch to preprocessing without listings.
Thanks.

**Comment by thomasWeise** [comment]
I just tested it without listings support, and then it seemingly renders to something like

`Listing 1.1: blabla blabla. [src](http://www.github.com/thomasWeise/blabla/blob/master/file.java)`

In other words, the plain text remains and is not reduced to just `src`.

Is there any way in which I can get this to work?

Sorry for the trouble.
Thomas.

**Comment by thomasWeise** [comment]
A, thanks, now I see it.
I have to do both
1. not use the listings package and
2. use table-style captions

...now it works as wanted, thanks, great :-)
