### ISSUE TITLE
support numbering by chapters

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#2]
If the parameter `--chapters` is given to pandoc, all crossref numbers should be prefixed with the chapter number and restarted at 1 for each chapter.

Currently, they will be simply incremented across the whole document.

**Comment by lierdakil** [comment]
This is tough actually, so it might take a bit of time to implement.

**Comment by lierdakil** [comment]
So... it's not really possible to determine if `--chapters` was passed to pandoc from within filter. Metadata flag will have to do for this, I fear.

**Comment by tolot27** [comment]
Okay, a metadata flag would be a good workaround.

For Latex output it should be solved intrinsically and for PDF output too, if #4 is addressed.

**Comment by lierdakil** [comment]
Initial support implemented by bf56ae5f176c36be137aabce2682a3cdedccbf28, but I'll leave this open for any feedback on issue, if any.

**Comment by tolot27** [comment]
Works great! Many thanks!

**Comment by baig** [comment]
Is it possible to specify chapter number with `-M chapters` option?

**Comment by lierdakil** [comment]
@baig, not at the moment, no. Please open new issue with detailed description of semantics you require, and I will try to implement something.
