### ISSUE TITLE
Customize prefix globally

### ISSUE THREAD

**Issue by zwz** [lierdakil/pandoc-crossref#206]
I read the document, pandoc-crossref supports custom prefix per reference by [myprefix @somekey].

It works but a little tedious for some people speaking some language.
Take Chinese as an example, we use '图' for figure(s).

So we set `figureTitle` to '图'. And we definitely want every reference to a figure `[@fig:any]` should results in `图~\ref{fig:any}`.

IMHO, `figureTitle` is a good option to customize figure prefix globally. In cases it does not meet the requirement, we can still fall back to the per-reference way.

**Comment by lierdakil** [comment]
See http://lierdakil.github.io/pandoc-crossref/#reference-format
TL;DR you want `figPrefix` metadata setting.

**Comment by zwz** [comment]
OMG, how could I miss that.
Forgive my carelessness, and thank you.
