### ISSUE TITLE
crossref more types

### ISSUE THREAD

**Issue by zwz** [lierdakil/pandoc-crossref#207]
For scholar papers, it is common to crossref theorems, algorithms(pseudo-code) and etc..

I was wondering if it is possible for pandoc-crossref to deal with those stuff.

What I thought is to distinguish them by 'fenced_code_attributes', like
````
```{#theorem:xxx}
this is theorem
```
````
````
```{#algorithm:xxx}
this is pseudo-code
```
````
and
````
```{#lst:xxx}
this is code
```
````
And pandoc-crossref handles them accordingly.

**Comment by lierdakil** [comment]
Something like this is being worked on in https://github.com/lierdakil/pandoc-crossref/pull/174. I sadly don't currently have time to finish it, so there are a still few things to be done and I'm pretty sure there are some occasional bugs, but you're very welcome to test it and provide feedback if you want to.

Notice that contains major changes to metadata config format, and LaTeX support is somewhat stifled at the moment.

**Comment by lierdakil** [comment]
Closing in favour of #84
