### ISSUE TITLE
listingTitle is showing incorrectly as lolTitle

### ISSUE THREAD

**Issue by kohenkatz** [lierdakil/pandoc-crossref#211]
When I insert code listings with captions, the captions are prefixed with "List of Listings #" instead of "Listing #".

Example Markdown source:

    This paragraph has a @lst:example reference.
    
    ```{lst:example}
    // Example code is here
    ```

    Listing: Example code listing

---

I expect the caption to show up as:

    Listing 1. Example code listing

Instead, it shows up as:

    List of Listings 1. Example code listing

---

Note that this is with only `codeBlockCaptions: true` set in YAML but without `listings: true` and `--listings` (on the command line) because I like the default style and don't need the `listings` package.

---

If I generate a `.tex` file as output (instead of a PDF), I see that it contains the following definition:

```
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{List of Listings}
```

As far as I can tell, this comes from [here](https://github.com/lierdakil/pandoc-crossref/blob/c3d7d6a87fa81d44a41e8bd0d89e8b18ada6f625/lib/Text/Pandoc/CrossRef/Util/ModifyMeta.hs#L79-L82). The code there is clearly referring to `listingTitle` -- which should be `Listing`, not to `lolTitle`, but it seems that `lolTitle` is actually what was output.

I tried to set `listingTitle` in my YAML, but that didn't seem to help.

Any idea why that is happening?

**Comment by lierdakil** [comment]
Which version are you using? That is, what is the exact output of
`pandoc-crossref --version`? Also, for reference, what is the output of
`pandoc --version`? I might've just messed up somewhere in the
v0.4.0.0-alpha (which is alpha for a reason).

пн, 7 янв. 2019 г. в 06:58, MK <notifications@github.com>:

**Comment by kohenkatz** [comment]
Yes, it is the alpha version:

```
PS C:\Users\moshe> pandoc-crossref --version
pandoc-crossref v0.4.0.0 git commit 508487f68f39fec7fe10dcc8d6b593c463e68684 (HEAD) built with Pandoc v2.4, pandoc-types v1.17.5.4 and GHC 8.6.2
```

Pandoc version:

```
PS C:\Users\moshe> pandoc --version
pandoc.exe 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
Default user data directory: C:\Users\moshe\AppData\Roaming\pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I'm guessing that means the issue is here: https://github.com/lierdakil/pandoc-crossref/commit/508487f68f39fec7fe10dcc8d6b593c463e68684#diff-37a3db528809639287b899d0fc58e302R84

**Comment by kohenkatz** [comment]
I have confirmed that it works correctly in v0.3.4.0

**Comment by lierdakil** [comment]
Thanks for reporting and investigating! Sorry for the hold-up, was very busy with day job. [v0.4.0.0-alpha4](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.4.0.0-alpha4) should have this fixed. Binaries will most likely appear there in a couple hours (builds can be slow).
