### ISSUE TITLE
support secPostfix

### ISSUE THREAD

**Issue by KageShiron** [lierdakil/pandoc-crossref#212]
# feature request
I want to use postfix for section's ref

```markdown
# Sample
## sample1 {#sec:sec1}
This is a sample.

## prefix (supporting)
[@sec:sec1] is a sample1.

## postfix (not supporting)
[-@sec:sec1] sec is a sample.
```

![image](https://user-images.githubusercontent.com/17571233/51015186-92a09100-15ae-11e9-823f-1d67d10e03a1.png)

## why?
In Japanese, postfix is more often used than prefix for section.

👎  節1.1
👍  1.1節

(節=section)

**Comment by lierdakil** [comment]
You can use [templates](http://lierdakil.github.io/pandoc-crossref/#templates), in particular `secPrefixTemplate` (or in v0.4.0.0 use `referenceTemplate` under the `sec` prefix). Notice that *reference* templates (i.e. `xxxPrefixTemplate`) should work in LaTeX with `cref: false`, despite what is written in the documentation (I should probably fix that). TL;DR: on v0.3, set `secPrefixTemplate: $$i$$$$p$$`, in v0.4 it's a bit more wordy: `prefixes: sec: referenceTemplate: $$i$$$$p$$`

With LaTeX and `cref: true`, I suggest using `\crefformat` command to specify the reference format. For more information, please see [cleveref documentation](http://mirrors.ctan.org/macros/latex/contrib/cleveref/cleveref.pdf) (in particular sec. 8.2.1)

**Comment by KageShiron** [comment]
Thanks! Templates works well.

```yaml
# pandoc-crossref v0.3.4.0b
secPrefix: "節"
secPrefixTemplate: $$i$$$$p$$
```
