### ISSUE TITLE
will v0.3.4.0 work with Pandoc 2.5?

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#213]

**Comment by kiwi0fruit** [comment]
thanks!

**Comment by lierdakil** [comment]
I've relaxed version constraints on Hackage, so you can build pandoc-crossref v0.3.4.0 against pandoc v2.5 yourself if you so choose (without manual tweaking).

Also, new github releases will likely be built in a few hours: https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.4.0a and https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.4.0.0-alpha4a

**Comment by kiwi0fruit** [comment]
Great! Is there a reason why Windows build is not present?

**Comment by lierdakil** [comment]
AppVeyor is being difficult. I might try building those manually if it doesn't cooperate eventually.

**Comment by kiwi0fruit** [comment]
@lierdakil At the moment I try to create a conda package to pandoc-crossref: https://github.com/conda-forge/staged-recipes/pull/7614

It gives an error:

`pandoc-crossref: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by pandoc-crossref)`

So I guess pandoc-crossref on linux is built against some particular version of glibc? So it won't work on all versions of OSes? But the same time compiled pandoc executables from github do not give such an error. What's the difference?

**Comment by kiwi0fruit** [comment]
Something like that happen on macOS:
```
dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
```
But compiled pandoc from github works at this time...

Is there an easy way to tweak you build tools so that they compile the same ways as pandoc does? I could try to dig it myself but I need a hook to tweak (if it's possible).

**Comment by lierdakil** [comment]
Pandoc team apparently uses their own infrastructure for builds. I don't have that kind of resources really, so I'm using Travis' and AppVeyor's infrastructure. So I'm kinda limited by what I can do on those.

On Linux, Travis uses Ubuntu trusty for its base images -- so binary compatibility is limited to whatever is binary-compatible with that. In theory, it's possible to link statically against non-glibc libc implementation (building statically against glibc will still have version mismatch issues), and it might perhaps even be viable with docker, but I couldn't set this up quickly if my life depended on it, and I don't have much time to play with this atm.

As for OSX, I honestly have no idea. Pretty sure it worked at one point, but whether something's changed I couldn't say -- don't have a Mac handy to test on. Insight is welcome. Probably the easiest way to "hook in" would be to fork, change `.travis.yml` in the root of the repo to upload build artifacts to some file store on the 'net with curl, and create a PR. Or you could probably set-up your own slice of Travis for testing. Sorry can't help out more with the set-up, again, not much spare time right now.

**Comment by lierdakil** [comment]
This GHC issue might be relevant: https://ghc.haskell.org/trac/ghc/ticket/15404

**Comment by kiwi0fruit** [comment]
@lierdakil Wait. It'ss not the first simple way. The first simple way is to go with pandoc-fignos, pandoc-eqnos and pandoc-tablenos.

So I'll first try this.

**Comment by kiwi0fruit** [comment]
But I guess pandoc-crossref is preferable though...

**Comment by jgm** [comment]
> Pandoc team apparently uses their own infrastructure for builds.

@lierdakil No, pandoc uses appveyor for its Windows builds, so you should be able to borrow from our build script...

**Comment by lierdakil** [comment]
@jgm, Windows is the least of my worries right now -- that I have easy access to. MacOS is much more of an issue.

**Comment by jgm** [comment]
Nikolay Yakimov <notifications@github.com> writes:

> @jgm, Windows is the least of my worries right now -- that I have easy access to. MacOS is much more of an issue.

Ah.  I do use my own mac to create packages.
However, I see that travis offers macOS builds --
maybe that's what you're using?

**Comment by lierdakil** [comment]
> However, I see that travis offers macOS builds -- maybe that's what you're using?

Exactly. But I have no real way to troubleshoot (or frankly even test) the builds. And apparently something is rotten in the state of Denmark, since [reportedly](https://github.com/lierdakil/pandoc-crossref/issues/213#issuecomment-456007340) MacOS builds say this:
> dyld: Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib

**Comment by mb21** [comment]
@kiwi0fruit I would recommend you to build pandoc-crossref on your local machine using [stack](https://www.haskellstack.org/), it's just a build tool like any other and you don't need to know Haskell:

    git clone git@github.com:lierdakil/pandoc-crossref.git
    stack install

**Comment by kiwi0fruit** [comment]
@mb21 Thanks. Now I need scripts for downloading and installing stack on mac and on windows. Then compiling. I guess I could make it work on conda-forge...
But I still have no idea what to do about linux build. [Dockerfile](https://github.com/jgm/pandoc/blob/master/linux/Dockerfile) says that Pandoc uses Alpine Linux:

> It uses a hardened kernel and compiles all user space binaries as position-independent executables with stack-smashing protection

Sounds good. But how to even start setting it up online?

**Comment by kiwi0fruit** [comment]
> (or frankly even test) the builds

Now all three OSes testing could be made here: https://github.com/conda-forge/staged-recipes/pull/7614

On Ubuntu 14.04.5 LTS it gives: pandoc-crossref: /lib64/libc.so.6: version `GLIBC_2.14' not found

But it happens due to special conda requirements: the right way there is to compile against conda binaries. Or compile a fully independent build. For example Pandoc binaries are OK on the same Ubuntu 14.04.5 LTS tests.

**Comment by lierdakil** [comment]
linux-ghc84-pandoc25-static.tar.gz is a freshly-added statically-linked binary. The difference in size is because I've packed the binary with [upx](https://upx.github.io/) -- otherwise the binary size is just stupid.

**Comment by kiwi0fruit** [comment]
Nevermind. I can get it myself :)

**Comment by lierdakil** [comment]
```
$ sha256sum linux-ghc84-pandoc25-static.tar.gz 
346690db6438ea42ff6fa5ca3576ccdd9c0a05b86c1139600694d3723f5c870e  linux-ghc84-pandoc25-static.tar.gz

$ sha256sum pandoc-crossref 
3ed60b20c127176fca504cac24ef196afc4a1c5b58abddda3d05c9a4671cc5f6  pandoc-crossref
```
notice that `linux-ghc84-pandoc25-static.tar.gz` does *not* contain the man page (`pandoc-crossref.1`)

**Comment by kiwi0fruit** [comment]
Thanks! I've already noticed it's absence :)

**Comment by kiwi0fruit** [comment]
Static build works fine on Linux. So everything is almost nice.

Windows 0.3.4.0 works. But 0.3.4.0a wasn't compiled.

**Comment by kiwi0fruit** [comment]
Am I right that Windows build failed because of the:

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by kiwi0fruit** [comment]
If so could you please provide me with build script so I could build it on Windows?

**Comment by kiwi0fruit** [comment]
Or maybe the installation instructions from main README.md are enough?

**Comment by jgm** [comment]
Nikolay Yakimov <notifications@github.com> writes:

> linux-ghc84-pandoc25-static.tar.gz is a freshly-added statically-linked binary. The difference in size is because I've packed the binary with [upx](https://upx.github.io/) -- otherwise the binary size is just stupid.

Doesn't this entail a fairly significant delay in
unpacking when you use the binary?  That's what I
found when I tried upx for pandoc.

**Comment by lierdakil** [comment]
> Doesn't this entail a fairly significant delay in unpacking when you use the binary?

Sure, but that's about a couple hundred milliseconds of overhead tops, in my tests, which is IMO completely reasonable.

**Comment by kiwi0fruit** [comment]
I tried to install pandoc-crossref via:
```
cabal update
mkdir pandoc-crossref
cd pandoc-crossref
cabal sandbox init
cabal install pandoc-crossref
```

and got handed bash on windows (one of the packages asked for bash):

```Downloading  skylighting-0.7.5
Downloaded   skylighting-0.7.5
Starting     skylighting-0.7.5
Building     texmath-0.11.1.2
Building     skylighting-0.7.5
Completed    skylighting-0.7.5
Completed    texmath-0.11.1.2
Downloading  pandoc-2.5
Downloaded   pandoc-2.5
Starting     pandoc-2.5
Building     pandoc-2.5
Completed    pandoc-2.5
```
it's the same what you got on appveyor on your windows build.

**Comment by kiwi0fruit** [comment]
though GHC.exe still does something with single core.

**Comment by lierdakil** [comment]
GHC apparently hangs on some TH in data-accessor-template with GHC 8.6.3. GHC 8.4.4 seems to work though.

**Comment by kiwi0fruit** [comment]
how can I compile with CHC 8.4.4 on WIndows?

**Comment by kiwi0fruit** [comment]
Oh... If you know what's wrong then you can compile in appveyor yourself.

**Comment by lierdakil** [comment]
Already did. Just uploaded the build https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.4.0a

**Comment by kiwi0fruit** [comment]
@lierdakil pandoc-crossref was added to conda:

* https://anaconda.org/conda-forge/pandoc-crossref
* https://github.com/conda-forge/pandoc-crossref-feedstock

can be installed via:

    conda install -c conda-forge pandoc-crossref
