### ISSUE TITLE
Request for build against Pandoc 2.6

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#217]

**Comment by diallobakary4** [comment]
Pandoc 2.6 supports Jupiter notebooks. If build with Pandoc 2.6, then it will be possible to output notebook as a pdf with cross-refs.

**Comment by lierdakil** [comment]
Thanks for the heads-up. https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.4.0c

**Comment by kiwi0fruit** [comment]
Thanks!
