### ISSUE TITLE
Crossref along citeproc: Multiple references.

### ISSUE THREAD

**Issue by Pierre-Stir** [lierdakil/pandoc-crossref#22]
FIrst of all, thanks for creating such filter, it was something I was looking for for a long time. 

I am having issues running crossref along citeproc. The problem is that once crossref has run, it splits my in text references from 

```
[@Dean1998a; @Verpoorter2014]
```

to 

```
[@Dean1998a], [@Verpoorter2014]
```

Making it so that I can't have my in text references as "(Dean and Gorham, 1998; Verpoorter et al., 2014)" but as (Dean and Gorham, 1998), (Verpoorter et al., 2014).

Is there anyway that this can be fixed?

Cheers!

**Comment by lierdakil** [comment]
Hm. This is unintended. I will see what I can do.

**Comment by Pierre-Stir** [comment]
Thank you, I look forward to hearing from you!

**Comment by lierdakil** [comment]
Okay, I've put a pre-release 0.1.2.1 on hackage. You can install it with
`cabal install http://hackage.haskell.org/package/pandoc-crossref-0.1.2.1/candidate/pandoc-crossref-0.1.2.1.tar.gz`

I will properly release it when (if) all tests pass in Travis. Should be fine though.

**Comment by lierdakil** [comment]
Published
