### ISSUE TITLE
Unnumbered section numbering for \listoffigures, \listoftables and listoflistings

### ISSUE THREAD

**Issue by samueldodson** [lierdakil/pandoc-crossref#220]
Hi @lierdakil,

I am writing a markdown document with the pandoc `number-sections` option turned on. Is it possible to unnumber the headings created with the `\listoffigures`, `\listoftables` and `\listoflistings` LaTeX commands?

For example, when I use these commands, I get:

> 1. List of Figures
> 2. List of Tables
> 3. List of Listings

...but I would like these headings to be unnumbered. I know pandoc supports unnumbered headings with the `{-}` and `{.unnumbered}` commands, and am curious if pandoc-crossref has a similar workaround?

Thanks.

**Comment by lierdakil** [comment]
You can override titles of lists using `lofTitle`, `lolTitle`, `lotTitle` metadata attributes. Those are parsed as Markdown, so you can add the `.unnumbered` class there. F.ex.
```yaml
lofTitle: |
  # List of Figures {-}
```
