### ISSUE TITLE
Double periods after subfigure caption

### ISSUE THREAD

**Issue by slochower** [lierdakil/pandoc-crossref#225]
I'm getting double periods after my subfigure caption. The screenshot below has some extra styling applied, but this still happens when I go straight from Markdown to HTML5 via:

```
/usr/local/bin/pandoc --verbose \
  --from=markdown \
  --to=html5 \
  --filter=pandoc-crossref \
  --metadata-file=pandoc-crossref.yaml \
  --output=output/manuscript.html \
  $INPUT_PATH
```
where `pandoc-crossref.yaml` contains:
```
---
figPrefix:
  - "Figure"
  - "Figures"

ccsLabelSep: ":&nbsp;"
---
```
I can see the period popping up if I look at the native AST with and without `pandoc-crossref`, but I don't know enough about the details to debug:
```
[...]
Space,Str "ammonium,",Space,Str "alcohol,",Space,Str "or",Space,Str "carboxylate,",Space,Str "respectively..",Space]]
```

- pandoc version 2.7.2
- pandoc-crossref version v0.3.4.0 git commit 9c61b7a14c2ac2f1e79dc79a22f23aecea78f5a9

![image](https://user-images.githubusercontent.com/5393995/56183988-6d685800-5fcd-11e9-861d-741b7977106c.png)
![image](https://user-images.githubusercontent.com/5393995/56184000-7527fc80-5fcd-11e9-9a87-c91e8070fa93.png)

**Comment by lierdakil** [comment]
Take a look at http://lierdakil.github.io/pandoc-crossref/#subfigure-templates, in particular the default value for `subfigureTemplate`, which is 
```
$$figureTitle$$ $$i$$$$titleDelim$$ $$t$$. $$ccs$$
-----------------------------------------^
here is the second period
```

You can redefine `subfigureTemplate` to remove it. The reason for its inclusion in the first place is the "subfigre caption collection" thing, that is, subfigure captions are moved into the parent figure caption, and period is used for separating the main capiton and subfigure captions. This is described here: http://lierdakil.github.io/pandoc-crossref/#subfigures

**Comment by slochower** [comment]
Ah, perfect! Fantastic. I should have looked more closely at the `subfigureTemplate`. Thanks.
