### ISSUE TITLE
alt text support

### ISSUE THREAD

**Issue by lavaner** [lierdakil/pandoc-crossref#227]
Since a large pandoc-markdown usually manage by divided to many small files, reference sometimes across files.

in that case preview render would raise a error about "Undefined cross-reference: xxxx",
so I was wondering if it is possible to support alt text when the cross-reference was not found?

something like 

```
@eq:label[alt label] 
```

if `#eq:label` was not found, the alt text "alt label" left.

**Comment by lierdakil** [comment]
Don't see the usefulness of this feature. Message about an undefined cross-reference is just a warning, the output is still produced. The undefined cross-reference itself is replaced by `**¿label?**` in the output, where `label` is the original label used (e.g. `fig:smth`). Having no warnings on undefined cross-references is not an option, and I don't see how having "alt text" would help things.

If your preview doesn't show the rendered document when it sees warnings, frankly, that's that preview's problem.

**Comment by lavaner** [comment]
OK, you are right, it's only a warning, and reasonable. preview's fault.

this issue should be closed
