### ISSUE TITLE
No release builds available for the latest version of Pandoc: 2.7.3

### ISSUE THREAD

**Issue by gijswijs** [lierdakil/pandoc-crossref#232]
Pandoc has a new release available, 2.7.3.

https://github.com/jgm/pandoc/releases/tag/2.7.3

**Comment by lierdakil** [comment]
Sorry for the hold-up. Done:

https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.4.1a

https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.4.0.0-alpha5a
