### ISSUE TITLE
Add space between subfigure

### ISSUE THREAD

**Issue by annProg** [lierdakil/pandoc-crossref#235]
Is there any way to add space between subfigures？

![image](https://user-images.githubusercontent.com/4145852/63670442-40477400-c80f-11e9-8d62-68e1cb13925d.png)

**Comment by lierdakil** [comment]
I can't really recall from the top of my head, and I don't have the ability to test right now, but I think adding a literal (or non-breakable) space between image elements in the source markdown might help a little bit. If that's not enough, then explicitly setting `width` attribute on both images to something like `40%` should work. See https://pandoc.org/MANUAL.html#extension-link_attributes for syntax.

**Comment by annProg** [comment]
Thanks. add `\ ` between image work. `width` attribute not work
```markdown
::: {#fig:subfig}
![](pi.pdf){width=10%}\ \ 
![](pi2.pdf){width=10%}

Sub Figure
:::


::: {#fig:subfig2}
![](pi.pdf){width=40%}
![](pi2.pdf){width=40%}

Sub Figure
:::
```


![image](https://user-images.githubusercontent.com/4145852/63749267-ab5f7c00-c8dd-11e9-84b7-42a4e7ff2fff.png)
