### ISSUE TITLE
Link and numbering for Equations, Figures and tables with docx format

### ISSUE THREAD

**Issue by ebranlard** [lierdakil/pandoc-crossref#236]
The issues of #105 and  #147 are also found for equations. Another issue is that the numbering is not automatic. 

I believe the main issue is that currently equations, figures and tables are referenced as standard "bookmarks", while Word defines by default the "Equation", "Figure" and "Table" bookmarks. 

Further, Word as an option to define sequence of increasing numbers as follows: `SEQ Equation \* ARABIC` . This is shown when pressing `ALT-F9` for instance. 

The equations generated by `pandoc-crossref` seem hardcoded, and won't update if the user add more equations to the Word document. 

I'm enclosing an example containing one equation, with an equation-bookmark definition and it's citation. 

I believe the key is having this `SEQ Equation \* ARABIC` in the xml file. I'm aware that this format is difficult to implement as you mentioned in other thread. 

This feature is much needed since otherwise the Word document cannot be modified. 

Thank you so much for your help.

[Test-Equation.docx](https://github.com/lierdakil/pandoc-crossref/files/3563080/Test-Equation.docx)

**Comment by lierdakil** [comment]
Sorry, this is a "won't fix". If you're targeting Word exclusively, you
might just use Word to begin with. Especially when you're planning on
modifying the Word document directly anyway.

If you have "difficult" coauthors who refuse to use anything but Word,
pandoc-crossref markers won't survive the round-trip through Word anyway,
so in any case, after going to Word, you'll be stuck with it, unless you
manage to negotiate some compromise.

At the end of the day, pandoc-crossref is arguably more powerful than Word
in terms of item numbering already, and there's room to grow still. Trying
to use Word primitives would unavoidably limit pandoc-crossref to what Word
supports natively, which, let's face it, is not that much. For the same
reason, the current alpha is not using LaTeX primitives either.

As for the rest, I'll see later if I'm missing something, but right now it
seems that you want autoEqnLabels, linkReferences and perhaps nameInLink
options. Consult the manual for details.

вс, 1 сент. 2019 г., 7:55 E. Branlard <notifications@github.com>:
