### ISSUE TITLE
why --pipe?

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#239]
> Running pandoc-crossref as a UNIX pipe implicitly, i.e.
pandoc -t json text.md | pandoc-crossref | pandoc -f json
is no longer supported. Use the --pipe (short -p is also supported) option, e.g.
pandoc -t json text.md | pandoc-crossref --pipe | pandoc -f json
>
>Running pandoc-crossref as a UNIX pipe with specified output format, i.e.
pandoc -t json text.md | pandoc-crossref html | pandoc -f json
is deprecated. Please use the --pipe (short -p is also supported) option, e.g.
pandoc -t json text.md | pandoc-crossref --pipe html | pandoc -f json

What's the reason for breaking backward compatibility and behaving in a different way as other pandoc filters?

**Comment by lierdakil** [comment]
So, basically two reasons. First, running `pandoc-crossref` on command line without arguments just basically awaits input from stdin, which can be confusing, and isn't at all useful. Now it can detect this and give some hopefully helpful hints. Second, pandoc-crossref finally checks if it's being run with the pandoc version it was built for, and issues a warning if it isn't. But it can't check for that in "pipe mode", hence the need for explicit switch. Well, actually, I could've made it implicit, but I'm a big proponent for "explicit > implicit", so there you have it.

It is a somewhat questionable point whether this is a big compatibility issue. The "proper" way to run pandoc filters is with `--filter` option, which works just like it used to. Very few people actually bother with using filters-as-pipes, most of those people, to my knowledge, being pandoc and filter developers.

**Comment by kiwi0fruit** [comment]
I thought that it can always check it by reading appropriate ast value. Is it not true?

**Comment by lierdakil** [comment]
Pandoc's version isn't in the AST. pandoc-types version is in json, but it's not the same as pandoc version, and it's already checked by pandoc's filter API.

**Comment by kiwi0fruit** [comment]
Actually I use it only in pipe way. Now I would need to create wrappers like

```
pandoc-crossref --pipe "$@"
```

in py-pandoc-crossref package (conda pandoc-crossref package would work in a new way and py-pandoc-crossref would implement a patch)... That's easy to fix but annoying nevertheless.

As I'm a big propenent of backward compatibility :)

**Comment by kiwi0fruit** [comment]
Oh. It's not that simple. Easier is to postpone conda pandoc-crossref package till I fix pandoctools CI issue someday (I don't want to post new pandoctools version until I fix it).

**Comment by lierdakil** [comment]
> Actually I use it only in pipe way. Now I would need to create wrappers like
> 
> ```
> pandoc-crossref --pipe "$@"
> ```

There is an alternative. If you're invoking `pandoc-crossref` programmatically, just tell it what pandoc version you're running and it'll assume it's being run by pandoc. That is,
```bash
env PANDOC_VERSION="2.8.0" pandoc-crossref $outfmt
```
will work. If `$outfmt` is not specified, it won't though, since pandoc always supplies the intended output format. You can set `PANDOC_VERSION` at any point before `pandoc-crossref` is invoked, as is with any environment variables.

**Comment by lierdakil** [comment]
Side note: all pandoc-crossref releases prior to 0.3.5.0 are completely incompatible with pandoc 2.8 (AST was updated). See #240 for instance.

**Comment by kiwi0fruit** [comment]
Oh, thanks! that would be a nice temporal fix.

чт, 28 нояб. 2019 г., 4:36 Nikolay Yakimov <notifications@github.com>:
