### ISSUE TITLE
table references in org-mode

### ISSUE THREAD

**Issue by michelk** [lierdakil/pandoc-crossref#241]
```org
See figure [-@fig:label]

#+CAPTION: Caption
#+LABEL: fig:label
file:tt.png

See table [-@tbl:label]

#+CAPTION: Caption
#+LABEL: tbl:label
| a   | b   | c   |
|-----+-----+-----|
| 1   | 2   | 3   |
| 4   | 5   | 6   |
```
Produces with `pandoc -F pandoc-crossref -F pandoc-citeproc -t txt`

```txt
See figure 1

![Figure 1: Caption](tt.png){#fig:label}

See table **¿tbl:label?**

  a   b   c
  --- --- ---
  1   2   3
  4   5   6

  : Caption
```

Any idea how to circumvent this?

cc @tarleb

**Comment by lierdakil** [comment]
Add Markdown-style label to table caption. Pandoc Markdown (and pandoc AST) doesn't have table labels, so pandoc-crossref has to extract those from the caption.

[Nikolay Yakimov - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=abnwi)	[abnwi]

On December 11, 2019 at 8:23 GMT, Michel Kuhlmann <notifications@github.com> wrote:

See figure [-@fig:label] #+CAPTION: Caption #+LABEL: fig:label file:tt.png See table [-@tbl:label] #+CAPTION: Caption #+LABEL: tbl:label | a | b | c | |-----+-----+-----| | 1 | 2 | 3 | | 4 | 5 | 6 |
Produces with pandoc -F pandoc-crossref -F pandoc-citeproc -t txt
See figure 1 ![Figure 1: Caption](tt.png){#fig:label} See table **¿tbl:label?** a b c --- --- --- 1 2 3 4 5 6 : Caption
Any idea how to circumvent this?

cc [@tarleb](https://github.com/tarleb)

**Comment by tarleb** [comment]
We could think about changing the org reader to wrap the table in a div which has the label as its ID. Or maybe add the label as an empty span to the caption. This would preserve the information in a way that would allow another filter to get it into a format processable by pandoc-crossref.

**Comment by lierdakil** [comment]
Actually, IIRC, pandoc-crossref should already recognize the div-wrapped table. In fact, internally that's pretty much how it stores table labels in the AST.

**Comment by tarleb** [comment]
Oh cool! That's very straight-forward then. @michelk, could you open an issue in the pandoc repo so we don't lose track of this?

**Comment by michelk** [comment]
Thanks.
