### ISSUE TITLE
UPX causes issues if running pandoc-crossref inside a chroot

### ISSUE THREAD

**Issue by seanlano** [lierdakil/pandoc-crossref#245]
It's not a bug with anything to do with `pandoc-crossref`, but I've just come across a problem with trying to run newer versions inside a Linux `chroot`. _(Why do I do this? It's part of a little project I've made: https://gitlab.com/md2x/md2pdf-webserver )_ 

After having setup a `chroot` quite a while ago, which works fine, I found that creating a new environment caused `pandoc-crossref` to crash (although not `pandoc` itself). After a bunch of digging and trying different builds, I came across [this note](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.4.0b): 

> Linux and MacOS binaries are packed with upx. ... If you don't like the overhead, and don't mind 40-megabyte binaries, you can unpack those manually with `upx -d pandoc-crossref`.

I tried `upx -d pandoc-crossref` with the `pandoc-crossref` binary inside my `chroot`, and voila! Everything now works as expected, with the latest versions (v0.3.6.1b and v2.9.1.1). 

I wanted to file this issue just in case anyone else came across this bizarrely specific situation and was wondering why. Something the way UPX works wants to read things from `/proc`, which would normally work fine but I don't have that mounted in my `chroot` environment and was hoping to not need to do a bind mount for it since that would then make Snap packaging very hard to do. 

Thanks @lierdakil for having good release notes! Otherwise I never would have figured this out.

**Comment by lierdakil** [comment]
Didn't know that upx needs access to `/proc` to work, but it makes sense in hindsight.

Anyway, I've added this information to the README, in case someone else stumbles upon this oddity. Thanks for the heads-up!
