### ISSUE TITLE
how to suppress caption for use in .Rmd file

### ISSUE THREAD

**Issue by atanasj** [lierdakil/pandoc-crossref#249]
I want to suppress the caption provided by `pandoc-crossref` in `.Rmd` files. I am wrapping plots in `div` as per below:

```r
::: {#fig:test2}


```{r sample-plot-test2, fig.cap=""}

###--------------------------------------------------
### Code for a nice plot
###--------------------------------------------------

df <- tibble(tea = rnorm(100),
biscuits = tea + rnorm(100, 0, 1.3),
chips = tea + rnorm(100,0,1.8),
cheese = tea + rnorm(100,0,1.5))

df %>%
   ggplot(aes(x = tea, y = biscuits)) +
   geom_smooth(method="lm") +
   labs(x = "Tea", y = "Biscuits") +
   theme_bw()

\```

Tea and Biscuits are correlated but there may be identifiability issues.
:::

```

However, it comes out like this:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/27214625/75497931-e15ef380-5a19-11ea-9c5d-5ccedbfda99d.png">

Where do I put the `nocaption` option?

**Comment by lierdakil** [comment]
Um... This isn't an option. Items that can be referenced need to have a caption, otherwise you would reference, e.g. "Figure 2", but there won't be anything labelled as "Figure 2" in the document.

So I'm not sure what you're trying to do here. Perhaps if you explain what exactly you want to accomplish, I might suggest a solution or a workaround.

**Comment by atanasj** [comment]
Sorry for my tardy reply. I want to be able to reference the figure that it is wrapped by the `pandoc-crossref` `div` tags so that I can insert links to the figure in `html`, `docx`, and `pdf`. 

The only way this is possible in `.Rmd` is by using the `bookdown` package, and I was hoping to use my same writing workflow (using your package) without introducing another dependency (`bookdown`). 

I'm not sure if that make sense or not. And in fact, I'm not even sure whether `pandoc-crossref` is creating the `(a)` label in the screenshot, or if it is `R`… I assumed it was `pandoc-crossref` because I though the `div` tags were meant for cross-referencing multiple images.

Am I write in my assumption that it is `pandoc-crossref` creating the `(a)` label? If not, then my question my be better directed somewhere else...

**Comment by lierdakil** [comment]
Ah, I see. Yes, right, if you're using v0.3.x of pandoc-crossref, the "image wrapped in a div" is interpreted as LaTeX's `subfigures` environment, and acts accordingly. Sorry I didn't understand your question the first time around.

So okay, if you don't actually need subfigures at all, you can suppress subfigure captions by setting `subfigureChildTemplate` metadata field to an empty string.

Other than that, you might try to give your R plots pandoc-crossref compatible identifiers, and that might just work without the wrapping div (I don't use R myself, so this is a poorly educated guess, but anyway):
``````
```{r fig:sample-plot-test2, fig.cap=""}
# Code goes here...
```
``````
