### ISSUE TITLE
2.9.2.1

### ISSUE THREAD

**Issue by blaggacao** [lierdakil/pandoc-crossref#251]
Looks like a new image is out: https://github.com/pandoc/dockerfiles/commit/ff2f4e3f850501657b324868b1f0b81fefa97551

Please update as for some reason 2.9.2 does produce something around those lines (for whatever reason): `/opt/texlive/texdir/bin/x86_64-linuxmusl/tlmgr: unexpected return value from verify_checksum: -5`

**Comment by lierdakil** [comment]
Done https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.6.2a

**Comment by blaggacao** [comment]
Thanks!
