### ISSUE TITLE
Release supporting 8.8

### ISSUE THREAD

**Issue by arrowd** [lierdakil/pandoc-crossref#255]
Hello. Is there any ETA on a release that'd support building with GHC 8.8? It looks like 0.4 is pretty far away, so maybe another point-release?

**Comment by lierdakil** [comment]
Ah, right. I've added ghc 8.8 support, but didn't release it, apparently. Well, the reasoning for that IIRC was that data-accessor-template on Hackage doesn't technically support GHC 8.8 (although it builds and seemingly works, version constraints are too tight), so I decided to hold off and wait until (if) it updates. It didn't update yet, so I just wrote to the maintainer, so let's wait for a bit and see. Meanwhile, you could try the master branch if you need pandoc-crossref built with GHC 8.8 ASAP.

**Comment by lierdakil** [comment]
Okay, data-accessor-template was updated (well, the constraints were relaxed on Hackage), so v0.3.6.2 should build with GHC 8.8 now. Publishing a new release is somewhat pointless, because it would only contain trivial changes.

**Comment by arrowd** [comment]
Indeed, it works now. Thanks for checking!
