### ISSUE TITLE
latex to markdown support?

### ISSUE THREAD

**Issue by ricopicone** [lierdakil/pandoc-crossref#257]
Great project! I'm converting my LaTeX `memoir` class documents over to Markdown to be used with pandoc+pandoc-crossref. I'm looking for advice on the conversion. The documents are book-size and include several subfiles and custom environments, so I haven't had good luck with `pandoc` ing the master files. And even when I `pandoc` subfiles individually, I lose the crossreferences. There's no chance pandoc-crossref has support for the reverse process: LaTeX to Markdown that preserves pandoc-crossref style cross-references?

Thanks for any advice!

**Comment by lierdakil** [comment]
Hi. There's no direct provision in pandoc-crossref for input formats besides Markdown, but some other input formats happen to work. Regrettably, LaTeX isn't really one of those.

That said, it's possible to _kind of_ make it work, see https://github.com/lierdakil/pandoc-crossref/issues/250#issuecomment-596109229 (and other messages in that thread for context). But it's not a silver bullet, so you'll likely have to do some manual tweaking.

**Comment by ricopicone** [comment]
Thanks @lierdakil I'm playing with your luatex filter and seeing promising results!
