### ISSUE TITLE
tblPrefix metadata not working

### ISSUE THREAD

**Issue by maxhaz** [lierdakil/pandoc-crossref#258]
I am transitioning from pandoc-fignos, pandoc-tablenosm and pandoc-eqnos filters (also very useful BTW).

 Trying to use the metadata tblPrefix, figPrefix, and eqnPrefix to change the default value, it is not working for me.

What is functioning is to replace the default with the per reference syntax `[newprefix @tbl:table1]`.

But either:
- adding the switch `-M "tblPrefix=newprefix"`
- adding `tblPrefix: "newprefix"` in the YAML front matter
- adding the switch `-M "crossrefYaml=pandoc-crossref.yaml"`

with the `demo.md` file does not work. 

Am I doing something wrong?
(using the version pandoc-crossref v0.4.0.0 )

**Comment by lierdakil** [comment]
Hi. v0.4.0.0 is still in alpha. I did not yet add provisions for common use-cases or update documentation. TL;DR: use the latest v0.3.x unless feeling particularly adventurous.

If you really want to try out v0.4, then you can change table prefixes using metadata like this:
```haskell
prefixes:
  tbl:
    ref:
    - 'prefix for signle item'
    - 'prefix for multiple items'
```

**Comment by maxhaz** [comment]
Ok, that makes sense. I had no idea that v0.4.0.0 was making such important change in the syntax.
Thanks!
