### ISSUE TITLE
No release builds with latest version of `pandoc`

### ISSUE THREAD

**Issue by magthe** [lierdakil/pandoc-crossref#26]
The dependency on `pandoc` has an upper limit of `< 1.15` and the latest version at the moment is 1.15.0.4.  Any chance of getting a new release soon?

**Comment by lierdakil** [comment]
Sure, I think I could relax constraints with no ill effects. I'll see if it's indeed possible, and publish a patch-release if it is.

**Comment by lierdakil** [comment]
Done.

**Comment by magthe** [comment]
Thanks!
