### ISSUE TITLE
README.md shouldn't point to an alpha release (only)

### ISSUE THREAD

**Issue by tonyo96** [lierdakil/pandoc-crossref#260]
Currently, the README.md points to `https://github.com/lierdakil/pandoc-crossref/releases/latest`

Which is a major alpha release (at the time of writing this), and the page shows nothing else (no stable release).

I think it should point to the latest non-alpha release, or all the releases: `https://github.com/lierdakil/pandoc-crossref/releases`

Why: I followed the link in the README.md, downloaded the only shown release (I even noticed it was alpha, but "whatever, I was linked to this, I've read the docs, I should be okay"), and then I spent an hour debugging (because I wasn't able to customize). After reading random issues in the repo I realized I shouldn't be using an alpha release because of the changed syntax. Of course, it's a very dumb mistake from my side, but I'm not the only one who got tricked by it #254

**Comment by lierdakil** [comment]
Sorry, this was an oversight on my part. Should be fixed now.
