### ISSUE TITLE
pandoc-crossref by pipe gives different result

### ISSUE THREAD

**Issue by gabyx** [lierdakil/pandoc-crossref#262]
```markdown
(see [@fig:figure1])
```
with
```shell
pandoc -s -f markdown -t json Test.md | pandoc-crossref --pipe latex | tee Test.json | pandoc -s -f json -t latex Test.tex
```

**Output: Test.json**
```json
"blocks": [
        { "t": "Para", "c": [{ "t": "Str", "c": "(see" }, { "t": "Space" }, { "t": "Str", "c": "fig. 1)" }] }
    ],
```

replaces the reference directly with `fig. 1`, why is that behavior different from (should be the same behavior according to pandoc)

```shell
pandoc -s -f markdown -t latex -F pandoc-crossref Test.md > Test.tex
```
where its replaced correctly with `\cref`. What I am doing wrong?

**Comment by lierdakil** [comment]
Try invoking with `pandoc-crossref latex --pipe`. It seems there's a bug in option parser somewhere, which I will try to fix sometime next week.

**Comment by gabyx** [comment]
See https://github.com/gabyx/TechnicalMarkdown/blob/master/output-tex/input.pdf
works like a charm, but the setup is a lot of fiddling trying to put together the best parts.
