### ISSUE TITLE
table {#tbl:} syntax does not work

### ISSUE THREAD

**Issue by redoxmatlab** [lierdakil/pandoc-crossref#265]
Hi,
I've installed the haskell version of pandoc-crossref and tried to convert my markdown file to PDF. Everything seems to go well, except for table labels and references. I know that I am using the right syntax as:

`: Table {#tbl:table1} and for cross-reference @tbl:table1`

The issue is that these get un recognised when converting via pandoc commnd:
`pandoc --filter pandoc-crossref mdfile -o pdfile`

I am not getting any error messages but something gone wrong. I have tried the crossref filter via homebrew (I have Mac) and that did not work at all. Interesting though that figure crossref is working just fine.

Could any one help please.

Thanks

**Comment by lierdakil** [comment]
Works for me:
```markdown
| 123 | 123 |
|-----|-----|
| 321 | 321 |

: Table 1 {#tbl:table1}

@tbl:table1
```

Pandoc-crossref version is:
```
pandoc-crossref v0.3.6.2 git commit UNKNOWN (UNKNOWN) built with Pandoc v2.9.2.1, pandoc-types v1.20 and GHC 8.6.5
```
