### ISSUE TITLE
cref section does not work in v0.3.6.3

### ISSUE THREAD

**Issue by zwz** [lierdakil/pandoc-crossref#268]
This is a MWE
```
---
autoSectionLabels: True
title: pandoc-crossref demo document
cref: True
---

# Chapter 1. Figures {#sec:sec1}
[@sec:sec1]
[@fig:fig1]

![test](test.png){#fig:fig1}

```

It is converted into pdf by
```
pandoc -f markdown -o demo.tex -s  demo.md
latexmk -xelatex demo.tex
```

But in the pdf it shows
```
Chapter 1. Figures
?? fig. 1
<<<the figure>>>
Figure # 1: test
```
The figure reference is OK, but the section reference is not.

**Comment by lierdakil** [comment]
You need to invoke pandoc with `--number-sections` to have section numbers enabled in output LaTeX. Naturally, it's impossible to reference unnumbered sections by number.

**Comment by zwz** [comment]
Oops...
It works now.
