### ISSUE TITLE
issue with per-chapter numbering and unnumbered chapters

### ISSUE THREAD

**Issue by bmesuere** [lierdakil/pandoc-crossref#27]
I'm working on a book with a few unnumbered chapters without images as front-matter.
If I use per-chapter numbering, the pandoc-crossref chapter seems to also increment for these chapters.
Therefore, my chapter 2 figures are numbered `Figure 5.1`, `Figure 5.2`,...

Is this expected behaviour and if so, is there a workaround to manually reset the internal counter so I can make the pandoc chapter numbers and the pandoc-crossref chapter numbers match?

**Comment by lierdakil** [comment]
How would you specify unnumbered chapters in Markdown though? I think pandoc only supports either numbering all chapters, or none of them (I may be mistaken though).

**Comment by bmesuere** [comment]
Numbering can be turned off on a per-chapter basis: http://pandoc.org/README.html#extension-header_attributes

**Comment by lierdakil** [comment]
Thanks. I will try to fix this sometime this week.

**Comment by lierdakil** [comment]
I've released v0.1.2.4, which hopefully fixes most problems with per-chapter numeration (there were a couple). If you find anything else, feel free to open new issues.

**Comment by bmesuere** [comment]
Great, this fixes the problem. Thanks for the quick fix!
