### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by oguerrer** [lierdakil/pandoc-crossref#274]
Hi,

I have pandoc-crossref installed on MacOs (have tried both brew and conda and get the same result). I am trying to convert tex to word, but I keep getting a `Duplicate label` error for a label that is not a duplicate. Through trial and error, I have noticed that the error appears whenever a label is referenced more than once in the document.

This error appears in various documents that I try to convert. Any help would be greatly appreciated.

**Comment by lierdakil** [comment]
Hello.

Pandoc-crossref is _not intended_ to be used with LaTeX as input format, so it's generally no surprise it doesn't work. See #250, #257 for more information and a hack that _might_ help (depending on your use case, it might not). If you need further help, an example document where the issue manifests would certainly make things easier for everyone involved.
