### ISSUE TITLE
Underscore in codeblock caption breaks output with listings

### ISSUE THREAD

**Issue by sys9kdr** [lierdakil/pandoc-crossref#278]
I've got problem with codeblock captions and listings.

# Steps to reproduce

1.  Create this markdown file, input.md.

~~~markdown
```{#lst:codeblock caption="some_code.c"}
code
```
~~~

2.  Build pdf with listings options and lualatex.

```console
pandoc -o ./output.pdf --filter pandoc-crossref --pdf-engine=lualatex --listings -Mlistings input.md
```

3. Following error caused.

```error

Error producing PDF.
! Missing $ inserted.
<inserted text> 
$
l.76 ...[caption={some_code.c}, label=lst:codeblock]


```

With removing underscores from codeblock captions,  I've successfully built pdf.

**Comment by lierdakil** [comment]
Apparently pandoc doesn't escape caption appropriately with `--listings`. FWIW,

``````markdown
```{#lst:codeblock caption="some_code.c"}
code
```
``````

is exactly as borked without pandoc-crossref, so it's probably better to report this [upstream](https://github.com/jgm/pandoc/)

As for other cases, I'll try to figure something out. As a temporary workaround, escaping with `\`/`\\` should work.

**Comment by lierdakil** [comment]
v0.3.8.2 should fix the issue for codeblock divs and table-style captions. Caption attribute is left as-is, as it might be intentional (in case you want to include raw LaTeX in caption). If you believe it is a bug, report it [upstream](https://github.com/jgm/pandoc/)

**Comment by sys9kdr** [comment]
Thank you for your kindness. I filed this bug at upstream. https://github.com/jgm/pandoc/issues/6742

**Comment by sys9kdr** [comment]
Fixed at upstream. https://github.com/jgm/pandoc/issues/6742

**Comment by pykong** [comment]
@sys9kdr THX!
