### ISSUE TITLE
What is "Fixed format option order in pipe mode"?

### ISSUE THREAD

**Issue by kiwi0fruit** [lierdakil/pandoc-crossref#279]
https://github.com/lierdakil/pandoc-crossref/commit/ad1b11aeb1875704a43056189a545147f30bf170

I can't really understan Haskell. Could you please elaborate what behaviour was on `<=0.3.6.2a` and what behavour is now on `>=0.3.6.3`?

Will anything change for script like this one?

```bash
... | pandoc-crossref --pipe "$to" | ...
```

where `"$to"` is a single argument.

**Comment by kiwi0fruit** [comment]
Will anything change for script like

```
... | pandoc-crossref --pipe "$to" | ...
```

where `"$to"` is a single argument.

**Comment by lierdakil** [comment]
IIRC ad1b11a fixes https://github.com/lierdakil/pandoc-crossref/issues/262

**Comment by kiwi0fruit** [comment]
Thanks!
