### ISSUE TITLE
[DOCS] Outline in documentation

### ISSUE THREAD

**Issue by jzeneto** [lierdakil/pandoc-crossref#280]
Hi, thank you for pandoc-crossref, it's awesome.

Although its syntax is clear, sometimes I need to quickly look the docs to remember something. But, as it doesn't have an outline, this process is a bit slow.

So, it would be great if the documentation had an outline (just like [Pandoc user's guide](https://pandoc.org/MANUAL.html) has).

**Comment by lierdakil** [comment]
If by "outline" you mean the thing that's usually called "table of contents", I've added that: http://lierdakil.github.io/pandoc-crossref/. Otherwise, I'm not entirely sure what you mean.

**Comment by jzeneto** [comment]
Yes, it was exactly that! Thank you, and sorry by my English.
