### ISSUE TITLE
Move number tag outside of equation object for docx output

### ISSUE THREAD

**Issue by mlell** [lierdakil/pandoc-crossref#285]
This project is hugely useful for me to exchange manuscript drafts with other people because they want Word's "Track changes" features for corrections. So for now I'm stuck with DOCX output. 

The equation numbering, however, is included in the math object so that I cannot align them properly.
Minimal example:
```
Test text

$$ 
a^2 = b + \sqrt{\frac cd}
$$ {#eq:test}

This is text referring to [@eq:test]
```

converted with `pandoc -F pandoc-crossref --to docx --from markdown+latex_macros < test.md > test.docx`

Yields: 
![grafik](https://user-images.githubusercontent.com/16210594/101031566-edb04800-3579-11eb-80ed-2fa3fe4443b8.png)

What would be much better is instead putting the equation on a paragraph with centered format, the equation would be aligned with two tabstops, one centered and one right-aligned:

![grafik](https://user-images.githubusercontent.com/16210594/101033164-67483600-357a-11eb-90e6-0242cbc3523e.png)

**Comment by lierdakil** [comment]
You might be interested in `tableEqns` option. It does something like this, albeit not with tabs. Frankly, Pandoc doesn't do tabs, and I really don't want to fiddle with raw OOXML any more than I absolutely have to. I will consider a PR though.

**Comment by mlell** [comment]
`tableEqns`works wonderfully. I overlooked this option in the docs because it didn't mention that this option is related to aligning the equation number. 

Thank you for your help.
