### ISSUE TITLE
Filter returned error status -9

### ISSUE THREAD

**Issue by scokobro** [lierdakil/pandoc-crossref#288]
I receive the output below when running this command...

`pandoc --filter /Users/USERNAME/.pandoc/filters/pandoc-crossref --output /Users/USERNAME/Desktop/test.odt --to odt --from markdown --standalone --verbose Untitled.md`

on this file (Untitled.md)

```
see @fig:pic

![Caption](https://fakeimg.pl/200x40/?retina=1&text=Image%201%20Here){#fig:pic}
```

OUTPUT

```
[INFO] Running filter /Users/USERNAME/.pandoc/filters/pandoc-crossref
Error running filter /Users/USERNAME/.pandoc/filters/pandoc-crossref:
Filter returned error status -9
```

Any guidance on dealing with 'error status -9' would be greatly appreciated.

Pandoc - 2.11.3.1
pandoc-crossref - latest (as of 22/12/20)
MacOS v11.1

**Comment by lierdakil** [comment]
Hmm. I could not reproduce on the one macOS machine I have access to (which is on 10.12). This might be related to UPX -- in which case unpacking with `upx -d` should help. Or this might be some sort of incompatibility between the build environment and your system, in which case installing [pandoc-crossref from Homebrew](https://formulae.brew.sh/formula/pandoc-crossref) should be a viable option.

For reference, I don't think the prebuilt binaries available here are compatible with Apple M1 processor. Can't do much about that for the simple reason there are no CI servers on M1.

**Comment by scokobro** [comment]
Installing from Homebrew solved the problem. 
Many thanks!
