### ISSUE TITLE
builds for macos big sur

### ISSUE THREAD

**Issue by knaaptime** [lierdakil/pandoc-crossref#289]
hi team, thanks for all your work on this! Unfortunately I'm unable to get the released binary (actually any of the prior releases) working on macos big sur. Each time the binary is called its shutdown with `[1]    40976 killed     pandoc-crossref`.  `sudo chmod +x path/to/pandoc-crossref` doesnt seem to fix the issue, though the same binaries work on older versions of macos

oddly, the homebrew-compiled version works just fine, so i wonder if it the issue could somehow be related to the packaging build system (like [this](https://github.com/hasura/graphql-engine/issues/5462))?

thanks for all your help

**Comment by lierdakil** [comment]
I don't have access to Big Sur, so I can't test, and I have no idea what changed exactly. If you don't mind testing, here's a upx-free version of v0.3.9.0 [pandoc-crossref.zip](https://github.com/lierdakil/pandoc-crossref/files/5750151/pandoc-crossref.zip (sorry, it's an xz file inside a zip, because github refuses to attach xz by itself), perhaps it's just as simple as that.

**Comment by knaaptime** [comment]
thanks for your quick response. I'm more than happy to beta test. Bummer though, this doesn't seem to resolve the issue (which i can confirm on a couple different big sur machines)

**Comment by knaaptime** [comment]
EDIT: scratch that. this DOES fix the issue

**Comment by lierdakil** [comment]
Okay, I've tried updating upx, let's see if that helps: https://bintray.com/lierdakil/pandoc-crossref/download_file?file_path=pandoc-crossref-macOS-42fd8a8c1a22b58496fa162040fe486ec7677137.tar.xz (this also slightly bumps GHC and Pandoc versions, but I think this shouldn't be an issue).

**Comment by knaaptime** [comment]
nope, that one still gets killed

**Comment by lierdakil** [comment]
All righty, in that case the easiest option for me is probably just drop upx on macOS entirely. As a sanity check, please confirm that the automated build without upx works: https://bintray.com/lierdakil/pandoc-crossref/download_file?file_path=pandoc-crossref-macOS-cdb098b5a73304b4f02eb28e5bfb1e3837e41c29.tar.xz Thanks

**Comment by knaaptime** [comment]
yep, that one works again

```bash
base ❯ /Users/knaaptime/Downloads/pandoc-crossref\ 3 -v
pandoc-crossref v0.3.9.0 git commit cdb098b5a73304b4f02eb28e5bfb1e3837e41c29 (ci-test) built with Pandoc v2.11.3.2, pandoc-types v1.22 and GHC 8.10.3
```

thanks a ton for the package in general and for the rapid support!

**Comment by xuebao1942** [comment]
It also works for me!!!

**Comment by lierdakil** [comment]
v0.3.9.0a available on the releases page.
