### ISSUE TITLE
[latex] conflict with minted package

### ISSUE THREAD

**Issue by jpcirrus** [lierdakil/pandoc-crossref#29]
With output to latex and when the `minted` package is loaded for source code highlighting, there is a conflict which prevents the latex document from compiling.

`minted` by default loads the `float` package and also provides a `listoflistings` command which conflicts with that in `pandoc-crossref`. If this`pandoc-crossref` command is changed in the source document to `\renewcommand*\listoflistings{\listof{codelisting}{List of Listings}}` then it compiles. There should be a test to see if `minted` is loaded and then either provide a new or renew command for `listoflistings` or just use the `minted` command.

**Comment by lierdakil** [comment]
For compatibility with extra packages, you have three options:

1. Use a custom LaTeX template (presumably without `header-includes` variable)
2. "Undefine" conflicting commands in document header, e.g.

    ```markdown
    ---
    header-includes:
      - "\\usepackage{minted}"
      - "\\makeatletter"
      - "\\let\\listoflistings\\@undefined"
      - "\\makeatother"
    ...
    ```

3. Some combination of both

I don't want to `\renewcommand*` for reasons of avoiding implicit redefinitions (which *will* break things). And I can't assume that already-defined commands will do what they're supposed to. So this is wontfix.

**Comment by jpcirrus** [comment]
Fair enough, and thanks for the suggestions.
