### ISSUE TITLE
Bump to latest version?

### ISSUE THREAD

**Issue by OvidiusCicero** [lierdakil/pandoc-crossref#294]
~~~
WARNING: pandoc-crossref was compiled with pandoc 2.11.3.2 but is being run through 2.11.4. This is not supported. Strange things may (and likely will) happen silently.
~~~

**Comment by ArturoBell** [comment]
Same error over here. I tried downgrading my pandoc, though I wasn't successful...

**Comment by lierdakil** [comment]
Sorry, forgot to update this issue. pandoc-crossref v0.3.9.1 is built with pandoc 2.11.4.

**Comment by OvidiusCicero** [comment]
thank you!Am 09.02.21, 16:42 schrieb Nikolay Yakimov <notifications@github.com>:

   
  Sorry, forgot to update this issue. pandoc-crossref v0.3.9.1 is built with pandoc 2.11.4.
