### ISSUE TITLE
feature request: link cross references

### ISSUE THREAD

**Issue by bmesuere** [lierdakil/pandoc-crossref#30]
The pandoc-citeref filter has an option (`link-citations`) to link the cross references in html and latex output: clicking on the reference jumps to the corresponding entry in the bibliography.
Would it be possible to add something alike to pandoc-crossref?

One of the things that needs to happen for this is adding id's to the figures and tables in html. This would also be beneficial for other things such as targeting specific images with css, or adding page numbers (using `target-counter(attr(href), page)` in css) to the list of figures in html.

**Comment by lierdakil** [comment]
I assume you mean pandoc-citeproc?

Pandoc's document model lacks arbitrary element attributes, i.e. images, math formulae, etc can't have `id` set. Inserting it manually for all possible output formats is pure madness, so only option is to encase all "referenceable" elements in `div`s. This seems like a very hacky solution, so I'm more than a bit reluctant to implement it.

I'll keep this request in mind, but I'm really not sure of when I will be able to do something about it.

If you have any suggestions on possible implementation, I'm always glad to hear those. PRs are also welcome.

**Comment by bmesuere** [comment]
Yes, I'm sorry, I indeed meant citeproc. I really want to help, but unfortunately I've never learned haskell :( 
I tried looking at the citeproc implementation, but I assume the id's used there are added by pandoc itself?

**Comment by lierdakil** [comment]
I haven't been following pandoc development closely as of late, so I'm not sure how John implemented it, but looking at the output, citeproc wraps each paragraph in reference list into a div. Seems like it's really the only option with current document model. There has been some discussion about adding attributes to everything, but almost no progress on this has been made to my knowledge.
