### ISSUE TITLE
Redefine \floatstyle for codelistings

### ISSUE THREAD

**Issue by Tajnymag** [lierdakil/pandoc-crossref#303]
Do you know of any way how I could change the style for codelistings? It seems that pandoc-crossref hardcodes it for the environment at the end of the header.

I would like to set the style back to plain but I can't find any way to do it. The docs seem to talk only about the formatting of the displayed text, not about the block style itself.

**Comment by lierdakil** [comment]
Run pandoc with `--listings -Mlistings` to use LaTeX listings package and add configuration you need in header-includes? Alternatively, use a custom LaTeX template which defines `codelisting` environment as no-op. Or perhaps you could just force "here" positioning for `codelisting` floats.

If you don't need either captions on or references to listings, you might as well set pandoc-crossref `listings` option to `true` (either via metadata block or `-Mlistings` on the command line) without actually telling pandoc to use listings package (i.e. without `--listings`). This will should any special code block handling on both pandoc and pandoc-crossref sides.

Sorry if I misunderstood the question or my advice seems somewhat deficient, I'm pretty knackered, so words are especially hard.

**Comment by Tajnymag** [comment]
Using listings might help, but I would lose the skylighting highlighting.

Unfortunately, I do need both captions and references.

I need to specifically change the way the float is decorated, not really the code itself. 

This is the way the pandoc-crossref sets the floatstyle:
```tex
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Kód}
```

This is how it gets rendered:
![obrazek](https://user-images.githubusercontent.com/3985946/113438674-58b74180-93e9-11eb-91ba-c1aa67e9b7c2.png)

This is how I would like the float to be rendered:
![obrazek](https://user-images.githubusercontent.com/3985946/113438845-af248000-93e9-11eb-85a6-80ef53409dff.png)

This is how I need to edit the intermediate tex file to have the code block caption rendered as I want:
```tex
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{plain}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Kód}
```

What I tried was to set floatstyle to noop by `\let\floatstyle\nop` in header-includes but that didn't have any effect.

**Comment by lierdakil** [comment]
I see.

```yaml
header-includes:
- |
  \AtEndPreamble{%
  \floatstyle{plain}
  \restylefloat{codelisting}
  }
```
should probably work.

**Comment by Tajnymag** [comment]
Ah, I see. Thanks. I've had to leave it for today, but I'll try your solution tommorow morning an will close the issue.

Thank you for your guidance.

**Comment by Tajnymag** [comment]
> 
> 
> I see.
> 
> ```yaml
> header-includes:
> - |
>   \AtEndPreamble{%
>   \floatstyle{plain}
>   \restylefloat{codelisting}
>   }
> ```
> 
> should probably work.

For anyone having similar troubles as me, @lierdakil's code works great. Thank you @lierdakil.
