### ISSUE TITLE
Templates in defaults files when converting to reveal.js

### ISSUE THREAD

**Issue by p3palazzo** [lierdakil/pandoc-crossref#304]
Use case: a `defaults.yaml` file containing the following lines.

```
metadata:
  figureTemplate: $$t$$
```

This works when converting `-t html`, but not with `-t revealjs`. In the latter case, Pandoc seems to escape the dollar signs and the template shows as a literal `$$t$$` on the slide, rather than being parsed as the figure caption. Is there any workaround we could use? Specifying the template within the file's front matter works fine, but I would rather not do this since I have a large number of documents to convert.

**Comment by lierdakil** [comment]
You can try creating `pandoc-crossref.yaml` in the current directory (i.e. the directory where you run pandoc) with the following contents:
```yaml
figureTemplate: $$t$$
```
Or you could create this file globally in `$HOME/.pandoc-crossref/config.yaml`, or specify a path to it on the command line with `-McrossrefYaml=path/to/config.yaml`

For more information, please see the documentation: http://lierdakil.github.io/pandoc-crossref/#settings-file

**Comment by p3palazzo** [comment]
Thanks—I should have paid attention to the `crossrefYaml` part in the documentation.
