### ISSUE TITLE
Provide a library to use in hakyll/gitit/etc [was: pandoc-crossref, bibtex and hakyll]

### ISSUE THREAD

**Issue by anderflash** [lierdakil/pandoc-crossref#31]
Hi,
I'm trying to put bibtex and pandoc-crossref to work in a Hakyll wiki config.
I have this almost default code:
~~~.haskell
match "posts/*" $ do
        route $ setExtension "html"
        compile $ do
            -- modification begin
            item <- getUnderlying
            bibFile <- liftM (fromMaybe "") $ getMetadataField item "biblio"
            cslFile <- liftM (fromMaybe "chicago") $ getMetadataField item "csl"
            let compiler = if bibFile /= ""
                then bibtexCompiler cslFile bibFile
                else pandocCompilerWithTransformM defaultHakyllReaderOptions pandocOptions (transformer "pandoc-crossref" defaultHakyllReaderOptions pandocOptions)
            compiler
            -- modification end
                >>= loadAndApplyTemplate "templates/post.html"    postCtx
                >>= loadAndApplyTemplate "templates/default.html" postCtx
                >>= relativizeUrls
~~~
If the post has a bibtex file attached, process the bibtex, else skip bibtex processing, working only with the pandoc-crossref.

My problem is the bibtexCompiler code. I want to put pandoc-crossref inside it:

~~~.haskell
bibtexCompiler :: String -> String -> Compiler (Item String)
bibtexCompiler cslFileName bibFileName = do 
    csl <- load (fromFilePath $ "csl/"++cslFileName)
    bib <- load (fromFilePath $ "bib/"++bibFileName)
    --liftM (writePandocWith pandocOptions)
    --    (getResourceBody >>= readPandocBiblio def csl bib)
    writePandocWith pandocOptions <$>
        (traverse transformer "pandoc-crossref" def pandocOptions =<< readPandocBiblio def csl bib =<< getResourceBody)

transformer  :: Script  -> ReaderOptions  -> WriterOptions -> (Pandoc -> Compiler Pandoc)
transformer script reader_opts writer_opts pandoc = 
    do let input_json = writeJSON writer_opts pandoc
       output_json <- unixFilter script [] input_json
       return $ 
          either (error.show) id $  -- this line needs to be uncommented atm.
          readJSON reader_opts output_json 
~~~

I've seen the code for pandocCompilerWithTransformM:
~~~.haskell
pandocCompilerWithTransformM :: ReaderOptions -> WriterOptions
                    -> (Pandoc -> Compiler Pandoc)
                    -> Compiler (Item String)
pandocCompilerWithTransformM ropt wopt f =
    writePandocWith wopt <$>
        (traverse f =<< readPandocWith ropt =<< getResourceBody)
~~~
That's why I'm trying to use this code, replacing `readPandocWith ropt` with `readPandocBiblio def csl bib`, which has the same return type. But it doesn't work.

It compiles and runs correctly, and it shows the bibliography and the _Figure 1_, but the citation shows  \[@author\], even though it shows [1]. The reason I create the issue here is that whether I remove the `traverse transformer ...`, the citation works (it shows [1]), but the pandoc-crossref not.

Thanks

**Comment by lierdakil** [comment]
An obvious question: does running `pandoc -F pandoc-crossref -F pandoc-citeproc` on your Markdown source produce desired output? I'm not an expert on using Pandoc filters in Hakyll by any stretch, so besides that, not sure if I can be of much help.

**Comment by lierdakil** [comment]
I think I could just provide a library to sidestep this issue altogether. I will change this issue accordingly. Not sure if I find time to do this soon though.

**Comment by lierdakil** [comment]
So, I kind of offer a library interface here. That said, it might be a little bit awkward to work with at the moment. I will try to extend this interface later down the line, so marking this as 'in progress'.

**Comment by lierdakil** [comment]
So... library interface probably isn't going to change much, so closing this. If anyone has suggestions, feel free to open new issues.
