### ISSUE TITLE
pandoc 2.13 support

### ISSUE THREAD

**Issue by ickc** [lierdakil/pandoc-crossref#311]
Hi,

I noticed that 2.13 is supported in v0.3.10.0a, but because of the alpha status it is not propagated to conda-forge yet: https://github.com/conda-forge/pandoc-crossref-feedstock/blob/master/recipe/meta.yaml

Is there any reason for the alpha status or can it be bumped to say v0.3.10.1?

Thanks.

**Comment by lierdakil** [comment]
It's not an alpha. It's just v0.3.10.0 with an updated CI config. Because I need to tag those builds somehow, and the numeric part needs to correspond to the actual version number in the cabalfile/on Hackage.

**Comment by ickc** [comment]
Sorry I was not familiar with the Haskell versioning semantics. I’ve already made a PR to the conda forge package and hopefully it’ll be merged soon.

have a great day.
