### ISSUE TITLE
Can't update cabal from v3 to v2 to install pandoc-crossref 

### ISSUE THREAD

**Issue by YAS01-M** [lierdakil/pandoc-crossref#312]
Platform : Windows 

 i run "cabal v2-update'' and then i install pandoc-crossref , but i get this error :

![2](https://user-images.githubusercontent.com/84593166/120361726-1aaf9e80-c302-11eb-94bf-c8718c387351.JPG)

**Comment by lierdakil** [comment]
Sorry, we don't support GHC 9.0 yet. Try building with GHC 8.10.

**Comment by Delanii** [comment]
Are there any plans as to when ghc 9.0 support will be comming?

**Comment by lierdakil** [comment]
No plans. "Eventually". Not earlier than Stackage LTS switches to GHC 9.

**Comment by lierdakil** [comment]
Actually, scratch that. Master should build with ghc 9. I will also make a release based off the current master. However, CI binaries will still be built with 8.10 for the time being.

**Comment by lierdakil** [comment]
Released as pandoc-crossref 0.3.12.0.
