### ISSUE TITLE
Implicit heading reference problem when "autoSectionLabels" is enabled.

### ISSUE THREAD

**Issue by skystar0227** [lierdakil/pandoc-crossref#314]
Thank you very much for the nice tool.

I have a problem with implicit heading reference when "autoSectionLabels" is enabled.

```markdown
---
autoSectionLabels: True
---

# Section One

This section's heading has an identifier `#sec:section-one` thanks to Pandoc extension auto_identifiers and an option `autoSectionLabels: True` for pandoc-crossref.

See [Section One].

Problem: above hyperlink will be linked not to `#sec:secton-one` but to `#section-one`.
```

Any solutions or workarounds?

**Comment by lierdakil** [comment]
Can't offer any workarounds aside from verbosely writing out your links (i.e. `[Section One](#sec:section-one)`).

However, I'm somewhat confused as to why exactly you want to use a direct section link instead of a reference, i.e. why not `@sec:section-one` instead of `[Section One]`; Consider:

```markdown
---
autoSectionLabels: True
linkReferences: True
nameInLink: True
refIndexTemplate:
  sec: $$i$$$$suf$$ ($$t$$)
  default: $$i$$$$suf$$
---

# Section One

This section's heading has an identifier `#sec:section-one` thanks to Pandoc extension auto_identifiers and an opti
on `autoSectionLabels: True` for pandoc-crossref.

See @sec:section-one.
```

or even remove the section index entirely if you prefer:

```yaml
# ...
refIndexTemplate:
  sec: $$t$$$$suf$$
  default: $$i$$$$suf$$
secPrefixTemplate: $$i$$
```

**Comment by skystar0227** [comment]
Thank you for concrete consideration.

As you mentioned, I have an option to use `@sec:section-one` instead of `[Section One]`.
Off cause, I think it is not beautiful that multiple different reference styles exist in one document.
It is not critical for me that there is no solution for this problem, currently.

My interest is to notate hyperlinks with heading text instead of identifier.
I found this problem when seeking solutions for #315.

We can close this issue if there is no enough worth to restore the original Pandoc behavior when "autoSectionLabels" is enabled.
