### ISSUE TITLE
pandoc-crossref errors 

### ISSUE THREAD

**Issue by VolkovIlia** [lierdakil/pandoc-crossref#317]
When I trying to compile document I've got errors:

```
pandoc-crossref: error while loading shared libraries: libHSpandoc-2.14.0.2-38QxSC8J8O32ZyS4un
0Ncd-ghc8.10.5.so: cannot open shared object file: No such file or directory
Error running filter pandoc-crossref:
Filter returned error status 127
pandoc-crossref: error while loading shared libraries: libHSpandoc-2.14.0.2-38QxSC8J8O32ZyS4un
0Ncd-ghc8.10.5.so: cannot open shared object file: No such file or directory
Error running filter pandoc-crossref:
Filter returned error status 127

shell returned 83
```

pandoc version `pandoc 2.14.0.2`

Also cant start pandoc-crossref with the same error. version `0.3.12.0-1`

How to fix it?

**Comment by lierdakil** [comment]
How did you obtain pandoc-crossref binary? What OS are you using?

**Comment by lierdakil** [comment]
Okay, after a quick investigation, I'm guessing Arch Linux for the second question, and installed from the Community repository for the first one.

The short answer is, the missing library is available specifically in this package: https://archlinux.org/packages/community/x86_64/pandoc/ . If you've installed pandoc from any other source, you need to install that package instead.

If that doesn't work, I suggest creating an issue on the [arch bug tracker](https://bugs.archlinux.org/).

In the meantime, feel free to grab the prebuilt Linux binary from the [releases page](https://github.com/lierdakil/pandoc-crossref/releases) and putting it somewhere on PATH (`/usr/local/bin/` for instance)

**Comment by VolkovIlia** [comment]
Installing pandoc from community repo works for me, thx!

> Okay, after a quick investigation, I'm guessing Arch Linux for the second question, and installed from the Community repository for the first one.
> 
> The short answer is, the missing library is available specifically in this package: https://archlinux.org/packages/community/x86_64/pandoc/ . If you've installed pandoc from any other source, you need to install that package instead.
> 
> If that doesn't work, I suggest creating an issue on the [arch bug tracker](https://bugs.archlinux.org/).
> 
> In the meantime, feel free to grab the prebuilt Linux binary from the [releases page](https://github.com/lierdakil/pandoc-crossref/releases) and putting it somewhere on PATH (`/usr/local/bin/` for instance)
