### ISSUE TITLE
Expose equation table width parameter in yml

### ISSUE THREAD

**Issue by leenamurgai** [lierdakil/pandoc-crossref#321]
I am converting from LaTeX to HTML5 and trying to use pandoc-crossref version 2.14.02 for equations. In the resulting HTML, the equation is inserted into a table (which is great by the way - very happy indeed to see this feature):
```
<div id="eq:label">
<table style="width:99%;">
<colgroup>
<col style="width: 90%" />
<col style="width: 9%" />
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math display">latex_equation</span></td>
<td style="text-align: right;"><span class="math display">(chap#.value(eq:label))</span></td>
</tr>
</tbody>
</table>
</div>
```
I would like to adjust the width of the table. Would you consider exposing the table width (currently set to 99%) as an option in the yml?

**Comment by tolot27** [comment]
You can use a css prefix selector to achieve this already:

```
div[class^="eq:"] { 
// your formatting
}
```

**Comment by lierdakil** [comment]
If you're targeting HTML with MathJax specifically, you actually likely want

```yaml
equationNumberTeX: \\tag
```

instead of `tableEqns`. It will provide more consistent formatting using MathJax to typeset the number.

**Comment by leenamurgai** [comment]
> You can use a css prefix selector to achieve this already:
> 
> ```css
> div[id^="eq:"] { 
> // your formatting
> }
> ```

Hi @tolot27 I'm already doing something more like this to remove table borders, I didn't think it would override the hard coded 99%. But then I didn't think to change the div width either, just the table. Sorry! Problem solved!

**Comment by leenamurgai** [comment]
> If you're targeting HTML with MathJax specifically, you actually likely want
> 
> ```yaml
> equationNumberTeX: \\tag
> ```
> 
> instead of `tableEqns`. It will provide more consistent formatting using MathJax to typeset the number.

Hi @lierdakil, sorry for the non-issues and thanks. All good, I'm using KaTeX.
