### ISSUE TITLE
 `figureTitle`  and `tableTitle` seemingly ignored in XeLaTeX builds

### ISSUE THREAD

**Issue by thomasWeise** [lierdakil/pandoc-crossref#330]
Hello.

I am sorry to disturb your work a second time in such short succession.
This again is a problem of low importance and most likely I am doing something wrong...

It just noticed that it seems that `figureTitle`  and `tableTitle` may be ignored under XeLaTeX builds(?)

I have two builds, one in German and one in Chinese.
For both, `figureTitle`  and `tableTitle`  work completely fine when rendering to HTML (see [here](https://thomasweise.github.io/bookbuilderpy-mwe/de/book_de.html) and [here](https://thomasweise.github.io/bookbuilderpy-mwe/zh/book_zh.html), respectively).

However, when building to pdf, I have to select the XeLaTeX pipeline for the Chinese version while using pdfLaTex for the German one.
The [German](https://thomasweise.github.io/bookbuilderpy-mwe/de/book_de.pdf) version renders completely fine and produces a [pdf](https://thomasweise.github.io/bookbuilderpy-mwe/de/book_de.pdf) where the figure and table captions contain the German words.
The [Chinese](https://thomasweise.github.io/bookbuilderpy-mwe/zh/book_zh.pdf) version, however, produces a [pdf](https://thomasweise.github.io/bookbuilderpy-mwe/zh/book_zh.pdf) where the figure and table captions are the English terms "Figure" and "Table", respectively.

Maybe I am doing something wrong here?

(Side note: If `figureTitle`  and `tableTitle` actually do not work, maybe `listingTitle` won't work either, but I did not test that yet.)

Many thanks for your help.
Thomas.

**Comment by lierdakil** [comment]
Hey. Sorry for the late reply. I can't reproduce the issue.

```markdown
---
figureTitle: xxx
...

![Somefigure](fig.png){#fig:fig}

@fig:fig
```
passed through `pandoc -F pandoc-crossref -t latex -s --pdf-engine=xelatex -o test.pdf` seems to produce the expected output:
![image showing figure title with "xxx 1" prefix](https://user-images.githubusercontent.com/7275622/132750398-c139475f-a75e-4fbb-addf-92a1e342f4e6.png)

Check that your pandoc invocation doesn't use `--header-includes` (I believe we discussed workarounds in another thread) and if you're using a custom template (via `--template` or the defaults file), make sure it contains
```
$for(header-includes)$
$header-includes$
$endfor$
```
in the appropriate place.

**Comment by thomasWeise** [comment]
You are right.
It seems to be an issue with the [`eisvogel.tex` template](https://github.com/Wandmalfarbe/pandoc-latex-template/issues/256) which I love very much (or with me doing something wrong).
Many thanks again,
  and sorry for the mistake on my side.
Thomas.

**Comment by ajeep8** [comment]
I do need to workaround, but I can't find the thread. 

I see https://lierdakil.github.io/pandoc-crossref/#latex-output-and---include-in-header, but don't know how to do.

I had tried pandoc-xnos' workaround, put some lines into headings.tex, I think pandoc-crossref should be likely, but can't find what to add to headings.tex. 

Any help? Thanks.

> Check that your pandoc invocation doesn't use `--header-includes` (I believe we discussed workarounds in another thread) and if you're using a custom template (via `--template` or the defaults file), make sure it contains
> 
> ```
> $for(header-includes)$
> $header-includes$
> $endfor$
> ```
> 
> in the appropriate place.
