### ISSUE TITLE
Custom Reference Labels Incorrect in PDF output

### ISSUE THREAD

**Issue by Kaszanas** [lierdakil/pandoc-crossref#332]
While browsing on how to use custom labels with ```pandoc-crossref``` I have noticed that even in the official examples the custom label part of the example is wrong:

![image](https://user-images.githubusercontent.com/34846245/135312382-23a743b4-a0fc-4fdd-bf2f-191a62558a0d.png)

Which seems strange especially that in HTML output it seems to be working correctly:

![image](https://user-images.githubusercontent.com/34846245/135312445-2106b47d-5fd1-4e3b-b976-af421d5efcf9.png)

I have the same problem where my references do not have custom labels when attempting to output to PDF.
If You know anything about a potential fix, I would be glad to verify it.

**Comment by lierdakil** [comment]
Those just don't work with LaTeX. There's actually no way to make it work with LaTeX and still produce non-plaintext references. If you don't care, try running pandoc-crossref as a pipe:

```
pandoc -t json input.md | pandoc-crossref --pipe | pandoc -f json -t latex -o output.pdf
```

**Comment by Kaszanas** [comment]
My current command looks like this:

```
pandoc program.md -o program.pdf --filter pandoc-crossref --template eisvogel --listings --number-sections --toc
```

I will try to run pandoc the way that You suggest and provide You with information if it indeed works as intended. I do not use subfigures so I do not care about such things.

**Comment by Kaszanas** [comment]
@lierdakil So the output "technically" works but any special characters that were written in UTF-8 in markdown break and result in ```??``` within the final ```.pdf``` output. Any Idea on how to preserve these characters as initially when not using ```pandoc-crossref``` the output is correct.

**Comment by lierdakil** [comment]
> UTF-8 in markdown break[s]

Uh... that really shouldn't happen AFAIK. Are you perchance on Windows? Perhaps try `chcp 65001` in the terminal before running pandoc.

**Comment by Kaszanas** [comment]
@lierdakil Yes I am currently on Windows. And for example my name that uses a special character "Andrzej Białecki" is generated as:

![obraz](https://user-images.githubusercontent.com/34846245/135342490-e1966fd4-5d8a-44e2-bb13-babe3d258f2d.png)

My YAML header is:

```
---
title: "Enter Some title"
author: [Andrzej Białecki]
subject: "Some Subject"
keywords: [keyword1, keyword2]
subtitle: "Some Subtitle"
lang: "pl"
titlepage: true
titlepage-text-color: "FFFFFF"
titlepage-rule-color: "360049"
titlepage-rule-height: 0
titlepage-background: "../assets/background-1.pdf"
...
```

Apart from that all of other special characters such as: ó, ę, ć, ż, and others - just break into ```??``` within the file as follows:

![obraz](https://user-images.githubusercontent.com/34846245/135342790-4dfb0f9b-dc1c-4a6f-a811-4aad6d447a4e.png)
![obraz](https://user-images.githubusercontent.com/34846245/135342802-13db896f-8969-4f60-8b25-5421f2226f1c.png)

**Comment by lierdakil** [comment]
Huh... Well, I can add a metadata option to disable most special treatments for LaTeX, which would fix this issue. However, this will likely have to wait till weekend, pretty busy with work currently, don't have much mental capacity left for code during weekdays.

**Comment by Kaszanas** [comment]
Ok, should I provide a sample file with more examples of such characters being used?

**Comment by Kaszanas** [comment]
It seems that I somehow resolved this issue as initially the text appeared incorrect but after running the following commands in two intermediate steps solved the problem and provided the correct labels.

It might've been MY - User error.

I am closing this issue.
