### ISSUE TITLE
Equation references not work for very simple latex file. please help.

### ISSUE THREAD

**Issue by pbpf** [lierdakil/pandoc-crossref#333]
Hi there, I read the document briefly and test a simply latex file  with command

 "pandoc -s a.tex --filter pandoc-crossref  -f LaTeX -t docx   --citeproc -M autoEqnLabels=true -o a.docx"

**But the equation references in output file is "[_label_]" not "(_equation number_)", what should i do?**

Here is the file a.tex
``` latex
\documentclass{article} 
\usepackage{amsmath} 
\usepackage{hyperref} 
\usepackage{amsfonts} 

\title{title}
\author{author \\ dp}

\begin{document}
\maketitle
\begin{abstract}
    test abstract
\end{abstract}  
\begin{equation}
    x=1\label{eq1}
\end{equation}
test equation ref \eqref{eq1}.
\end{document}
```

**Comment by lierdakil** [comment]
See https://github.com/lierdakil/pandoc-crossref/issues/250
