### ISSUE TITLE
pandoc-crossref support  for  latest pandoc release 

### ISSUE THREAD

**Issue by danieltomasz** [lierdakil/pandoc-crossref#334]
Current version was compiled for pandoc 2.14.2.
It causes error when running with pandoc 2.15
```
WARNING: pandoc-crossref was compiled with pandoc 2.14.2 but is being run through 2.15. This is not supported. Strange things may (and likely will) happen silently.
```

**Comment by hseg** [comment]
`pandoc 2.16` was released a couple hours ago, issue should be updated for that
(forcibly building against 2.15 works, checking 2.16...)

**Comment by lierdakil** [comment]
> pandoc 2.16 was released
 
Not on Hackage, or GitHub, or pandoc.org, so no, apparently it wasn't, at least not yet.

Other than that, thanks for the heads-up. Something went wrong on the CI side of things though, it'll probably take a little while to sort out. Meanwhile, I'll go update version constraints on Hackage.

**Comment by hseg** [comment]
On hackage now, fyi

**Comment by lierdakil** [comment]
Yeah... the issue is I can't yet _get_ it from Hackage, because it takes a few hours to update. Anyway, for now I'll figure something out wrt 2.15, and we'll get to 2.16 in a day or two, when both hackage and stackage snapshots catch up.

**Comment by hschwentner** [comment]
Pandoc was updated again, so current release is 2.16.1

**Comment by lierdakil** [comment]
Okay, with builds for both 2.15 and 2.16.1 available, I think this issue can be closed. Please open new issues for future versions of pandoc.
