### ISSUE TITLE
Pandoc  2.16.2 is out. pandoc-crossref  doesn't support it yet

### ISSUE THREAD

**Issue by danieltomasz** [lierdakil/pandoc-crossref#337]
Current version was compiled for pandoc 2.16.1.
It causes error when running with pandoc 2.16.2

`pandoc-crossref v0.3.12.1 git commit 6ab340e (HEAD) built with Pandoc v2.16.1`

```
WARNING: pandoc-crossref was compiled with pandoc 2.16.1 but is being run through 2.16.2. This is not supported. Strange things may (and likely will) happen silently.
```

**Comment by jankap** [comment]
To my understanding, current version of pandoc-crossref works only for pandoc 2.14, see https://github.com/lierdakil/pandoc-crossref/releases
![image](https://user-images.githubusercontent.com/12893844/143214529-ef3ed286-3b3c-4fa4-bb16-74521f3f2b92.png)

Where did you get the binary from? :)

**Comment by danieltomasz** [comment]
There is release for 2.16.1 from  the same day,  you need to scroll down on GitHub releases page

**Comment by lierdakil** [comment]
> pandoc-crossref doesn't support it yet

... actually it does if you build from source. But there were no binaries, yes. https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.12.1a
