### ISSUE TITLE
Multiple labels in the same section.

### ISSUE THREAD

**Issue by piccolbo** [lierdakil/pandoc-crossref#340]
I am a new user so this may be a question. But if it isn't, maybe it's a proposal for future versions.

 I noticed a difference in the design compared to latex, whereby (from https://latex-tutorial.com/advanced-latex-cross-references/)

> For each key declared with \label{key}, LaTeX records the current reference string and the page number. Thus you can put multiple \label commands (of course, with different keys) inside the same sectorial unit, which will cause them to reference the same element with \ref but, possibly, different page numbers with \pageref.

Here, if I am not getting it wrong, to reference a section I need to put a single label in the same line as the section title. I like the latex design because I can keep the labels closer to the content. For example

> We are going to follow two main character Jim (see @jim) and Josh (see @josh). Story develops.

> # Background

> Jim {#jim} was born in Canada ...
Josh {#josh} was born in Mexico ...

If I could do this, if by any chance I split the Background chapter into several ones, the references will keep working. They are associated with the content,  not with the section title.

Would love to be told that this can be done already, but looking at docs, examples and my own tests I convinced myself this is not possible. If so please consider this as a possible design for future releases.

**Comment by lierdakil** [comment]
Unfortunately, multiple labels per section aren't possible in the pandoc document model. You could create anchors with inline spans and link to those, but that's probably not exactly what you're looking for.

**Comment by piccolbo** [comment]
I worked around it with a filter, thanks.

**Comment by piccolbo** [comment]
How does the inline span thing work?
<span> Jim {#jim}</span> or some such?

**Comment by lierdakil** [comment]
```markdown
[Jim]{#jim} was born in Canada ...
[Josh]{#josh} was born in Mexico ...
```
and respectively
```markdown
... main character Jim (see [Background](#jim)) and Josh (see [Background](#josh))
```
TBC this is just hyperlinks, nothing fancy. But it'll work in formats that support hyperlinks.
