### ISSUE TITLE
Support pandoc 2.17.1.1

### ISSUE THREAD

**Issue by aspeddro** [lierdakil/pandoc-crossref#345]
```
WARNING: pandoc-crossref was compiled with pandoc 2.17.0.1 but is being run through 2.17.1.1. This is not supported. Strange things may (and likely will) happen silently.
```

**Comment by jpk3333** [comment]
I've been getting this too (after a recent new install of Pandoc), but everything has been working perfectly, so far as I can tell.

**Comment by jpk3333** [comment]
Thanks. How should we move to this new version? I've already forgotten how I went about getting the pandoc-crossref executable on my machine in the first place!

**Comment by lierdakil** [comment]
Unfortunately, there was a build issue with one of the dependencies on Windows. I'll try again with a prior version for now.

When (if) CI passes, the binaries will be attached to a new release on the releases page.

**Comment by lierdakil** [comment]
CI finally succeeded. Sorry for the delay. https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.12.2a
