### ISSUE TITLE
Section crossrefs working with docx but not pdf

### ISSUE THREAD

**Issue by jpk3333** [lierdakil/pandoc-crossref#346]
Despite not having this problem a week or so ago, I've just noticed that pandoc-crossref for some reason is not working when I use pandoc to convert markdown to pdf. But it is working fine when I use pandoc to convert the same markdown to docx.

MWE:

```

> # Section I {#sec:1}
> 
> A reference to [@sec:1]. A reference to @johansson1991.
> 
> # References

```

This gives the following for docx using "pandoc test.md --filter pandoc-crossref --citeproc --bibliography=bibliography.bib -o output.docx":

<img width="796" alt="Screen Shot 2022-03-15 at 7 45 22 AM" src="https://user-images.githubusercontent.com/99686982/158381204-35837a62-8437-4363-866c-9a1bef9103be.png">

But gives this for pdf using "pandoc test.md --filter pandoc-crossref --citeproc --bibliography=bibliography.bib -o output.pdf":

<img width="356" alt="Screen Shot 2022-03-15 at 7 45 02 AM" src="https://user-images.githubusercontent.com/99686982/158381478-32d27f24-32e4-4bcd-ba04-e27b0becd0f4.png">

Like I said, this wasn't happening a week or so ago. I've tried using all the versions of pandoc-crossref I've used in that time period, and none work. I know this is bizarre. Any idea what might be going on? Thanks so much, and sorry if I'm doing something wrong!

**Comment by jpk3333** [comment]
I discovered the problem (or at least how to work around it). I can convert md to pdf with perfect section crossrefs if my YAML includes "numbersections: true" with "numbersections" written _without_ camel case. But in order to convert md to docx without receiving an error when opening up the docx, I must write "numberSections" using camel case. 

The reason I didn't have a problem a few weeks ago is that [this Youtube video](https://youtu.be/HllCrrXui2g?t=234) (which should start at 3m54s) warned me that the Pandoc-crossref documentation seemed to be mistaken in calling for camel case. I think what I've discovered is that, for some reason, camel case is required for docx, but must be avoided for pdf.

**Comment by lierdakil** [comment]
That YouTube video is wrong... `numbersections` works with LaTeX output due to a chain of coincidences. What you're _supposed_ to use is `--number-sections` command-line switch. Pandoc-crossref uses `numberSections`, but LaTeX is special in that numbering is offloaded to LaTeX, so pandoc-crossref's `numberSections` doesn't affect LaTeX output.

**Comment by jpk3333** [comment]
Ah, Ok. So if I'm following, you're saying: Whether you're moving from md to pdf or md to docx, you should use the `--number-sections` command-line switch.

I just tried that (after removing any reference to numbering sections from my YAML header), and it worked for both pdf and docx output. Thanks!

**Comment by lierdakil** [comment]
> Whether you're moving from md to pdf or md to docx, you should use the --number-sections command-line switch.

With LaTeX, you _have_ to use `--number-sections`. With docx, you have an option of numbering sections with pandoc-crossref (via `numberSections` metadata option) _instead_ of `--number-sections`. That said, pandoc-crossref's `numberSections` option was introduced primarily for output formats where `--number-sections` doesn't work or when you need to do something non-standard (which is relatively straightforward with LaTeX via `header-includes`, but not necessarily so with other formats)

**Comment by jpk3333** [comment]
Thank you!
