### ISSUE TITLE
Allow pandoc 2.19

### ISSUE THREAD

**Issue by sternenseemann** [lierdakil/pandoc-crossref#350]
Seems like pandoc-crossref builds fine with that pandoc version.

**Comment by lierdakil** [comment]
It's not out yet, afaict, which means that might change by the time it's released. When 2.19 is out, I'll bump the version bounds if everything's fine (i.e. it builds and all tests pass). Feel free to build with `--allow-newer` in the meantime.

**Comment by sternenseemann** [comment]
Oh, I meant to say 2.17, just assumed 2.19 was already out (usually upper bounds are the problems I run into…).

**Comment by lierdakil** [comment]
Some tests on current pandoc-crossref version [don't pass](https://github.com/lierdakil/pandoc-crossref/pull/348) on 2.17. See the [release notes](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.13.0). Again, `--allow-newer` works in a pinch, but the recommendation is to just update to pandoc-2.18.

**Comment by sternenseemann** [comment]
Hm, we could I guess downgrade pandoc-crossref; pandoc 2.17 is a given due to Stackage LTS 19.
