### ISSUE TITLE
Version for pandoc 2.18

### ISSUE THREAD

**Issue by austinjp** [lierdakil/pandoc-crossref#354]
Hi. As per the readme, this issue is just to track any planned release of `pandoc-crossref` compiled against [Pandoc 2.18](https://github.com/jgm/pandoc/releases/tag/2.18) which is the latest release at the time of raising this.

**Comment by lierdakil** [comment]
:thinking: https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.13.0 is built against pandoc 2.18

**Comment by austinjp** [comment]
Hmm, apologies! I had multiple versions of both `pandoc` and `pandoc-crossref` installed at the time. Can't reproduce now. Closing! :)
