### ISSUE TITLE
Create new release compiled with Pandoc 2.19

### ISSUE THREAD

**Issue by hschwentner** [lierdakil/pandoc-crossref#359]
Pandoc 2.19 is out and it would be great to have a release of pandoc-crossref that is compiled with this new version.

**Comment by lierdakil** [comment]
Sorry it took a month, I was out of town and then had some health issues. I'll try to get a build out in a bit.

**Comment by lierdakil** [comment]
The new build is up: https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.13.0a

**Comment by hschwentner** [comment]
Thanks a lot!
