### ISSUE TITLE
brew version incompatibility

### ISSUE THREAD

**Issue by piccolbo** [lierdakil/pandoc-crossref#362]
When running pandoc from the latest update in brew one gets

```
WARNING: pandoc-crossref was compiled with pandoc 2.18 but is being run through 2.19.2. This is not supported. Strange things may (and likely will) happen silently.
```

Workaround is downgrading to 2.18. Platform is Mac OS monterey.
Looks like a new instance of #253 

It would be nice to get to the root cause of this instead of fixing breakage every time a pandoc update happens. It certainly isn't good user experience. I personally only do brew downgrades for pandoc and have to research how it's done every time, because it is not a single command, more like 4 commands. In this case specifically, I needed a new feature in 2.19 (I found a way around that). Not sure why there is this tight coupling between two software artifacts, I am not a haskell expert. If the dep can't be made more accepting (>=), then typically they need to be packaged together, taking from my experience with other languages. This is related https://github.com/jgm/pandoc/issues/7637 but it seems to reject a solution to this problem in favor of a completely new, delayed solution for crossreferencing. CC @jgm in case he wants to chip in. Thanks

**Comment by lierdakil** [comment]
This is something that the homebrew crew needs to figure out, there's not all that much we can do on our end. We (me and @jgm) are not affiliated with homebrew. See #360 and links there for a (very brief) discussion of the topic. Or you might try precompiled binaries on [this here releases page](https://github.com/lierdakil/pandoc-crossref/releases) if you want.
