### ISSUE TITLE
What to do when code blocks produce figures

### ISSUE THREAD

**Issue by piccolbo** [lierdakil/pandoc-crossref#363]
I think this is just an unpredictable interaction of two filters rather than a bug in any of them, but I am hoping that someone smarter has a solution. Sorry if an issue is not the correct forum for this. I am using of course pandoc-crossref together with diagram-generator. A code block with a class .graphviz containing dot language statements will be rendered as a graph. From the point of view of crossreferencing, that's a figure but it is referred to as a lst, which is confusing for the reader. Suggestions? Thanks.

**Comment by piccolbo** [comment]
possible duplication of #282, looking into it.

**Comment by piccolbo** [comment]
Looks like my problem has been solved two years ago. If I use `#lst:something` cross-ref correctly points to a listing (which is instead a figure). If I replace lst with fig or Fig I get an undefined crossref. Will prepare MRE

**Comment by lierdakil** [comment]
So, uh, make sure you're running pandoc-crossref after the diagram-generator. The order of filters specified on CLI matters.

**Comment by piccolbo** [comment]
That was it, thanks. Could you elaborate on that "matters" a little for my education? If I am using 10 filters, should I try all the 10! permutations? Or is there a logic to it? Thanks

**Comment by lierdakil** [comment]
There is logic behind it, but by "matters" I meant that filters are applied in the order they're specified on the CLI. Which filters to run first depends on what you want to achieve and how those filters work.

With pandoc-crossref and digram-generator the logic is pretty straightforward: running pandoc-crossref first, it sees a listing and treats it as such; that listing is later turned into a diagram by diagram-generator, but pandoc-crossref has no way of knowing that. Running pandoc-crossref later, it sees a diagram -- it doesn't even know that this diagram was ever a block of code in the first place.

The crucial thing to understand is that each filter runs individually, taking the document output by the previous filter, processing it, and passing the result on to the next filter (or to pandoc for final output if it's the last one). There's no way for filters to talk to each other in this model, so each has to work as if it was the only one in the chain. It's slightly more complicated in practice, but that's the gist of it.

Very generally speaking, you want to run content-generating filters (like diagram-generator) first, content-modifying filters second, content-referencing filters (like crossref and citeproc) last. Obviously, there are exceptions to this general guideline, but those are usually self-explanatory if you keep the above in mind.
