### ISSUE TITLE
change language of "Figure:" in caption?

### ISSUE THREAD

**Issue by kurokirasama** [lierdakil/pandoc-crossref#366]
Hi, is it possible to change the language of the word "Figure" within a caption?

**Comment by lierdakil** [comment]
See https://lierdakil.github.io/pandoc-crossref/#item-title-format, https://lierdakil.github.io/pandoc-crossref/#reference-format, https://lierdakil.github.io/pandoc-crossref/#settings-file.

**Comment by kurokirasama** [comment]
thanks!
