### ISSUE TITLE
cleveref must be loaded after hyperref

### ISSUE THREAD

**Issue by mcnesium** [lierdakil/pandoc-crossref#369]
I am only here because Google found me [that line in the changelog](https://github.com/lierdakil/pandoc-crossref/blob/master/CHANGELOG.md?plain=1#L25-L27).

So I added the latest release to the Docker image:

    COPY pandoc-crossref /usr/local/bin/pandoc-crossref

and am now running pandoc-crossref v0.3.14.0 together with pandoc 2.19.2 within `pandoc/latex` image ([`476a9c7ce3ec`](https://hub.docker.com/layers/pandoc/latex/latest/images/sha256-476a9c7ce3ec81ebd39205a0244c272e4638599a27846abbb906fba650404bd6?context=explore)).

Unfortunately it still says 

> Error producing PDF.
> ! Package cleveref Error: cleveref must be loaded after hyperref!.

Is that even related to this filter? If so, what do I need to do to apply the fixed version of it?

**Comment by lierdakil** [comment]
> Is that even related to this filter?

Unless you're doing `-Fpandoc-crossref -Mcref` or equivalent, then no.

**Comment by lierdakil** [comment]
Apparently you're using pandoc-secnos. Well, then no, unrelated. That said, this issue is fixed in pandoc-crossref, and IIUC the feature set is pretty close, so feel free to give it a spin instead of pandoc-secnos if you're so inclined.
