### ISSUE TITLE
Support pandoc 3.1.1

### ISSUE THREAD

**Issue by chenrui333** [lierdakil/pandoc-crossref#378]
While [upgrading pandoc to 3.1.1](https://github.com/Homebrew/homebrew-core/pull/124889), I've found some warnings in the output.

```
WARNING: pandoc-crossref was compiled with pandoc 3.1 but is being run through 3.1.1. This is not supported. Strange things may (and likely will) happen silently.
```

build log, https://github.com/Homebrew/homebrew-core/actions/runs/4339564816/jobs/7577364092

**Comment by lierdakil** [comment]
@amine-aboufirass this is homebrew-related, there is some caching weirdness happening there which I don't claim to understand. For now, we just settled on homebrew depending on me cutting new tags of pandoc-crossref each pandoc release, which I'd do anyway to produce binaries. FWIW, I appreciate the notification, as I don't really track pandoc releases nowadays.

@chenrui333 I'll cut a new tag in the next few days.

**Comment by lierdakil** [comment]
https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.15.1a is live. Apologies for the hold-up.
