### ISSUE TITLE
Feature request: one row of subfigures side-by-side

### ISSUE THREAD

**Issue by hhirtz** [lierdakil/pandoc-crossref#381]
Continuation of #60, the syntax for side-by-side subfigures only works when there are more than one row.

This works:

```
# Figures

<div id="fig:latex">
![cool caption](/tmp/LaTeX_logo.svg.png){#fig:logo1 width=40%}
![cooler caption](/tmp/LaTeX_logo.svg.png){#fig:logo2 width=40%}

![cool caption](/tmp/LaTeX_logo.svg.png){#fig:logo3 width=40%}
![cooler caption](/tmp/LaTeX_logo.svg.png){#fig:logo4 width=40%}

Copies of the LaTeX logo
</div>

Those logos are different I swear. Especially [@fig:logo1] and [@fig:logo2].
```

![screen-20230317151723](https://user-images.githubusercontent.com/51088794/225930998-5f7a8267-b331-4654-a9eb-9f1147ce29c6.png)

But this doesn't (I only deleted the second row of images, notice how the refs are now broken):

```
# Figures

<div id="fig:latex">
![cool caption](/tmp/LaTeX_logo.svg.png){#fig:logo1 width=40%}
![cooler caption](/tmp/LaTeX_logo.svg.png){#fig:logo2 width=40%}

Copies of the LaTeX logo
</div>

Those logos are different I swear. Especially [@fig:logo1] and [@fig:logo2].
```

![screen-20230317151738](https://user-images.githubusercontent.com/51088794/225931123-caabe832-08f4-4a91-8e1d-9a47dd69da46.png)

The workaround I use now is to insert no-op latex `$\text{}$` as a second paragraph, although it seems a HTML comment `<!-- hack -->` does the trick too:

```
# Figures

<div id="fig:latex">
![cool caption](/tmp/LaTeX_logo.svg.png){#fig:logo1 width=40%}
![cooler caption](/tmp/LaTeX_logo.svg.png){#fig:logo2 width=40%}

$\text{}$

Copies of the LaTeX logo
</div>

Those logos are different I swear. Especially [@fig:logo1] and [@fig:logo2].
```

![screen-20230317151757](https://user-images.githubusercontent.com/51088794/225931337-44df8c1e-1dcd-4de3-b427-367809306c51.png)

Here's the command I'm using to convert from markdown to pdf:

```
pandoc --filter pandoc-crossref --citeproc test.md -o test.pdf
```

I'm using pandoc v3.1 and pandoc-crossref v0.3.15.1a.

**Comment by lierdakil** [comment]
Hi! Thanks for the report! You've actually stumbled upon a bug introduced when updating to pandoc 3.0 format. I've pushed a commit that should fix this to `master`. I'll try to push out a release in a bit. If you need it ASAP, you could grab artefacts from https://github.com/lierdakil/pandoc-crossref/actions/runs/4460009114 once that's done (should be within the next hour or so)

**Comment by hhirtz** [comment]
Thank you very much! Works like a charm with v0.3.15.2
