### ISSUE TITLE
Centering captions for HTML output

### ISSUE THREAD

**Issue by awa5114** [lierdakil/pandoc-crossref#383]
Is there a way to center captions for code blocks, figures and tables? Why is the default setting aligned to the left?

**Comment by lierdakil** [comment]
> Why is the default setting aligned to the left?

Because that's the browser default :shrug: 

Add something like this to metadata?

```yaml
header-includes:
- '<style>figure, .listing > p { text-align: center ; }</style>'
```

Table captions are already centred by default in most browsers.
