### ISSUE TITLE
Orgmode cross references

### ISSUE THREAD

**Issue by awelormro** [lierdakil/pandoc-crossref#384]
Hello, and thanks for the plugin, works well in almost all the filetypes I tested, but in org files the cross references are not created, whem I export from an org file to docx the cross references are not created, Is this implemented yet?

**Comment by lierdakil** [comment]
I don't use org-mode personally, hence take this with a grain of salt, but try using `[cite:@fig:figureRef]` as a reference. See also https://github.com/lierdakil/pandoc-crossref/issues/357#issuecomment-1200484928

**Comment by awelormro** [comment]
Sorry to answer after a few days, as I could see, figure captions works well, but in the table captions case is not working as expected, Shall I need to open a new issue to check this?

**Comment by awelormro** [comment]
Edit: The main config was putting the original caption style, like this

```
#+NAME: tabladedatos
#+CAPTION: My table caption {#tbl:tabladedatos}
#+LABEL: {#tbl:tabladedatos}
| Columna 1 | Columna 2 | Columna 3 |
|-----------+-----------+-----------|
| Fila 1    | Valor 1   | Valor 2   |
| Fila 2    | Valor 3   | Valor 4   |


   This is a reference to Table [cite:@tbl:tabladedatos] .
```
