### ISSUE TITLE
Arrange two images vertically for figure

### ISSUE THREAD

**Issue by julianbarg** [lierdakil/pandoc-crossref#391]
As stated above. I seem to be unable to do this. My preferred solution would be the same as the long-form syntax for creating a table with a fenced div, i.e.:

:::{#fig:label}
\!\[](figure1.png)

\!\[](figure2.jpg)
: Caption
:::

pandoc-crossref v0.3.16.0 git commit UNKNOWN (UNKNOWN) built with Pandoc v3.1.2, pandoc-types v1.23 and GHC 8.8.4

pandoc 3.1.2
Features: -server +lua
Scripting engine: Lua 5.4

**Comment by lierdakil** [comment]
The `:` before the caption messes with Pandoc, it parsers it as a definition list. By convention, the last paragraph in a subfigures div is treated as caption by pandoc-crossref without any extra markers.

What is your target output format?

This seems to work for html:

```markdown
---
subfigGrid: true
---

:::{#fig:label}
![](figure1.png)

![](figure2.jpg)

Caption
:::
```

For LaTeX, don't set `subfigGrid`.

**Comment by julianbarg** [comment]
That works! Brilliant! It seems to change how some other illustrations get processed, but overall great result. Might be worth adding that example to the docs.
