### ISSUE TITLE
Incorrect equation reference number in main text when convert .tex to .docx

### ISSUE THREAD

**Issue by christina-0725** [lierdakil/pandoc-crossref#398]
I have pandoc 3.1.6 and pandoc-crossref v0.3.16.0 in my pc.
I convert ``.tex`` to ``.docx`` by using command as follows:
```
pandoc temp.tex -o output.docx \
        --bibliography ../../latex/reference.bib \
        --filter pandoc-crossref -M tableEqns -M autoEqnLabels -t docx+native_numbering\
        --citeproc  --csl ../../latex/ieee.csl \
        --number-sections -M reference-section-title=Reference\
        --reference-doc ../../latex/ref.docx
```
The .tex file is as follows:
```
...
This is Eq.\ref{eq1}

\begin{equation}
    {a + b = c}\label{eq1}
\end{equation}
...
```

And obtained .docx file is as follows:
```
This is Eq.[eq1]
a+b=c	(1)
```
The equation reference number in main text is ``[eq1]``, same as the label name in ``.tex`` file, but  the equation number I want to get is ``1``. But I got correct table, figure and reference number in ``.docx`` file.
What command should I use or how should I fix ``.tex`` file to get the correct  equation reference number in main text?
Thanks for your help!

**Comment by lierdakil** [comment]
See #250. TL;DR: pandoc-crossref doesn't support LaTeX as input format, but you can bludgeon it into doing what you want with a bit of prefiltering, see #250 for some examples.
