### ISSUE TITLE
latex with extensions is not recognized as latex by pandoc-crossref

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#4]
Since latex is the interemediate output format for pdf, `\label` and `\ref` could be used for pdf output, too.

Implementation should be straight forward, but I'm just beginning to learn Haskell.

**Comment by lierdakil** [comment]
Pandoc does not internally have dedicated "pdf" format, so "latex" filter works for both. You might notice that [demo pdf][1] is properly typeset.

[1]:http://lierdakil.github.io/pandoc-crossref/output.pdf

**Comment by tolot27** [comment]
You are right, demo.pdf is properly typeset. Unfortunately, my document not. I got "Figure 1.1: Figure 1: ..." and the reference to the figure is not a link.

I'll figure out, why.

**Comment by lierdakil** [comment]
Try specifying output format explicitly, if you do not already. It really should work.

`pandoc -t latex -o output.pdf`

**Comment by tolot27** [comment]
Ha, found it.

```
pandoc -t latex+definition_lists
```

The extension `definition_lists` seem to automatically add labels to all figures. If pandoc-crossref then adds an additional label, the hyperref link will not work.

**Comment by tolot27** [comment]
I was wrong. The extension `definition_lists` itself does not add labels to figures. Only in combination with pandoc-crossref, it does not work because no label at all is added. Instead, the caption is "hardcoded" without any label:

```latex
\begin{figure}[htbp]
\centering
\includegraphics{img1.jpg}
\caption{Figure 1: First figure}
\end{figure}
```

**Comment by lierdakil** [comment]
Right. Forgot about extensions. Sigh. I'll fix it.

**Comment by tolot27** [comment]
Maybe the bug should be renamed to a more appropriate name?

Ah, you did this right now. :+1:
