### ISSUE TITLE
.docx support?

### ISSUE THREAD

**Issue by petobens** [lierdakil/pandoc-crossref#41]
Hi,  are `.docx` files supported?. With the following `foo.tex` file:

```tex
\documentclass{article}
\usepackage{amsmath}
\usepackage{cleveref}
\begin{document}
\begin{equation}
\label{eq:first}
  1 + 1 = 2
\end{equation}
\cref{eq:first}
\end{document}
```

If I run `pandoc -s --filter pandoc-crossref foo.tex -o foo.docx` I get:
![asdasdasdasdas](https://cloud.githubusercontent.com/assets/2583971/11571561/cf920942-99db-11e5-82af-2e08161f3837.png)

Thanks!

**Comment by lierdakil** [comment]
pandoc-crossref does not, and likely *will* not, support with any input formats besides Markdown.

Outputting to docx works though.

**Comment by petobens** [comment]
@lierdakil  ok, thanks anyway.
