### ISSUE TITLE
Compatibility with recent pandoc 3.1.9 release

### ISSUE THREAD

**Issue by finiteabelian** [lierdakil/pandoc-crossref#410]
pandoc 3.1.9 was released on 27 Oct 2023.  Can pandoc-crossref be update to support the new version?

**Comment by jankap** [comment]
I just tried it out to use the 3.1.9 with pandoc-crossref 0.3.17 and could not see immediate issues.

**Comment by lierdakil** [comment]
Sorry for seemingly falling off the face of the Earth for the past couple months, didn't have any bandwidth to dedicate to this. A new build for 3.1.11 should be up in a few hours.

**Comment by lierdakil** [comment]
The new build [is up](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.17.0a).

**Comment by jankap** [comment]
Dear @lierdakil thank you so much for your work!
