### ISSUE TITLE
Figure captions in ODT output should have 'Figure' or 'FigureCaption' style 

### ISSUE THREAD

**Issue by chenyhsu** [lierdakil/pandoc-crossref#414]
I tried to convert markdown to odt.

When add a table with caption, the table caption got table style 'TableCaption' , but for figure caption, only  'Default Paragraph Style' applied.

Is it possible to get figure captions with proper style set in output odt files?

**Comment by lierdakil** [comment]
This is likely a Pandoc issue. Can't reproduce with pandoc 3.1.11, so try that perhaps?

**Comment by chenyhsu** [comment]
Sorry, my fault.
It turns out that I forgot to add `FigureCaption` and `FigureWithCaption` in my template.
(But I don't find any related information in the documentation)
