### ISSUE TITLE
Make grid tables visible

### ISSUE THREAD

**Issue by awelormro** [lierdakil/pandoc-crossref#418]
Hello there, sorry for bothering again, but I've found an issue with grid tables, here is a quick example:

```
+-----------+-----------+
| row1.  | row2|
+=====+=======+
| Lorem| Ipsum|
+----------+----------+
: caption {#tbl:pipetable1}
```
Just cannot recognize it, also happens in orgmode, Is there a way to make it recognizable? Sort a lua filter or something else? I've partially solutioned it for docx files creating an empty pipe table and deleting just the table, but with more tables is quite problematic. Thanks for the plugin!

**Comment by paul-kelleher** [comment]
The issue may be with Pandoc (or with your table syntax) and not pandoc-crossref. I think cross-ref will not treat a table as a table if pandoc isn't cool with how it's constructed.

Use the version of your table that I entered [here](https://pandoc.org/try/?params=%7B%22text%22%3A%22%2B-------%2B-------%2B%5Cn%7C+row1++%7C+row2++%7C%5Cn%2B%3D%3D%3D%3D%3D%3D%3D%2B%3D%3D%3D%3D%3D%3D%3D%2B%5Cn%7C+Lorem+%7C+Ipsum+%7C%5Cn%2B-------%2B-------%2B%22%2C%22to%22%3A%22docx%22%2C%22from%22%3A%22markdown%22%2C%22standalone%22%3Atrue%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D), and see if that works in your document.

**Comment by awelormro** [comment]
The real deal comes with long header text, when you need a long string in the headers, sort of:

```
+-------+-------+
| row1  | row2  |
| cosal | cosal |
+=======+=======+
| Lorem | Ipsum |
+-------+-------+

```

it is not recognized, any way to make tables with long text in headers?

**Comment by paul-kelleher** [comment]
I use this website: https://www.tablesgenerator.com/text_tables

**Comment by awelormro** [comment]
Sorry to bother, it was a Pandoc table recognition, now us solved
