### ISSUE TITLE
Mac can not open "pandoc-crossred" because it can not vertify the developer?

### ISSUE THREAD

**Issue by Hustdeng** [lierdakil/pandoc-crossref#419]
as the title.
![Uploading WechatIMG970.jpg…]()

**Comment by paul-kelleher** [comment]
See the "Note" at the bottom of this page:
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by lierdakil** [comment]
I assume this is resolved. I don't really plan to sign up for Apple's developer program anytime soon. Thanks @paul-kelleher for the link.

**Comment by Hustdeng** [comment]
Thank you for your suggestion. It works now!!
