### ISSUE TITLE
In-paragraph equation number needed

### ISSUE THREAD

**Issue by xoox** [lierdakil/pandoc-crossref#42]
pandoc-crossref is a great unified filter for figure/table/equation numbering.

But equation label only works if display math and label specification are in a paragraph of its own. That results in a big skip before the equation and a new paragraph after it,  whereas the equation and texts around it should remain in a same paragraph in most cases.

Would you please make the equation labels can be used with equations NOT in a paragraph of its own?

It'd be nice if equation labels can be used as [pandoc-eqnos](https://github.com/tomduck/pandoc-eqnos) does, its [demo.md](https://raw.githubusercontent.com/tomduck/pandoc-eqnos/master/demos/demo.md) shows this feature.

**Comment by lierdakil** [comment]
This won't be easy. I'll see what I can do.

**Comment by lierdakil** [comment]
Okay, v1.6.0 should do that. Hopefully I didn't break anything by that ^^"

**Comment by xoox** [comment]
That's awesome.
I've tested it with latex format.

Then this line "This only works if display math and label specification are in a paragraph of its own."
can be safely removed from [README.md](https://github.com/lierdakil/pandoc-crossref/blob/master/README.md)
