### ISSUE TITLE
New Version of Pandoc

### ISSUE THREAD

**Issue by thiboverbeerst** [lierdakil/pandoc-crossref#429]
Hello.

Could you kindly release a new version for Pandoc "**3.1.12.3**"?

Kr,
Thibo 👋

_PS: Thank you for creating such a valuable resource for us all to benefit from._ 😊

**Comment by lierdakil** [comment]
[Done](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.17.0f). Thanks for the heads-up.
