### ISSUE TITLE
Support for pandoc/pandoc-types 1.16

### ISSUE THREAD

**Issue by felixonmars** [lierdakil/pandoc-crossref#43]
A major new release of pandoc/pandoc-types now comes. Would be really appreciated to support them!

**Comment by lierdakil** [comment]
Package candidate is [available](https://hackage.haskell.org/package/pandoc-crossref-0.1.6.1/candidate). I will be grateful for testing before I release it.

You can force cabal to install package candidate by directing it to straight to distribution, like this:

```
cabal install http://hackage.haskell.org/package/pandoc-crossref-0.1.6.1/candidate/pandoc-crossref-0.1.6.1.tar.gz
```

**Comment by truemoid** [comment]
Works nicely thanks

**Comment by felixonmars** [comment]
:+1: works here, thanks :)

**Comment by lierdakil** [comment]
v0.1.6.2 is on Hackage.

v0.1.6.1 had some problems with testsuite on pandoc<1.16.

Note that GHC 7.4 build is no longer tested since this release, since managing dependency hell in travis is hell squared.
