### ISSUE TITLE
Pandoc 3.2 warning

### ISSUE THREAD

**Issue by jlam29** [lierdakil/pandoc-crossref#437]
Dear, 
Just to inform.
I have installed version pandoc (3.2) and pandoc-crossref (v0.3.17.1)
Here is the return : 
> WARNING: pandoc-crossref was compiled with pandoc 3.1.13 but is being run through 3.2. This is not supported. Strange things may (and likely will) happen silently

**Comment by lierdakil** [comment]
[A new build](https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.17.1a) is out.

**Comment by vedranmiletic** [comment]
Wow, that was fast, thanks!
