### ISSUE TITLE
LaTeX to DOCX， \eqref{label} to be Eq.[label] not Eq.(number)? How to DO!

### ISSUE THREAD

**Issue by pbpf** [lierdakil/pandoc-crossref#438]
I'm no expert, but often need to convert latex to docx, where formula references can't be converted to the correct number, although -M autoEqnLabels can generate numbers for the formula itself.

``` a.tex
\documentclass{article}
 

\begin{document}

This is a test for Eq.~\eqref{eq:test}
\begin{equation}
    x=1\label{eq:test}
\end{equation}

\end{document}
```
Let us do
```
pandoc a.tex    -M autoEqnLabels    --filter pandoc-crossref -o output.docx
```
Then, you got! 
![image](https://github.com/lierdakil/pandoc-crossref/assets/6541871/87fd6392-7a2a-47bb-9308-cbc9c42403c3)

**Comment by lierdakil** [comment]
Latex is not officially supported as an input format, but see https://github.com/lierdakil/pandoc-crossref/issues/250.
