### ISSUE TITLE
insert a new figure in word

### ISSUE THREAD

**Issue by thunderbolt-fire** [lierdakil/pandoc-crossref#439]
excuse me, I find a problem that the Id of figure can't change when I insert a figure before  it in word.
![image](https://github.com/lierdakil/pandoc-crossref/assets/94913283/de3766aa-0f2b-4aed-8821-22043d3547bf)

**Comment by lierdakil** [comment]
When converting Markdown to Word, the figure numbers are typeset as plaintext, not Word's counters. So, naturally, if you then edit the Word document, the numbers will not reflect the edit. This is entirely expected.

Now, as for rationale, basically OOXML is brittle and complicated, supporting native OOXML counters is not something I can do, especially not with all the templating options pandoc-crossref supports for captions.
