### ISSUE TITLE
man page not present in released source tarballs

### ISSUE THREAD

**Issue by vedranmiletic** [lierdakil/pandoc-crossref#449]
man page seems to be missing in source tarballs and is only shipped in (Linux) binary tarballs. Is that intentional? If not, could it be fixed so FreeBSD Ports can ship [pandoc-crossref with man page](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=281077)?

**Comment by lierdakil** [comment]
The man page is built from `docs/index.md` as a CI job. Source tarball is generated by GitHub, and I'd prefer to avoid checking in generated files if I can help it. FreeBSD Ports could generate a man page as a separate build step (it's easy enough to run `pandoc -s -t man docs/index.md -o pandoc-crossref.1.man`, as pandoc is a prerequisite anyway).

Now, the documentation is actually baked into the binary itself, running `pandoc-crossref --man` will dump the text. It's not in manpage format, though. You could also do `pandoc-crossref --man-html` to open a rendered html version in your default browser if gui is available. I can be convinced to bake-in man format, too, if that would be somehow easier.

**Comment by lierdakil** [comment]
Some other alternatives from the top of my head:

- attaching the manpage as a release artifact, separate from the binary. That would be the next easiest option for me, after "do nothing and letting downstream figure this out".
- adding a CI job to build a source tarball with the manpage included. Not sure how this will pan out, though, downstream has largely settled into pulling github-provided source tarballs a long time ago.

**Comment by vedranmiletic** [comment]
> (it's easy enough to run `pandoc -s -t man docs/index.md -o pandoc-crossref.1.man`, as pandoc is a prerequisite anyway).

Yes, pandoc seems to be installed by cabal when building pandoc-crossref. That would be an option. I will check.

**Comment by vedranmiletic** [comment]
Building it from `docs/index.md` seems to be an acceptable solution. Thanks for your help in this instance, and thanks overall for developing this awesome filter!
