### ISSUE TITLE
Loosen restrictions on yaml settings

### ISSUE THREAD

**Issue by scoavoux** [lierdakil/pandoc-crossref#45]
This is not really an issue, more of a feature suggestion. Currently, if the yaml setting file starts with an empty line or a line of three dashes (like yaml front matter in a pandoc document), it is silently ignored. Subsequent blank lines do not seem to matter, but options are not read after a --- line somewhere in the yaml file.

It would be great if:
+ the parser could ignore blank and --- lines in the yaml, and still work (though I am not sure this would follow yaml guidelines, I don't know much about it)
+ at least give a warning if a -M "crossrefYaml=settings.yaml" is given but no option has been found.

We could also mention in the README that the yaml file's first line needs to be setting an option.

**Comment by lierdakil** [comment]
Problem is, I leverage Pandoc to parse settings file. While it could be possible to do this using "real" YAML parser, I fear this would be extremely redundant

**Comment by scoavoux** [comment]
I think I see what's happening. In this [file](https://github.com/lierdakil/pandoc-crossref/blob/1639174c0ed8ad2db3be4acec12449978f4a7405/src/Text/Pandoc/CrossRef/Util/Settings.hs), the yaml is surrounded by two --- lines, which will make it invalid if they are already there.

     let Pandoc dtve _ = readMarkdown def ("---\n" ++ yaml ++ "\n---")

No problem about doing something about the parser, but I still think it would be worth mentioning it in the README since it might cause trouble to some users. I'll make a pull request with that info. Thanks for the filter!
