### ISSUE TITLE
Error: pandoc-crossref: createProcess: posix_spawnp: failed (Bad CPU type in executable)

### ISSUE THREAD

**Issue by somelinguist** [lierdakil/pandoc-crossref#452]
Hi, I just tried installing prebuilt pandoc-crossref 0.3.18.0 along side pandoc 3.4 on macOS Sequoia, but I get the following error:

```
Error running filter pandoc-crossref:
pandoc-crossref: createProcess: posix_spawnp: failed (Bad CPU type in executable)
```

I'm on an Intel Mac. Should the prebuilt binaries work with Intel still, or are they only for Apple Silicon now?

I've made sure to go through the new Sequoia security/permission dance, and put pandoc-crossref on my path (suggestions for similar errors with Pandoc and LaTeX dependencies), but still get the error.

Any ideas?

Thanks!

**Comment by lierdakil** [comment]
Huh. I'm not a mac user, so I just take whatever comes out of CI. It was amd64 until recently, but apparently things changed silently, and now it's arm64.

I'll try to look into packaging amd64 for macOS at some point, but at the moment I'm insanely busy with my day job, so can't promise any specific timelines, unfortunately. In the meantime, I hear hombrew does a decent job of packaging pandoc and pandoc-crossref.

**Comment by somelinguist** [comment]
Hey, Thanks for writing back and for the explanation. 

No rush for the fix!

I found this topic which might be helpful: https://discourse.julialang.org/t/how-to-fix-github-actions-ci-failures-with-julia-1-6-or-1-7-on-macos-latest-and-macos-14/117019

It looks like it might be as simple as changing`macos-latest` in  `jobs.build.strategy.matrix.os` to `macos-13` or lower, which still uses Intel.

It loos like Pandoc's workflow is still using `macos-12`, which is what `macos-latest` apparently defaulted to until June: https://github.com/jgm/pandoc/blob/a37035caa1f94f564a17afe874d448dab0793b76/.github/workflows/release-candidate.yml#L80

The Julia discussion mentions several other nuanced possibilities that might work as well, but given that Pandoc is using a lower configuration, it might be sufficient just to follow them.

Thanks again!

**Comment by lierdakil** [comment]
CI now has x86_64 build for macOS. See https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.3.18.0b.

Please verify it works as expected when you have a chance, and close the issue if it does.

/cc @Krande, apparently I've beat you to it :sweat_smile:

**Comment by somelinguist** [comment]
Thanks for this! I just tried it out with pandoc 3.5 and works fine.
