### ISSUE TITLE
Sequential Numbering of Figures and Tables Ignoring Chapter in DOCX

### ISSUE THREAD

**Issue by Mingzefei** [lierdakil/pandoc-crossref#455]
Hello,

I am trying to convert a LaTeX document to DOCX using `pandoc` and `pandoc-crossref`, but I am encountering issues with the numbering format for figures and tables in the resulting DOCX file. My goal is to have sequential numbering (e.g., Fig. 1, Fig. 2, etc.) for figures and tables throughout the document, ignoring chapter numbers. However, despite trying multiple approaches, the output I get in the DOCX file still includes chapter numbers, like `Fig. 2.1` and `Tab. 2.1`.

Here are the methods I have tried so far according to [pandoc-crossref/#customization](https://lierdakil.github.io/pandoc-crossref/#customization):

### 0. Based Conversion Command
```bash
pandoc \
    ./main_modified.tex \
    -o ./out.docx \
    --filter pandoc-crossref \
    --number-sections \
    -M autoEqnLabels \
    -M tableEqns \
    -M reference-section-title=Reference \
    --bibliography=../ref.bib \
    --citeproc \
    -t docx+native_numbering
```
Result: `Fig. 2.1` and `Tab. 2.1`.

### 1. Tried `chapters=false`
```bash
pandoc \
    ./main_modified.tex \
    -o ./out1.docx \
    --filter pandoc-crossref \
    --number-sections \
    -M autoEqnLabels \
    -M tableEqns \
    -M reference-section-title=Reference \
    -M chapters=false \
    --top-level-division=section \
    --bibliography=../ref.bib \
    --citeproc \
    -t docx+native_numbering
```
Result: Still `Fig. 2.1`.

### 2. Tried `chaptersDepth=0`
```bash
pandoc \
    ./main_modified.tex \
    -o ./out2.docx \
    --filter pandoc-crossref \
    --number-sections \
    -M autoEqnLabels \
    -M tableEqns \
    -M reference-section-title=Reference \
    -M chaptersDepth=0 \
    --bibliography=../ref.bib \
    --citeproc \
    -t docx+native_numbering
```
Result: Still `Fig. 2.1`.

### 3. Tried `sectionsDepth=-1`
```bash
pandoc \
    ./main_modified.tex \
    -o ./out3.docx \
    --filter pandoc-crossref \
    --number-sections \
    -M autoEqnLabels \
    -M tableEqns \
    -M reference-section-title=Reference \
    -M sectionsDepth=-1 \
    --bibliography=../ref.bib \
    --citeproc \
    -t docx+native_numbering
```
Result: Still `Fig. 2.1`.

### Version Information:
```bash
pandoc-crossref v0.3.18.0 git commit UNKNOWN (UNKNOWN) built with Pandoc v3.5, pandoc-types v1.23.1 and GHC 9.6.6
pandoc 3.5
Features: +server +lua
```

I have tried adjusting the metadata options (e.g., `chapters=false`, `chaptersDepth=0`, and `sectionsDepth=-1`) to no avail. Despite these efforts, the figure and table references in the DOCX output still include chapter numbers.

Could you please advise on how I can configure the conversion to use sequential numbering for figures and tables, ignoring chapters?

Thank you!

**Comment by lierdakil** [comment]
Sorry for the late reply, this slipped through the cracks a bit.

See #250. TL;DR: `\ref` is handled by pandoc, pandoc-crossref doesn't really understand those. But using a simple pre-filter to convert `\ref` (and also `\eqref` etc) to something pandoc-crossref recognizes will get you passable results.

**Comment by lierdakil** [comment]
You can also consider using https://github.com/fncokg/pandoc-tex-numbering, which is purpose-built for LaTeX input.
