### ISSUE TITLE
Need help regarding equation numbering when converting latex to docx

### ISSUE THREAD

**Issue by xlucn** [lierdakil/pandoc-crossref#457]
I try to convert a simple tex file:
```tex
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation}
E = mc^2
\label{eq:mc2}
\end{equation}
\eqref{eq:mc2}
\end{document}
```
to a docx, with this command:
```sh
pandoc --filter pandoc-crossref demo.tex -o demo.docx
```
No warning appears, but the resulting docx does not number the equation:
![20241202_16h40m35s_grim](https://github.com/user-attachments/assets/bfdf0414-46cd-4347-8aa3-2764a11e84b5)

Is this case not supported by pandoc-crossref, or am I doing anything wrong? Help appreciated.

Other info
```
$ pandoc -v
pandoc 3.5
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/oliver/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
$ pandoc-crossref -v
pandoc-crossref v0.3.18.0 git commit UNKNOWN (UNKNOWN) built with Pandoc v3.5, pand
oc-types v1.23.1 and GHC 9.6.6
```

**Comment by lierdakil** [comment]
Please see #250. TL;DR: LaTeX is not technically supported as an input format, but you can get it 80+% there with a little bit of finagling.

**Comment by lierdakil** [comment]
You can also consider using https://github.com/fncokg/pandoc-tex-numbering, which is purpose-built for LaTeX input.

**Comment by xlucn** [comment]
Thanks a lot for those information! I will look into those workarounds or solutions.
