### ISSUE TITLE
Captions for code listings produce \begin{codelisting} which is not in the listings package

### ISSUE THREAD

**Issue by matthiasbeyer** [lierdakil/pandoc-crossref#47]
If I use either

```
Listing: Foo
```{#lst:mypython .python .numberLines}
..somecode...
```

Or
```
```{#lst:mypython .python .numberLines caption="Foo"}
...somecode...
```

This produces following latex compilation error:

```
! LaTeX Error: Environment codelisting undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.48     \begin{codelisting}

pandoc: Error producing PDF from TeX source
```

I cannot find any package for a `codelisting` environment with google, so would you please tell me how I can fix this?

For compiling to HTML, everything works as expected.

**Comment by lierdakil** [comment]
You need to run `pandoc` with `-s` (`--standalone`) option in order to include definitions for `pandoc-crossref`-specific environments. Alternatively, you can see [here](https://github.com/lierdakil/pandoc-crossref/blob/master/src/Text/Pandoc/CrossRef/Util/ModifyMeta.hs#L45) to figure out what the definition should be.

**Comment by matthiasbeyer** [comment]
Passing `--standalone` to pandoc does not solve the error.

**Comment by lierdakil** [comment]
I will have to ask for a minimal testcase then.

**Comment by matthiasbeyer** [comment]
I will try to deliver...

**Comment by matthiasbeyer** [comment]
https://gist.github.com/matthiasbeyer/193105fd42de66fdb1dd

This is as minimal as I can get in such a short time.

I'm using 

```
pandoc --version
pandoc 1.15.2.1
```

btw.

**Comment by lierdakil** [comment]
Apparently, you're using custom template. That explains things.

Add this to your template header (before `\begin{document}`, but probably after everything else)
```
$for(header-includes)$
$header-includes$
$endfor$
```

This will allow pandoc-crossref to include its definitions into your template.

You can also define `codelisting` environment yourself if you want. Again, see [here](https://github.com/lierdakil/pandoc-crossref/blob/master/src/Text/Pandoc/CrossRef/Util/ModifyMeta.hs#L45) for a general idea on how pandoc-crossref does that.

P.S. You also seem to be including `\usepackage{listings}` in your template. If you want to use that one, pandoc-crossref supports that, but needs some coercion. See https://github.com/lierdakil/pandoc-crossref#customization (in particular, `listings` metadata attribute)

**Comment by matthiasbeyer** [comment]
Maaah, the `header-includes`. Damn.

Thanks for your help, that fixed the error for me!

**Comment by matthiasbeyer** [comment]
Follow-up question: What if I do not have a custom template?

**Comment by qaisjp** [comment]
People that get here from Google will find my comment useful.

If you are using `include-in-header`, read this caveat: https://lierdakil.github.io/pandoc-crossref/#latex-output-and---include-in-header

The solution is to put your entire `include-in-header` file inside your metadata file.

It's also useful if you read the _bottom_ of the "Metadata blocks" section (in pandoc's docs itself) - https://pandoc.org/MANUAL.html#metadata-blocks, copied below:

> Raw content to include in the document’s header may be specified using `header-includes`; however, it is important to mark up this content as raw code for a particular output format, using the `raw_attribute` extension, or it will be interpreted as markdown. For example:
>
> ``````yaml
> header-includes:
> - |
>   ```{=latex}
>   \let\oldsection\section
>   \renewcommand{\section}[1]{\clearpage\oldsection{#1}}
>   ```
> ``````


----


> P.S. You also seem to be including `\usepackage{listings}` in your template. If you want to use that one, pandoc-crossref supports that, but needs some coercion. See [lierdakil/pandoc-crossref#customization](https://github.com/lierdakil/pandoc-crossref#customization) (in particular, `listings` metadata attribute)

This link is now: https://github.com/lierdakil/pandoc-crossref/blob/master/lib/Text/Pandoc/CrossRef/Util/ModifyMeta.hs

**Comment by vinayakakv** [comment]
Apart from @lierdakil's fix, I had to add

```
$if(highlighting-macros)$
$highlighting-macros$
$endif$
```
to solve `Shaded` environment undefined error, as suggested by <https://stackoverflow.com/a/47122900>.
