### ISSUE TITLE
The key "SoftBreak" was not found - after update to pandoc 1.16

### ISSUE THREAD

**Issue by HJAllen** [lierdakil/pandoc-crossref#50]
Working on a win 7 professional system with RStudio/R/rmarkdown/pandoc.  Updated to pandoc 1.16 and crossref 0.1.6.3 via cabal.  Seems something else needs to be updated. Result is:

```
pandoc-crossref.exe: Error in $[2][29]: The key "SoftBreak" was not found
pandoc.exe: Error running filter pandoc-crossref
Filter returned error status 1
Error: pandoc document conversion failed with error 83
```

Full output:

```
"C:/path/cabal/bin/pandoc" +RTS -K512m -RTS 2015HarshaText.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output 2015HarshaText.pdf --filter pandoc-citeproc --template "c:\path\default-1.14.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "c:\\;path\\HABsPDFheader.tex" --filter pandoc-crossref --variable "geometry:margin=1in" --bibliography "c:\\path\\HABs.bib" 
output file: 2015HarshaText.knit.md

pandoc-citeproc: reference fig:MCStruct not found
pandoc-crossref.exe: Error in $[2][29]: The key "SoftBreak" was not found
pandoc.exe: Error running filter pandoc-crossref
Filter returned error status 1
Error: pandoc document conversion failed with error 83
In addition: Warning message:
running command '"C:/path/pandoc" +RTS -K512m -RTS 2015HarshaText.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output 2015HarshaText.pdf --filter pandoc-citeproc --template "c:\path\latex\default-1.14.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "c:\\path\\HABsPDFheader.tex" --filter pandoc-crossref --variable "geometry:margin=1in" --bibliography "c:\\path\\HABs.bib"' had status 83 
Execution halted
```

**Comment by lierdakil** [comment]
It seems that pandoc-crossref was built with different version of pandoc than you're running. Make sure that you build pandoc and pandoc-crossref in the same sandbox. Also run `ghc-pkg check` if you're not using sandboxes, it's possible that some packages are broken by updates.

**Comment by HJAllen** [comment]
I reinstalled crossref and it will process and create the pdf. However it does not label the figures appropriately nor insert the reference.  Unfortunately, I haven't used a sandbox, in fact I am not familiar with it.  Perhaps I need to wipe the slate clean and start over.

**Comment by lierdakil** [comment]
Let me know if it doesn't help. It's always possible I messed up somewhere.

**Comment by lierdakil** [comment]
Wait. I think I might have misinterpreted error log you provided. Sorry. Sleep deprivation does that. Could you show what command do you use to run Pandoc?

**Comment by lierdakil** [comment]
Okay... Could you change order of filters so that pandoc-crossref appears *before* pandoc-citeproc and test that one out?

**Comment by HJAllen** [comment]
I am using Rstudio and don't know exactly how the pandoc command is generated.  I am looking into it...  Thanks for the help!

**Comment by HJAllen** [comment]
i was able to run the command manually but didn't fix the problem.  Here is a bit more description of what I am doing.

markdown snippet:
```
####Structure

Microcystins are cyclic heptapeptides @fig:MCStruct with @campos_molecular_2010

![Microcystin Structure](../figures/microcystin.png){#fig:MCStruct}
```

output in pdf

Structure
Microcystins are cyclic heptapeptides ??? with [1]

command:
```
"C:/path/cabal/bin/pandoc" +RTS -K512m -RTS HABsLitReview.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output HABsLitReview.pdf --filter pandoc-citeproc --template "c:\path\R\library\rmarkdown\rmd\latex\default-1.14.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "c:\\path\\HABsPDFheader.tex" --filter pandoc-crossref --variable "geometry:margin=1in" --filter pandoc-citeproc --bibliography "c:\\path\\HABs.bib"
```

**Comment by lierdakil** [comment]
You're using `pandoc-citeproc` twice here:

"C:/path/cabal/bin/pandoc" +RTS -K512m -RTS HABsLitReview.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash-implicit_figures --output HABsLitReview.pdf **--filter pandoc-citeproc** --template "c:\path\R\library\rmarkdown\rmd\latex\default-1.14.tex" --highlight-style tango --latex-engine pdflatex --include-in-header "c:\\path\\HABsPDFheader.tex" --filter pandoc-crossref --variable "geometry:margin=1in" **--filter pandoc-citeproc** --bibliography "c:\\path\\HABs.bib"

while in fact `--bibliography` implies `--filter pandoc-citeproc` (as per [README](http://pandoc.org/README.html#citation-rendering))

Please remove first instance of `--filter pandoc-citeproc` (in fact you can safely remove both, but that's up to you)

**Comment by lierdakil** [comment]
Hell, there is one more problem. `--include-in-header` also overrides `header-includes` metadata that pandoc-crossref uses with LaTeX output. I should probably add this caveat to README.

You could probably add pandoc-crossref definitions yourself, but actual definitions depend on filter settings.

Here is the default verision for reference:

```latex
\AtBeginDocument{%
\renewcommand*\figurename{Figure}
\renewcommand*\tablename{Table}
}
\AtBeginDocument{%
\renewcommand*\listfigurename{List of Figures}
\renewcommand*\listtablename{List of Tables}
}
\usepackage{float}
\floatstyle{ruled}
\makeatletter
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\makeatother
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
```

**Comment by HJAllen** [comment]
Further investigation revealed the following in the .tex file produced by pandoc

```
\paragraph{Structure}\label{structure}

Microcystins are cyclic heptapeptides Figure\ref{fig:MCStruct} with

\includegraphics{../figures/microcystin.png}

\paragraph{Mode of Action}\label{mode-of-action}
```
Is this the intended?  The \includegraphics is not wrapped in \figure and has no label.

Also, I have read some other posts regarding the integration of cross referencing in pandoc and it seems this issue is still quite up in the air.  can you provide any insight into where this is going?
Thanks!

**Comment by tolot27** [comment]
Maybe there is no label because of a bug in the latest pandoc version (1.16.x). See here for a pull reguest: [2637](https://github.com/jgm/pandoc/pull/2637).

BTW: I run into the SoftBreak issue too but fix it by using the latest Haskell platform 7.10.3 and compiled everything again.

**Comment by lierdakil** [comment]
Okay, so I messed up *badly* with 0.1.6.4 release, it pretty much broke LaTeX output for figures. 0.1.6.5 *should* work.

https://github.com/jgm/pandoc/pull/2637 shouldn't affect anything until released, since pandoc-crossref manages LaTeX labels by itself. I will have to remove that after next pandoc release (since I have no idea which version will have that PR included, I can't do that until release)

@HJAllen, I have literally no idea why `\includegraphics` is not wrapped in `figure` environment. It should be. All I can suggest is try updating to pandoc-1.16.0.2 and pandoc-crossref-0.1.6.5.

**Comment by HJAllen** [comment]
success.  I updated pandoc and pandoc-crossref to latest.  I am using Rstudio and knitr which has the pandoc options 'hard coded' in the knit function so I used a lower level command rmarkdown::pandoc_convert to provide the filters in the appropriate order as in:
```
rmarkdown::pandoc_convert("HABsLitReview.Rmd", to="latex",output='HABsLitReview.pdf',citeproc=FALSE,options=c('--filter','pandoc-crossref','--filter','pandoc-citeproc.exe'),verbose=TRUE)
```

**Comment by lierdakil** [comment]
@HJAllen, FYI, https://github.com/rstudio/rmarkdown/commit/07da2572770568234b89ee2951a0b592f46e490f fixes filter order issue. rmarkdown 0.9.3 should have that once released.

**Comment by HJAllen** [comment]
great! thanks for the pointer.
Also, thank you for your hard work on this filter.  As far as my workflow goes, cross-refs, or lack of, were the last thing holding me back and your solution makes markdown and pandoc a great tool!
