### ISSUE TITLE
Request: Move space added between reference prefixes and numbers to the template

### ISSUE THREAD

**Issue by mickley** [lierdakil/pandoc-crossref#52]
If I set up a custom template for something, for example to give a title of Figure B1, then when I reference it, pandoc-crossref adds a space after the figPrefix variable.  So if I set figPrefix to "Fig. B", I will get
 ```Fig. B 1``` instead of  ```Fig. B1```

Moving the space to the template means that users have control over that space instead of it being hardcoded.  

The same might be useful with titles as well, though it's less necessary with the templates.

It's probably an easy change and if I can find the spot in Refs.hs I may try to submit a pull request.

**Comment by danil-tolkachev** [comment]
@mickley, try to set `figPrefixTemplate: "$$i$$"`. See  Customization section in readme.md for additional references.

**Comment by lierdakil** [comment]
Okay, that's something else I forgot to document. There are following YAML options related to figure prefixes:

figPrefixTemplate
eqnPrefixTemplate
tblPrefixTemplate
lstPrefixTemplate
secPrefixTemplate

Those have two variables they understand, `i` -- actual number, and `p` -- actual prefix variable, as set with one of

figPrefix
eqnPrefix
tblPrefix
lstPrefix
secPrefix

Default is `$$p$$&nbsp;$$i$$`

**Comment by lierdakil** [comment]
Finally got around to adding this to docs.
