### ISSUE TITLE
Multiple labels defined. Bugs?

### ISSUE THREAD

**Issue by xoox** [lierdakil/pandoc-crossref#53]
pandoc: 1.16.0.2
pandoc-crossref: 0.1.6.3

When images are used in subsequent paragraphs of lists, multiple labels will be produced.

to reproduce, just save the following code as a file `test.md`

```markdown
1.  list item1

    *   Bullet list1

        1)  inner list 1

            This paragraph will following the inner list 1.

            ![This image will not break the list](image1.png){#fig:image1}

        2)  inner list 2
```

`$ pandoc -t latex -o test.tex --filter pandoc-crossref test.md`

The `test.tex` shows:

```tex
\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  list item1

  \begin{itemize}
  \item
    Bullet list1

    \begin{enumerate}
    \def\labelenumii{\arabic{enumii})}
    \item
      inner list 1

      This paragraph will following the inner list 1.

      \begin{figure}[htbp]
      \centering
      \includegraphics{image1.png}
      \caption{\label{fig:image1}\label{fig:image1}\label{fig:image1}\label{fig:image1}This
      image will not break the list}
      \end{figure}
    \item
      inner list 2
    \end{enumerate}
  \end{itemize}
\end{enumerate}
```

There are four `\label`.

If the image paragraph is not indented by spaces, the inner list 2 will not be generated properly.

BTW, It would be better if `\label` is not in the `\caption` field. That's the expected latex way.

```tex
\begin{figure}[htbp]
      \centering
      \includegraphics{image1.png}
      \caption{This image will not break the list}
      \label{fig:image1}
\end{figure}
```

With `\label` embedded in `\caption`, problems will arise if caption (of figure, table) appear in multiple places.

**Comment by xoox** [comment]
ok. That's four `\label`.
;)

**Comment by lierdakil** [comment]
0.1.6.4 should be fine. Moving label is not that easy, but I'll see what I can do.

**Comment by xoox** [comment]
Using the newly introduced image link_attributes in pandoc, It's easier to add the label feature in the [latex writer](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs)
I know nothing about Haskell. But the following may be a dirty fix to [LaTeX.hs](https://github.com/jgm/pandoc/blob/master/src/Text/Pandoc/Writers/LaTeX.hs)

```haskell
inlineToLaTeX (Span (id',classes,kvs) ils) = do
  ref <- toLabel id'
  let linkAnchor = if null id'
                      then empty
                      else "\\protect\\hypertarget" <> braces (text ref) <>
                             braces empty <> "\\label" <> braces (text ref) -- Here the FIX, ref or id' ?
  let cmds = ["textup" | "csl-no-emph" `elem` classes] ++
             ["textnormal" | "csl-no-strong" `elem` classes ||
                             "csl-no-smallcaps" `elem` classes] ++
             ["RL" | ("dir", "rtl") `elem` kvs] ++
             ["LR" | ("dir", "ltr") `elem` kvs] ++
             (case lookup "lang" kvs of
                Just lng -> let (l, o) = toPolyglossia $ splitBy (=='-') lng
                                ops = if null o then "" else ("[" ++ o ++ "]")
                            in  ["text" ++ l ++ ops]
                Nothing  -> [])
  contents <- inlineListToLaTeX ils
  return $ linkAnchor <>
           if null cmds
              then braces contents
              else foldr inCmd contents cmds
```

The 'id' attribute would be enough.

what the most wanted is 'crossref' would be fully integrated into pandoc.

**Comment by lierdakil** [comment]
Okay, sorry, 1.6.4 is still broken, even more so than 1.6.3.

1.6.5 should work though.

As for moving label definition, https://github.com/jgm/pandoc/pull/2637 should add labels to images automatically (although I'm not sure if it will be picked up by various reference packages correctly), making this a moot point for now.

P.S. It will take a long while before most of functionality of crossref could be moved to pandoc. It would require adding attributes to many more syntax elements, besides figures, and filter will likely still be required. So if it happens, it won't be soon.
