### ISSUE TITLE
[README] Add docs on pandoc-citeproc compatibility

### ISSUE THREAD

**Issue by adamparker** [lierdakil/pandoc-crossref#54]
Hi,

I could not get the figures to cross reference initially, but this is because I was running pandoc with citeproc first.  When I ran just pandoc-crossref it worked.  I don't know if this is a problem with crossref or citeproc or just the way I'm doing it.  Either way I'm letting other people know if they face a similar issue.

This didn't work:

```
pandoc -s -S -c test.css --csl default.csl --metadata link-citations=true --filter pandoc-citeproc --filter pandoc-crossref --bibliography mybib.bib --number-sections input.markdown -o manual.html
```

When I changed them round to the following it worked:

```
pandoc -s -S -c test.css --csl default.csl --metadata link-citations=true --filter pandoc-crossref --filter pandoc-citeproc --bibliography mybib.bib --number-sections input.markdown -o manual.html
```

**Comment by lierdakil** [comment]
Yes, this is expected. You need to run pandoc-citeproc after pandoc-crossref, since former stops if it encounters undefined citation, and latter uses citations as references.

Probably need to add this to readme.

**Comment by adamparker** [comment]
Thanks for the quick reply.
