### ISSUE TITLE
Links between Figure Citations and the Figure

### ISSUE THREAD

**Issue by adamparker** [lierdakil/pandoc-crossref#55]
Hi,

I am converting from markdown to HTML.

I am currently creating a figure like this:

```
![LC male and female duplex connector](images/lcconnector.png){#fig:lcconnector}
```

and I am referencing it like this:

```
An LC connector [[@fig:lcconnector]] is a common connection type seen on fibre cables.
```

The reference is parsed correctly and the correct figure number appears in the output.  However there is no internal hyperlink in the citation.  I looked at the raw HTML and the img tag already has an id attribute set (fig:lcconnector).  The citation (in raw HTML) only needs to change from:

```
[Fig 5.] to <a href="#fig:lcconnector">[Fig. 5]</a>
```

Am I missing the way to do this or is this feature not available?

I'm using the latest version of all tools as far as I can tell.

I am using the following command line:

```
pandoc -s -S -c test.css --csl default.csl --metadata link-citations=true --filter pandoc-crossref --filter pandoc-citeproc --bibliography mybib.bib --number-sections input.markdown -o manual.html
```

Thanks for your efforts on this filter, it's been very useful for me so far and much more enjoyable than using Microsoft Word.  That's a compliment even if it doesn't sound like one. :)

Best Regards,

**Comment by adamparker** [comment]
Ok ignore me.  I worked this out about half an hour after posting.  Egg on my face.

The following way to citate and have an internal link working is:

```
[[[@fig:lcconnector]](#fig:lcconnector)]
```

Hopefully this is the correct way to do it!

**Comment by lierdakil** [comment]
Actually, there's been a request for this https://github.com/lierdakil/pandoc-crossref/issues/30. While your method works for figures in Pandoc 1.16, it wouldn't work on other elements (i.e. tables, etc), since those don't have internal `id` to link to.
