### ISSUE TITLE
Feature request: Number all equations

### ISSUE THREAD

**Issue by Phyks** [lierdakil/pandoc-crossref#56]
Hi,

Would it be possible to have a setting to number all equations by default?

I like to have all my equations numbered, although I do not necessarily reference them further in the document, and would be great if it could be done without having to introduce extra useless labels or using `\begin{equation} … \end{equation}`.

Thanks!

**Comment by lierdakil** [comment]
You can add "empty label" to each equation you want numbered, but not
referenced, e.g.

$$...$${#eq:}

I try to not to be invasive with this filter to avoid breaking existing
work flows. This sometimes comes at the cost of extra verbosity.
25 янв. 2016 г. 16:52 пользователь "Lucas Verney" <notifications@github.com>
написал:

**Comment by Phyks** [comment]
OK.

My proposal is the following:

* Add an `auto_number_equations` option (boolean) to turn on or off the auto-numbering feature (then preventing the necessity to use an empty label on each equation).
* Make it "off" by default to preserve the actual workflow, but still allow people to enable it if they are aware of it and the potential breaking.

What do you think?

**Comment by lierdakil** [comment]
Okay, `master` implements this with `autoEqnLabels` option via f48ec4e2fa5ae89982d6abdf81d3f9a3b5f04d05. This is barely tested, however.

**Comment by Phyks** [comment]
Cool! Thanks! I will try to give it a try ASAP. :)
