### ISSUE TITLE
Referencing/Numbering broken with new pandoc version 1.16

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#57]
With the newest pandoc version 1.16/1.17 and pandoc-crossref the referencing and numbering of figures is completely broken.

The caption changes to `Figure 1: Figure 1: caption` and the reference just to `See fig. .`

I applied pandoc pull request [2637](https://github.com/jgm/pandoc/pull/2637) already but it did not help.

How to reproduce:
```md
# Figure Test

See @fig:figure1.

![First figure](img1.jpg){#fig:figure1}
```

`pandoc -s -o test_figures.pdf -F pandoc-crossref.exe test_figures.md`

**Comment by lierdakil** [comment]
Latest pandoc-crossref should work with pandoc-1.16.0.2 (at least according to my tests, if it doesn't, please provide an example). I don't have time to support master builds at the moment, sorry.

**Comment by lierdakil** [comment]
Wait. My bad. Seems 0.1.6.4 is still broken. Duh. Sorry.

**Comment by lierdakil** [comment]
Okay, 0.1.6.5 should work.

**Comment by tolot27** [comment]
Unfortunately, this simple example does not work anymore with pandoc v1.7.0.2 and crossref v0.2.1.1. The figure label is printed correctly in PDF but the reference does not contain any number, just "See fig. .".
Converting it to tex an additional `\label{fig:figure1}` is added after `\end{figure}`. Removing this additional label and applying pdflatex afterwards produced the expected output.

**Comment by lierdakil** [comment]
Superfluous `\label` at the end is added by Pandoc. There's nothing I can do here, consider v1.17.0.2 broken. v1.17.0.3 fixes this. However, it will still produce two labels. LaTeX doesn't seem to mind much, but I will push a new version of pandoc-crossref in a bit that doesn't add additional labels when built with pandoc 1.17.
