### ISSUE TITLE
Subfigures not working

### ISSUE THREAD

**Issue by willwhitney** [lierdakil/pandoc-crossref#58]
Here's my markdown:

```markdown
<div id="fig:gen">
![](../figures/AZ_VARIED_scatter.png)

![](../figures/EL_VARIED_scatter.png)

![](../figures/LIGHT_AZ_VARIED_scatter.png)

Captions are great!
</div>
```

and here's the tex it renders to:

```tex
\hypertarget{fig:gen}{}
\begin{figure}[htbp]
\centering
\includegraphics{../figures/AZ_VARIED_scatter.png}
\caption{}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{../figures/EL_VARIED_scatter.png}
\caption{}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics{../figures/LIGHT_AZ_VARIED_scatter.png}
\caption{}
\end{figure}

Captions are great!
```

I'm using up-to-date master, and I'd love to help debug.

**Comment by lierdakil** [comment]
Well, this is still somewhat work-in-progress, hence the lack of release. But this example should work, I think? Let me check.

**Comment by lierdakil** [comment]
Oh. Right. This would work:

```
<div id="fig:gen">
![](../figures/AZ_VARIED_scatter.png){#fig:}

![](../figures/EL_VARIED_scatter.png){#fig:}

![](../figures/LIGHT_AZ_VARIED_scatter.png){#fig:}

Captions are great!
</div>
```

Last snapshot broke subfigures without `id`s.

**Comment by lierdakil** [comment]
Okay, I think ebbc246b2489376f5d654bf1430558bf9a1e6d28 should fix this. Let me know if it doesn't.

**Comment by willwhitney** [comment]
Yup, this makes the subfigures render. Thanks!

However, now I've got new problems for you: https://github.com/lierdakil/pandoc-crossref/issues/59
