### ISSUE TITLE
subfigures break height setting, do not support empty caption

### ISSUE THREAD

**Issue by willwhitney** [lierdakil/pandoc-crossref#59]
Input md:

```markdown
<div id="fig:gen">
![](../figures/AZ_VARIED_scatter.png){height=20%}

![](../figures/EL_VARIED_scatter.png){height=20%}

![](../figures/LIGHT_AZ_VARIED_scatter.png){height=20%}

Captions are great!
</div>
```

output tex:

```tex
\begin{figure}

{\subfloat[]{\includegraphics{../figures/AZ_VARIED_scatter.png}\label{fig:}}}

{\subfloat[]{\includegraphics{../figures/EL_VARIED_scatter.png}\label{fig:}}}

{\subfloat[]{\includegraphics{../figures/LIGHT_AZ_VARIED_scatter.png}\label{fig:}}}

	\caption{{Captions are great!}}

	\label{fig:gen}

\end{figure}
```

resulting pdf:

<img width="672" alt="screenshot 2016-01-28 17 05 47" src="https://cloud.githubusercontent.com/assets/597829/12660367/6654c9a6-c5e1-11e5-88b3-8ec63d36da98.png">

**Comment by lierdakil** [comment]
Okay, *this* is why I didn't make a release. Thanks for reporting. Fixing will take a while though.

**Comment by willwhitney** [comment]
Yup, no worries!

Thank you for your hard work on this package. Without it I would have had to write my thesis in LaTeX instead of markdown, so you've saved me a tremendous amount of pain.

**Comment by lierdakil** [comment]
Should be fixed by latest couple of commits. Note use of `nocaption` class to suppress subfigure caption altogether.
