### ISSUE TITLE
Keep subfigures on the same line in LaTeX output?

### ISSUE THREAD

**Issue by balachia** [lierdakil/pandoc-crossref#60]
Subfigures are currently written into latex with line breaks between them, so that

```md
<div id="fig:coolFig">
![cool caption](coolfiga.png){#fig:cfa width=40%}

![cooler caption](coolfigb.png){#fig:cfb width=40%}

Cool figure!
</div>
```

gets written as 

```latex
\begin{figure}

{\subfloat[cool caption]{\includegraphics[width=0.4\textwidth]{coolfiga.png}\label{fig:cfa}}}

{\subfloat[cooler caption]{\includegraphics[width=0.4\textwidth]{coolfigb.png}\label{fig:cfa}}}

\end{figure}
```

This causes subfigures to be rendered on separate lines, even if they could all fit onto a single row. Is there some way to specify whether these linebreaks should not be written? Or other ways to cause subfigures to appear in a single row?

**Comment by lierdakil** [comment]
You can coerce Pandoc to treat any image as figure. This works:

```markdown
<div id="fig:coolFig">
![cool caption](coolfiga.png "fig:"){#fig:cfa width=40%}
![cooler caption](coolfigb.png "fig:"){#fig:cfb width=40%}

Cool figure!
</div>
```

**Comment by balachia** [comment]
Doesn't that break pandoc-crossref's referencing system? When I run that, I get latex output:

```latex
\hypertarget{fig:coolFig}{}
\includegraphics[width=0.4\textwidth]{coolfiga.png}
\includegraphics[width=0.4\textwidth]{coolfigb.png}

Cool figure!
```

Subfigure labels, and references in the text (`[@fig:coolFig]`) all get clobbered. Is there any way to get both pandoc-crossref to work and single-row figures without writing the tex by hand?

**Comment by lierdakil** [comment]
Did you forget to add "fig:" after image path?
5 марта 2016 г. 0:46 пользователь "Tony Vashevko" <notifications@github.com>
написал:

**Comment by danil-tolkachev** [comment]
I try this

```
<div id="fig:coolFig">
![cool caption](coolfiga.png "fig:"){#fig:cfa width=40%}
![cooler caption](coolfigb.png "fig:"){#fig:cfb width=40%}

Cool figure!
</div>
```

But subfigures captions hide off. Is it posible to show them?

**Comment by lierdakil** [comment]
@danil-tolkachev, what is your output format?

**Comment by danil-tolkachev** [comment]
@lierdakil, html and docx

**Comment by lierdakil** [comment]
At the moment, there is no direct way to get multiple (sub)figures on one line with these.

You could probably hack something together with grid tables, but only `master` supports that at the moment (i.e. you need to build pandoc-crossref from repo)

Example:

```markdown
<div id="fig:coolFig">
+---------------------------------------------------------+-----------------------------------------------------------+
|![cool caption](coolfiga.png "fig:"){#fig:cfa width=100%}|![cooler caption](coolfigb.png "fig:"){#fig:cfb width=100%}|
+---------------------------------------------------------+-----------------------------------------------------------+

Cool figure!
</div>
```

Not sure how that will fare with docx output though. Probably not very well, if I had to guess.

**Comment by danil-tolkachev** [comment]
@lierdakil, thank you. I'll try to build pandoc-crossref, but I'm not sure that I can do it. When is the next release?

**Comment by danil-tolkachev** [comment]
I noticed that image caption doesn't marked with tag `caption` (html output) for coerced subfigures. It's a bug or a feature?

**Comment by danil-tolkachev** [comment]
I'm using the hack with grid tables. It's working, but sometimes it's awkward. If I want place subfigures in the table with same column width, I have to manually add extra spaces for short columns. Moreover, when subcaption is long and/or three or more subfigures are placed in grid table, the source lines of table become very long. It would be handy if pandoc-crossref form this table itself.

For example, the following
```
<div id="fig:coolFig">
![cool caption](coolfiga.png "fig:"){#fig:cfa width=100%}
![cooler caption](coolfigb.png "fig:"){#fig:cfb width=100%}

Cool figure!
</div>
```
is equal to (I'm adding two spaces to get same column width)
```
<div id="fig:coolFig">
+-----------------------------------------------------------+-----------------------------------------------------------+
|![cool caption](coolfiga.png "fig:"){#fig:cfa width=100%}  |![cooler caption](coolfigb.png "fig:"){#fig:cfb width=100%}|
+-----------------------------------------------------------+-----------------------------------------------------------+

Cool figure!
</div>
```

And if I want to place subfigures in the 3x2 table, I just write
```
<div id="fig:coolFig">
![caption a](coolfiga.png){#fig:cfa width=100%}
![caption b](coolfigb.png){#fig:cfb width=100%}
![caption c](coolfigb.png){#fig:cfc width=100%}

![caption d](coolfigd.png){#fig:cfd width=100%}
![caption e](coolfige.png){#fig:cfe width=100%}
![caption f](coolfigf.png){#fig:cff width=100%}

Cool figure!
</div>
```
Of course, this feature would be optional.

**Comment by lierdakil** [comment]
Patch to avoid unsightly `"fig:"` hack for LaTeX output is in `master`. Now syntax like

```markdown
<div id="fig:coolFig">
![cool caption](coolfiga.png){#fig:cfa width=40%}
![cooler caption](coolfigb.png){#fig:cfb width=40%}

![cool caption](coolfiga.png){#fig:cfx width=40%}
![cooler caption](coolfigb.png){#fig:cfy width=40%}

Cool figure!
</div>
```
will work as one would expect, i.e. produce two rows of subfigures side-by-side:

```latex
\begin{figure}

\subfloat[cool
caption]{\includegraphics[width=0.40000\textwidth]{coolfiga.png}\label{fig:cfa}}
\subfloat[cooler
caption]{\includegraphics[width=0.40000\textwidth]{coolfigb.png}\label{fig:cfb}}

\subfloat[cool
caption]{\includegraphics[width=0.40000\textwidth]{coolfiga.png}\label{fig:cfx}}
\subfloat[cooler
caption]{\includegraphics[width=0.40000\textwidth]{coolfigb.png}\label{fig:cfy}}

\caption{Cool figure!}

\label{fig:coolFig}

\end{figure}
```
