### ISSUE TITLE
v0.2.0 fails to build on Windows 10

### ISSUE THREAD

**Issue by treitmaier** [lierdakil/pandoc-crossref#61]
I tried to install pandoc-crossref-0.2.0.0 using cabal. I was able to do so without any problems on my Mac. I followed the same procedure on Windows 10.

I updated cabal

    C:\Users\thomas>cabal update
    Downloading the latest package list from hackage.haskell.org

Made sure that I'm running the latest version of cabal-install.
    
    C:\Users\thomas>cabal install cabal-install
    Resolving dependencies...
    Configuring cabal-install-1.22.9.0...
    Building cabal-install-1.22.9.0...
    Installed cabal-install-1.22.9.0

... and pandoc

    C:\Users\thomas>cabal install pandoc
    Resolving dependencies...
    All the requested packages are already installed:
    pandoc-1.16.0.2

... and pandoc-citeproc.

    C:\Users\thomas>cabal install pandoc-citeproc
    Resolving dependencies...
    All the requested packages are already installed:
    pandoc-citeproc-0.9

However, when I tried to install pandoc-crossref I got the following error message:

    C:\Users\thomas>cabal install pandoc-crossref
    Resolving dependencies...
    Configuring pandoc-crossref-0.2.0.0...
    Building pandoc-crossref-0.2.0.0...
    Failed to install pandoc-crossref-0.2.0.0
    Build log ( C:\Users\thomas\AppData\Roaming\cabal\logs\pandoc-crossref-0.2.0.0.log ):
    Building pandoc-crossref-0.2.0.0...
    Preprocessing library pandoc-crossref-0.2.0.0...
    [ 1 of 17] Compiling Text.Pandoc.CrossRef.Util.Gap ( lib\Text\Pandoc\CrossRef\Util\Gap.hs, dist\build\Text\Pandoc\CrossRef\Util\Gap.o )
    [ 2 of 17] Compiling Text.Pandoc.CrossRef.References.Types ( lib\Text\Pandoc\CrossRef\References\Types.hs, dist\build\Text\Pandoc\CrossRef\References\Types.o )
    ghc.exe: unable to load package `cmark-0.5.1'
    ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc.exe: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
    ghc.exe: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc.exe: warning: accept from ws2_32 is linked instead of __imp_accept
    ghc.exe: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
    ghc.exe: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
    ghc.exe: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
    ghc.exe: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
    ghc.exe: warning: _tzset from msvcrt is linked instead of __imp__tzset
    ghc.exe: C:\Users\thomas\AppData\Roaming\cabal\x86_64-windows-ghc-7.10.2\cmark-0.5.1-AA3TMZczyWi68XcSMdZFBo\HScmark-0.5.1-AA3TMZczyWi68XcSMdZFBo.o: unknown symbol `snprintf'
    cabal: Error: some packages failed to install:
    pandoc-crossref-0.2.0.0 failed during the building phase. The exception was:
    ExitFailure 1

With previous versions of pandoc-crossref, I do not get this error so I believe it's a problem with the v.0.2.0 release.

`C:\Users\thomas>cabal install pandoc-crossref-0.1.6.5`
`Resolving dependencies...`
`Downloading pandoc-crossref-0.1.6.5...`
`Configuring pandoc-crossref-0.1.6.5...`
`Building pandoc-crossref-0.1.6.5...`
`Installed pandoc-crossref-0.1.6.5`

**Comment by treitmaier** [comment]
I've been probing deeper into this issue and found out that if I use stack I can build pandoc-crossref without any errors. Sorry for the false alarm. At least if anybody else experiences this problem, they can try stack.

**Comment by lierdakil** [comment]
Actually I believe this is a GHC bug. Stack automatically uses one of the
later GHC versions. I believe 7.10.3 should be good, but don't quote me on
that.
