### ISSUE TITLE
pandoc-crossref seems broken by pandoc 0.17.0{,.1}

### ISSUE THREAD

**Issue by anntzer** [lierdakil/pandoc-crossref#63]
Sorry, I don't have a minimal example now.  Updating to pandoc 0.17.0 with a rebuilt pandoc-crossref (from the Arch Linux repos) seems to result in references not being resolved.

**Comment by lierdakil** [comment]
Um. pandoc-crossref shouldn't even build with 0.17 (see #62)

**Comment by anntzer** [comment]
I see that the Arch Linux packager came up with a quick hack (basically the same as in #62): https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pandoc-crossref#n21

**Comment by lierdakil** [comment]
Well, travis says that pandoc 1.17 is fine, at least for the most part. https://travis-ci.org/lierdakil/pandoc-crossref/jobs/118379597
So I have no idea what goes wrong for you.

**Comment by lierdakil** [comment]
Try building v0.2.0.1 from hackage (via `cabal install`) or from repo with `stack` (make sure you're using `stack-pandoc-1.17.yaml` as `STACK_YAML`).

**Comment by anntzer** [comment]
Seems to be working now, I don't know what changed.
