### ISSUE TITLE
Tables for equation numbers in docx and html

### ISSUE THREAD

**Issue by danil-tolkachev** [lierdakil/pandoc-crossref#65]
Equation numbers now are injected into equation itself for html and docx output. Is it possible to make tables for equation with numbers? This would be useful for pretty output in these formats. For example, equation with numbers would be rendered as
```markdown
  --------------- -------
    $E = m c^2$     (1.1) 
  --------------- -------
```
in equivalent pandoc's markdown.

**Comment by lierdakil** [comment]
This might lead to unexpected formatting problems... I'll see what I can do.

**Comment by lierdakil** [comment]
Yes... no, this doesn't really work. You usually want your display math to be rendered as display math. If it's crammed into a table cell, this gets pretty unsightly, at least with html output. Notice the giant vertical spacing:

![image](https://cloud.githubusercontent.com/assets/7275622/14337784/a228805c-fc79-11e5-836b-a44134d489db.png)

**Comment by lierdakil** [comment]
Okay, so I made a prototype if you really want to try.

**Comment by lierdakil** [comment]
See commit description https://github.com/lierdakil/pandoc-crossref/commit/6180e376719854dd342e37f397398d7ad6ebfe09

You need to explicitly enable it with `tableEqns` option, either by calling `pandoc` with `-MtableEqns`, or by setting `tableEqns: true` in yaml header/settings file.

**Comment by danil-tolkachev** [comment]
Thank you. In my case there's no such giant vertical spacing. For `docx` output result is almost pretty (it would be pretty if I know how to set central vertical alignment in table cells). For `html` ouput result is not centered and does not fill full width of the page in my case. `Html` looking good if I manually add attribute `style="width:100%;"` to `table` tag.

**Comment by danil-tolkachev** [comment]
@lierdakil, can you add the width style attribute to the table please? It would also be great if there was no need to place an equation on a separate paragraph (for save compatibility with `latex` output).

**Comment by lierdakil** [comment]
There are no style attributes for tables in Pandoc's AST. Nothing I can do.

**Comment by danil-tolkachev** [comment]
I experimented with Pandoc's Ast and found that Pandoc write this attribute if sum of column widths not equal 1. So, if change width of columns from `[0.9, 0.1]` to `[0.9, 0.09]` (line 168 in Block.hs) that would working. 

What about the need for a separate paragraph for equation?

**Comment by lierdakil** [comment]
Sorry about long silence, I was occupied by other things. Separate paragraph is required due to one simple reason: I can't really split a Pandoc block where I want to, and I'd have to do that, since table is a block-level element. So this has to be a block by itself, hence separate paragraph. As for `[0.9, 0.09]` hack, this seems very unreliable to me...

**Comment by lierdakil** [comment]
Okay, so I suppose we could at least try this `[0.9, 0.09]` thing. In `master`.

**Comment by danil-tolkachev** [comment]
Thanks a lot for implementation this may be rare feature.

Hack `[0.9 0.09]` works as expected.

I'm using now own filter to split paragraphs with equations before `pandoc-crossref`. It splits Para block if it contains equation with reference and returns the list of blocks. I write this filter on python. It's no beautiful but works. I think that filter on Haskell can also splits paragraphs. The main reason why I don't split paragraphs in source markdown is incompatibility with latex output. It would be convenient if `pandoc-crossref` can also split paragraphs itself.

Finally I'm interested why do you use Inline Math block for equation number? I think it would be enough simple Para block for that purpose.

Thanks again for your work. `pandoc-crossref` is making it possible to write complex reports in markdown and to export them in various output formats.

**Comment by lierdakil** [comment]
> It would be convenient if pandoc-crossref can also split paragraphs itself.

Okay, committed to master. It's not pretty and does interact with `autoEqnLabels` in an unexpected way. If you could test that on your files that would be nice.

> Finally I'm interested why do you use Display Math block for equation number? I think it would be enough a Str block for that purpose.

Typesetting. I believe having the same font in equation and in its number is more or less something expected. If I just use `Str`, then equation number will have different font size and face in many output formats. Does that make sense?

**Comment by danil-tolkachev** [comment]
>  It's not pretty and does interact with  autoEqnLabels  in an unexpected way. If you could test that on your files that would be nice.

Thank you. I tested `tableEqns` with and without `autoEqnLabels` on my files.  Everything works. If `autoEqnLabels` and `tabelEqns` are `true` then `pandoc-crossref` wraps every equation to table. I believe it is expected way.

> Does that make sense?

No, it doesn't matter. I just thought there may be a typo.

**Comment by jpk3333** [comment]
Sorry, I'm new here and so I don't know if this being "closed" mean I shouldn't post here. 

I wasn't sure I was following properly. I too am interest in having the equations and equation numbers set to the rightmost side of their respective cells. Was the [0.9 0.09] hack supposed to achieve this? If yes, can you walk me through how to implement this? I wasn't sure what "in `master`" meant [here](https://github.com/lierdakil/pandoc-crossref/issues/65#issuecomment-232917959). Thanks!
