### ISSUE TITLE
GHC 8 fixes

### ISSUE THREAD

**Issue by ilovezfs** [lierdakil/pandoc-crossref#69]
Due to a change in the template haskell API, I'm needing to do a bit of patching to get this building successfully under GHC 8 for Homebrew.

In particular, see
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0#template-haskell-2.11.0.0
http://git.haskell.org/ghc.git/commitdiff/575abf42e218925e456bf765abb14f069ac048a0

I've done the following replacements in pandoc-crossref itself:
```
      inreplace "lib/Text/Pandoc/CrossRef/Util/Settings/Template.hs" do |s|
        s.gsub! "DataD _ _ params cons' _", "DataD _ _ params _ cons' _"
        s.gsub! "NewtypeD _ _ params con' _", "NewtypeD _ _ params _ con' _"
        s.gsub! "VarI _ t' _ _ <- reify accName", "VarI _ t' _ <- reify accName"
      end
```

In addition, the dependency data-accessor-template-0.2.1.12 has needed a similar patch, as well as a bump for template-haskell.
```
        inreplace "data-accessor-template.cabal",
          "Build-Depends:  template-haskell >=2.4 && <2.11",
          "Build-Depends:  template-haskell >=2.4 && <2.12"
        inreplace "src-5/Data/Accessor/Template.hs" do |s|
          s.gsub! "DataD _ _ params cons' _ -> return (params, cons')",
            "DataD _ _ params _ cons' _ -> return (params, cons')"
          s.gsub! "NewtypeD _ _ params con' _ -> return (params, [con'])",
            "NewtypeD _ _ params _ con' _ -> return (params, [con'])"
        end
```

Finally, I've had to lift the constraints on some of the dependencies by placing a cabal.config at the root of the sandbox:
```
      (buildpath/"cabal.config").write <<-EOS.undent
        allow-newer: base,time
        constraints: data-accessor-template ==0.2.1.12
      EOS
```
With these changes, pandoc-crossref successfully builds and passes our testing.

**Comment by lierdakil** [comment]
Thanks for this overview. 0.2.2.1 should build out-of-the-box on both 7.10 and 8.0.

**Comment by ilovezfs** [comment]
@lierdakil Thanks. I'll try to remove the patching and see what happens!

**Comment by ilovezfs** [comment]
@lierdakil built sans patching locally :)

FYI: https://github.com/Homebrew/homebrew-core/pull/3014
