### ISSUE TITLE
master fails on Windows spectacularly

### ISSUE THREAD

**Issue by lierdakil** [lierdakil/pandoc-crossref#7]
Evidently, `import Text.Pandoc.Shared (normalizeInlines)` triggers the following behavior:

```
D:\Develop\git\pandoc-crossref>pandoc --filter ./pandoc-crossref.hs -o demo.pdf test.md
pandoc-crossref.hs: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
pandoc-crossref.hs: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
pandoc-crossref.hs: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
pandoc-crossref.hs: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
pandoc-crossref.hs: warning: accept from ws2_32 is linked instead of __imp_accept
pandoc-crossref.hs: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
pandoc-crossref.hs: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
pandoc-crossref.hs: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
pandoc-crossref.hs: warning: _vsnprintf from msvcrt is linked instead of __imp__vsnprintf
pandoc-crossref.hs: warning: GetVersionExA from kernel32 is linked instead of __imp_GetVersionExA
pandoc-crossref.hs: warning: GetModuleHandleA from kernel32 is linked instead of __imp_GetModuleHandleA
pandoc-crossref.hs: warning: GetProcAddress from kernel32 is linked instead of __imp_GetProcAddress
pandoc-crossref.hs: warning: _snprintf from msvcrt is linked instead of __imp__snprintf
pandoc-crossref.hs: warning: GetSystemInfo from kernel32 is linked instead of __imp_GetSystemInfo
pandoc-crossref.hs: warning: GetSystemMetrics from user32 is linked instead of __imp_GetSystemMetrics
pandoc-crossref.hs: warning: GetVersionExA from kernel32 is linked instead of __imp_GetVersionExA
pandoc-crossref.hs: warning: _snprintf from msvcrt is linked instead of __imp__snprintf
pandoc-crossref.hs: warning: GetSystemInfo from kernel32 is linked instead of __imp_GetSystemInfo
pandoc-crossref.hs: warning: GetComputerNameA from kernel32 is linked instead of __imp_GetComputerNameA
pandoc-crossref.hs: warning: CryptAcquireContextA from advapi32 is linked instead of __imp_CryptAcquireContextA
pandoc-crossref.hs: warning: CryptGenRandom from advapi32 is linked instead of __imp_CryptGenRandom
pandoc-crossref.hs: warning: _stat64 from msvcrt is linked instead of __imp__stat64
pandoc-crossref.hs: warning: _open from msvcrt is linked instead of __imp__open
pandoc-crossref.hs: warning: _stat64 from msvcrt is linked instead of __imp__stat64
pandoc-crossref.hs: warning: tolower from msvcrt is linked instead of __imp_tolower
pandoc-crossref.hs: warning: toupper from msvcrt is linked instead of __imp_toupper
pandoc-crossref.hs: warning: isalpha from msvcrt is linked instead of __imp_isalpha
pandoc-crossref.hs: warning: isalnum from msvcrt is linked instead of __imp_isalnum
pandoc-crossref.hs: warning: isupper from msvcrt is linked instead of __imp_isupper
pandoc-crossref.hs: warning: isgraph from msvcrt is linked instead of __imp_isgraph
pandoc-crossref.hs: warning: isprint from msvcrt is linked instead of __imp_isprint
pandoc-crossref.hs: warning: ispunct from msvcrt is linked instead of __imp_ispunct
pandoc-crossref.hs: warning: iscntrl from msvcrt is linked instead of __imp_iscntrl
pandoc-crossref.hs: warning: isupper from msvcrt is linked instead of __imp_isupper
pandoc-crossref.hs: C:\Users\Walter\AppData\Roaming\cabal\x86_64-windows-ghc-7.8.3\hslua-0.3.13\HShslua-0.3.13.o: unknown symbol `mingw_getsp'
pandoc-crossref.hs: pandoc-crossref.hs: unable to load package `hslua-0.3.13'
pandoc: Error running filter ./pandoc-crossref.hs
```

May be related to https://ghc.haskell.org/trac/ghc/ticket/9868

**Comment by tolot27** [comment]
It looks like a 64 bit issue. Using 32 Bit GHC it works. :-)

I'm using the pre-build 32 bit binary (`ghc --make pandoc-crosref.hs`), now.

**Comment by tolot27** [comment]
The most recent version compiles well with 64 bit ghc and the issue is gone.

**Comment by lierdakil** [comment]
Huh. Wierd. Seems like it actually was a ghc bug. Feel free to reopen if this happens again.

**Comment by basmeesters** [comment]
I have got the same problem again with the 64 bit version (on Windows 10).

**Comment by lierdakil** [comment]
I'm sorry to hear that. Unfortunately, I'm extremely busy right now, and
unable to dedicate much time to this issue. If you could test this with
different ghc versions (7.8, 7.10, 32 and 64 bit), that could help.
24 сент. 2015 г. 17:49 пользователь "basmeesters" <notifications@github.com>
написал:

**Comment by basmeesters** [comment]
No problem, I will. Keep you posted

**Comment by basmeesters** [comment]
Didn't get it to work on the last two GHC versions with both 32 and 64 bits. Afterwards I stopped. Maybe I will try some more in the weekend.

**Comment by lierdakil** [comment]
May be relevant:

https://github.com/osa1/hslua/issues/22

**Comment by mickley** [comment]
Hmm sorry for missing the duplicate.  

I also tried compiling with both 32bit and 64bit versions of Haskell Platform after reading the same hslua thread you apparently found.  

The 32bit version also doesn't work, but it fails with a different mingw error.  This time its an unknown symbol "mingw_vsprintf" from the cmark package

**Comment by lierdakil** [comment]
Okay, not sure how you get this. I just dusted off my Windows box with Haskell Platform 7.10.2-a x64 and run `cabal install pandoc-crossref`, which pulled in pandoc and whatnot. No errors or warnings to speak of.

Do you happen to have MSYS or MinGW installed separately from Haskell Platform? Maybe your PATH is confusing ghc there?

**Comment by mickley** [comment]
Nope, this was a clean system of Win7x64 All I installed was Haskell Platform and then ran the following.  First two went fine, not the 3rd.

```
cabal update
cabal install pandoc pandoc-citeproc
cabal install pandoc-crossref
```

**Comment by lierdakil** [comment]
Okay, let me try a clean Windows install then.

**Comment by lierdakil** [comment]
Okay, so apparently, this time it's TemplateHaskell not playing nice with hslua. Little to no idea why that is, exactly. If I had to guess, probably it's just some weird bug in hslua. I *really* don't want to have to write all that declarations by hand...

**Comment by lierdakil** [comment]
Okay, so I have commented on referenced hslua issue. For now, please use 0.1.4.0 -- it doesn't use Template Haskell and only difference at the moment is that 1.5.x provides library interface. I will decide on how to proceed depending on how hslua devs respond (and whether they respond at all)

**Comment by mickley** [comment]
Thank you.  0.1.4.0 installed without a hitch on Win7x64 using:
```
cabal install pandoc-crossref-0.1.4.0
```

**Comment by lierdakil** [comment]
0.1.5.3 removed template haskell dependency for the time being. Please check if it works.
