### ISSUE TITLE
Is there a way to customize label delimiter?

### ISSUE THREAD

**Issue by et2010** [lierdakil/pandoc-crossref#70]
In Chinese formatting style, it is not necessary to separate the label prefix and number with a nbsp, for example: `eq. 1` in Chinese is usually `式1`, there is no space between `式` and `1`. Is it possible in current version? thanks

**Comment by lierdakil** [comment]
See `figureTemplate` metadata option.

**Comment by et2010** [comment]
@lierdakil But that option only affects figure captions.

**Comment by lierdakil** [comment]
Oh. Right. Sorry. See https://github.com/lierdakil/pandoc-crossref/issues/52

**Comment by et2010** [comment]
Thanks, it works now.
