### ISSUE TITLE
Different labels from quoted and unquoted empty strings 

### ISSUE THREAD

**Issue by infotroph** [lierdakil/pandoc-crossref#78]
When defining custom section labels, quoting seems to work differently for empty and non-empty strings:

Unquoted labels work as I expect (barring other weirdness, e.g. spaces in the label):

```{markdown}
---
chapDelim: ""
---

# Main {label=}

## Section 1 {#sec:firstsec}

# Supplement {label=S}

## Section S1 {#sec:othersec}

Prints 'sec. 1 & sec. S1': @sec:firstsec & @sec:othersec
```

Compare to the quoted version, which I was expecting to produce identical output: 

```{markdown}
---
chapDelim: ""
---

# Main {label=""}

## Section 1 {#sec:firstsec}

# Supplement {label="S"}

## Section S1 {#sec:othersec}

Expecting 'sec. 1 & sec. S1', prints 'sec. ""1 & sec. S1': @sec:firstsec & @sec:othersec
```

**Comment by lierdakil** [comment]
What's up with 10 issues, mate?

**Comment by lierdakil** [comment]
#72 #73 #74 #75 #76 #77

**Comment by infotroph** [comment]
Ack! Github weirdness, sorry . Will close the others now.

**Comment by lierdakil** [comment]
Ahead of you on closing bit.

**Comment by lierdakil** [comment]
As for the issue itself, it's Pandoc's fault (or feature?)

e.g. taking your example and running through `pandoc -thtml` gives out

```html
<h1 id="main" label="&quot;&quot;">Main</h1>
<h2 id="sec:firstsec">Section 1</h2>
<h1 id="supplement" label="S">Supplement</h1>
<h2 id="sec:othersec">Section S1</h2>
```

Notice `label="&quot;&quot;"`. `&quot;` being html entity for `"`.

**Comment by infotroph** [comment]
That makes sense. I keep forgetting that Pandoc has attributes of its own ;)

And yeah, once I think of it as a generic key-value pair rather than just as a label I'm less sure which one is the right behavior, so I reckon I'll close this without pestering the Pandoc team. Sorry for the noise.
