### ISSUE TITLE
Leading and trayling spaces are removed from yaml configuration

### ISSUE THREAD

**Issue by danil-tolkachev** [lierdakil/pandoc-crossref#81]
I want to separate subfigure labels by semicolon and space. In markdown I set
```
cssDelim: "; "
```
but that doesn't work because trayling space is removed. I tried to add leading space to `cssTemplate`, but it removed too. Now I'm using non-breaking space for this, but it looks ugly for long captions.

**Comment by lierdakil** [comment]
That's just YAML parser being uncooperative. You can just use html entity for regular space, i.e. `&#32;`. You might also consider other alternatives from Unicode, see http://www.fileformat.info/info/unicode/category/Zs/list.htm

**Comment by lierdakil** [comment]
*that said, if you're aiming for LaTeX export, probably stick with regular/non-breaking space, since text encodings in LaTeX may pose a bit of a challenge for other alternatives.

**Comment by danil-tolkachev** [comment]
Thank you for your advice.
