### ISSUE TITLE
underscores in labels

### ISSUE THREAD

**Issue by MrApe** [lierdakil/pandoc-crossref#88]
Just detected, that underscores(`_`) in labels do not work if you produce pdf output over latex. The underscore is translated to `ux5f` in the `\label{}` command but not in the `\ref{}` command. That obviously breaks references. 

To avoid this, simply do not use underscores in your labels. Dashes (`-`) do work fine.

Best, Jonas

**Comment by lierdakil** [comment]
Um... This indicates that you're using pandoc-crossref that was built with a more recent version of Pandoc that you're running it with. I don't remember the version from the top of my head though.  Try updating Pandoc? Better yet, use one that was built alongside pandoc-crossref?
