### ISSUE TITLE
no latex commands are allowed after label definition

### ISSUE THREAD

**Issue by tolot27** [lierdakil/pandoc-crossref#9]
Just a tiny issue and maybe only for documentation purposes:

Currently, it is not allowed to have some characters or even latex commands after a label definition.

I. e. `![First figure](img1.jpg){#fig:figure1}\todo{write better description}` is not allowed. Just `{#fig:figure1}` is printed. Spaces are allowed.

Okay, it even does not work without the label definition. So probably a pandoc parsing issue or just a syntax violation?

**Comment by lierdakil** [comment]
Pandoc syntax violation. Readme states that this will work only for implicit figures -- those are images, appearing in a paragraph by themselves (which will be drawn as figures with captions). Having raw latex in the same paragraph is not the same as having an image by itself. Furthermore, alt text is treated as figure captions by pandoc only for implicit figures.
