### ISSUE TITLE
Performance issue and html comments

### ISSUE THREAD

**Issue by rafaqz** [lierdakil/pandoc-crossref#91]
Pandoc-crossref has recently ground to a halt on one of my documents - strangely processing html comments.

```
<!-- or <!---
lots of lines with text
lots of [@citation]
- dot points
- etc
-->
```

Removing the commented section, or just the html comment lines themselves instantly returns performance. I had assumed pandoc filters would ignore areas within html comments? 

I'm using the latest pandoc-crossref and pandoc 1.17.2.

**Comment by lierdakil** [comment]
It'd be nice if you could provide a test case. I doubt I'll be able to
easily reproduce just based on the description. Thanks in advance.

27 окт. 2016 г. 10:11 ДП пользователь "rafaqz" <notifications@github.com>
написал:

**Comment by rafaqz** [comment]
Sure... wasn't so keen to post all my random essay notes here ;) 

I'll cut it down and try and find exactly what triggers it.

**Comment by rafaqz** [comment]
Tested. There is no specific text that triggers it. I thought it was increasing slightly super-linearly with lines of comments. But it's probably actually increasing with character length, after testing with a denser test text.

Results of compiling a short document to pdf:
5.37 secs with no comments. Baseline.
9.51 secs with one 15 line comment
14.33 secs with one 15 line comment and 45 line comment.
60.69 secs with one 15 line comment and one 150 line comment.
94 secs with one 15 line comment and one 250 line comment.
154.2 with one dense 150 line comment all "This is some text".

I can't say absolutely it's only this plugin - but if I halt a slow build with lots of comments it _always_ breaks in pandoc-crossref. As you can image its keeping my fan going at a healthy speed, as my script build triggers whenever I save...

Heres my full pandoc command if that helps.

```
pandoc --verbose -r markdown+simple_tables+table_captions+yaml_metadata_block -w latex --filter pandoc-csv2table --filter /home/name/.pandoc/filters/tables.py --filter pandoc-crossref --filter pandoc-fignos --filter pandoc-citeproc --filter pandoc-citeproc-preamble -M citeproc-preamble=/home/name/.pandoc/templates/citeproc-preamble/hangingindent.latex --csl=/home/name/Projects/Uni/Citations/styles/harvard-the-university-of-melbourne.csl --bibliography=/home/name/Projects/Uni/Citations/Library.bib -s -S --template=/home/name/.pandoc/templates/essay --latex-engine=pdflatex -o essay.pdf essay.md
```

**Comment by rafaqz** [comment]
Just to be clear running a stripped down command with only pandoc-crossref as a filter has the same results

```
pandoc --verbose -r markdown -w latex --filter pandoc-crossref -s -S --template=/home/name/.pandoc/templates/essay --latex-engine=pdflatex -o essay.pdf essay.md
```

**Comment by lierdakil** [comment]
The reason why I'm asking for a test case (i.e. input file I could run the tests on) is so that I could run a performance analysis on it. That way, we'll know more or less for sure why it takes so long on seemingly innocent input... I will try to construct a test case based on your comments, but I'm always kinda short on time, so this might take a while.

Also, a quick question: does this happen only with LaTeX output, or with any other format as well?

**Comment by lierdakil** [comment]
Nevermind, I believe I found the culprit. If you're able to build from master, you can try that. Otherwise, I'll try to push out a release before mid-november.

**Comment by rafaqz** [comment]
Cheers!

**Comment by rafaqz** [comment]
Completely fixed. Thankyou!
