### ISSUE TITLE
feature request: support latex's figure*

### ISSUE THREAD

**Issue by laughingrice** [lierdakil/pandoc-crossref#93]
It would be great if it's possible to add support for latex's figure* to produce full width figures in a two column document

**Comment by lierdakil** [comment]
I'd say this request belongs more to [pandoc repo](https://github.com/jgm/pandoc) than here.

No plans on supporting raw LaTeX entities at the moment (this defeats the purpose, why not just use LaTeX then?), and no plans to add extra features unrelated to cross-referencing directly (this project already suffers from feature creep)
