### ISSUE TITLE
Custom numbering for PDF (Fig. S1)

### ISSUE THREAD

**Issue by sjackman** [lierdakil/pandoc-crossref#95]
For supplemental material, I'm using the following custom numbering scheme. It works for HTML but not for PDF. Any tips?
 
```yaml
figPrefix: "Fig."
figLabels: [S1, S2, S3, S4, S5]
```

**Comment by sjackman** [comment]
The following works for PDF output!
```latex
\renewcommand{\thefigure}{S\arabic{figure}}
```
http://www.stat.berkeley.edu/~paciorek/computingTips/Customizing_numbering_pages.html
http://tex.stackexchange.com/questions/85776/change-figure-numbering-for-appendix

**Comment by lierdakil** [comment]
Right. Custom numbering probably isn't *the* way to go here, but yes, it doesn't really work in LaTeX (yet).

However, you can add arbitrary LaTeX commands into `header-includes` metadata field. See pandoc's documentation for more details.

**Comment by sjackman** [comment]
I agree that there's probably a cleaner way, by modifying the template for example, but the following is simple and works quite nicely.

```tex
\renewcommand{\thefigure}{S\arabic{figure}}
\renewcommand{\thetable}{S\arabic{table}}
\renewcommand{\thecodelisting}{S\arabic{codelisting}}
```
