### ISSUE TITLE
Prefix suppression not working for HTML?

### ISSUE THREAD

**Issue by sjackman** [lierdakil/pandoc-crossref#96]
Prefix suppression with `[-@fig:foo]` works as expected with PDF output but not HTML. Is that true?
pandoc-crossref 0.2.3.0

**Comment by lierdakil** [comment]
I have to ask for a test case, since this works as expected  in my tests.

**Comment by sjackman** [comment]
I'm not sure what I'm doing wrong, but at home it's working for neither HTML nor PDF.

pandoc 1.18
pandoc-crossref 0.2.3.0

```markdown
See [-@tbl:foo].

Table: Foo {#tbl:foo}

| A | B |
|---|---|
| 0 | 1 |
```

```sh
pandoc -Fpandoc-crossref -o test.html test.md
```

-------

See tbl. 1.

Table 1: Foo
A	B
0	1

**Comment by lierdakil** [comment]
Can't reproduce (checking with pandoc 1.18 and pandoc-crossref 0.2.3.1 prebuilt, see releases)

Make sure there are no old `pandoc-crossref` executables on PATH.

```
[:~] $ cat test.md
See [-@tbl:foo].

Table: Foo {#tbl:foo}

| A | B |
|---|---|
| 0 | 1 |
[:~] $ pandoc -Fpandoc-crossref -t html test.md
<p>See 1.</p>
<div id="tbl:foo">
<table>
<caption>Table 1: Foo</caption>
<thead>
<tr class="header">
<th>A</th>
<th>B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
[:~] $ pandoc --version
pandoc 1.18
Compiled with pandoc-types 1.17.0.4, texmath 0.8.6.7, highlighting-kate 0.6.3
Default user data directory: /home/livid/.pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by lierdakil** [comment]
Sorry, typo, 0.2.4.1.

Oh. I'm an idiot. 0.2.3.0 didn't have prefix suppression implemented.

**Comment by sjackman** [comment]
Ack, sorry. I should have checked that I had the current release. There is a PR to update `pandoc-crossref` in Homebrew/core: https://github.com/Homebrew/homebrew-core/pull/7226

**Comment by lierdakil** [comment]
You could try to use appropriate prebuilt binary from https://github.com/lierdakil/pandoc-crossref/releases/tag/v0.2.4.1a -- note that I don't guarantee it'll work, since it's built by an automated build script on a virtual machine somewhere, but it's worth a try at least.

**Comment by sjackman** [comment]
I'll wait for the Homebrew bottle. Thanks though, and thanks for your quick response.
