### ISSUE TITLE
tblPrefix not working?

### ISSUE THREAD

**Issue by suknat** [lierdakil/pandoc-crossref#99]
I would like to use a YAML block like this:

```
---
title: Some title
author: AN Other  
date: December 2016
numberSections: TRUE
sectionsDepth: 0
chapters: TRUE
tblPrefix: 
	- “Table”
	- “Tables”
secPrefix:
	- “Section”
	- “Sections”
codeBlockCaptions: True
figureTitle: "Figure \\#"
lofTitle: "## List of Figures"
lotTitle: "## List of Tables"
autoSectionLabels: True
---

```

I've added the above to the beginning of my MD file, but I still get `tbl. 1` instead of `Table 1` in the output. Any idea why?

I've never used the YAML block before so am not even sure I'm doing this correctly. However, I did copy some of the options from the provided example file, so hopefully I'm not a million miles off!

**Comment by lierdakil** [comment]
This shouldn't be the case, although I should point out that you're apparently using typographic quotes in `tblPrefix` and `secPrefix`. You might try removing those altogether to see if it helps any.

The following Markdown works as expected (at least on the latest version and pandoc 1..18):

```markdown
---
title: Some title
author: AN Other  
date: December 2016
numberSections: TRUE
sectionsDepth: 0
chapters: TRUE
tblPrefix: 
- "Table"
- "Tables"
secPrefix:
- "Section"
- "Sections"
codeBlockCaptions: True
figureTitle: "Figure \\#"
lofTitle: "## List of Figures"
lotTitle: "## List of Tables"
autoSectionLabels: True
---

: I have a table {#tbl:tbl1}

| asd |
| --- |
| 123 |

I have a reference [@tbl:tbl1]
```

If you're still running into trouble, post output of `pandoc -t native -s problematic.md` -- provided contents of `problematic.md` are not confidential, of course (I would prefer a constructed example)

**Comment by suknat** [comment]
Ah - works now. It was probably the typographic quotes!
Thanks!
